//! klcompile: compile KL `(defun ...)` forms to Rust function bodies.
//!
//! Input: a `.kl` source file (or any `.kl` from the kernel).
//! Output: a Rust module with one `pub fn aot_<name>(...)` per defun,
//! plus `pub fn install(interp: &mut Interp)` that registers them all.
//!
//! The emitted code calls `shen_cedar::aot::runtime::*` helpers for
//! anything that crosses a function boundary. Plain named calls now go
//! through `rt::apply_direct`, which hits a raw fn pointer table for
//! every AOT-compiled kernel function (populated at install time via
//! `register_aot_direct`). This gives the fast direct AOT-to-AOT path
//! without per-module cross references in the generated code.

use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::ExitCode;

use shen_cedar::kl::ast::KlExpr;
use shen_cedar::kl::parser::parse_all;
use shen_cedar::symbol::Interner;

fn main() -> ExitCode {
    let args: Vec<String> = env::args().collect();
    if args.len() != 3 {
        eprintln!("Usage: klcompile <input.kl> <output.rs>");
        return ExitCode::from(2);
    }
    let input = PathBuf::from(&args[1]);
    let output = PathBuf::from(&args[2]);

    let src = match fs::read_to_string(&input) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("klcompile: read {input:?}: {e}");
            return ExitCode::from(1);
        }
    };

    let mut interner = Interner::new();
    let forms = match parse_all(&src, &mut interner) {
        Ok(f) => f,
        Err(e) => {
            eprintln!("klcompile: parse {input:?}: {e}");
            return ExitCode::from(1);
        }
    };

    // KL allows multiple `(defun NAME …)` for the same NAME — last wins.
    // Find the last index per defun name and skip earlier duplicates so
    // the emitted Rust module only contains one definition per function.
    let mut last_index = std::collections::HashMap::new();
    for (i, form) in forms.iter().enumerate() {
        if let Some(name) = defun_name(form, &interner) {
            last_index.insert(name, i);
        }
    }

    let mut g = Codegen::new(&interner);
    g.emit_header(&input);
    let mut compiled = Vec::new();
    let mut skipped = Vec::new();
    for (i, form) in forms.iter().enumerate() {
        if let Some(name) = defun_name(form, &interner) {
            if last_index.get(&name) != Some(&i) {
                continue;
            }
            // SLOW_DEFUNS: a handful of kernel functions emit very large
            // bodies (e.g. `stlib.initialise-sources` is a 1.7 MB nested
            // cons of every kernel file's metadata). LLVM optimization
            // takes minutes on these even at opt-level=1 because they
            // all land in one codegen unit. They run once at boot, so
            // skipping AOT and letting the tree-walker handle them
            // costs us nothing meaningful at runtime but saves ~5
            // minutes per release build.
            if SLOW_DEFUNS.contains(&name.as_str()) {
                skipped.push(format!("{name}: known-slow-to-compile (left tree-walked)"));
                continue;
            }
        }
        match g.compile_top(form) {
            Ok(name) => compiled.push(name),
            Err(reason) => skipped.push(reason),
        }
    }
    g.emit_install(&compiled);

    if let Some(parent) = output.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent).ok();
        }
    }
    if let Err(e) = fs::write(&output, g.finish()) {
        eprintln!("klcompile: write {output:?}: {e}");
        return ExitCode::from(1);
    }
    eprintln!(
        "klcompile: {} compiled, {} skipped → {}",
        compiled.len(),
        skipped.len(),
        output.display()
    );
    for s in &skipped {
        eprintln!("  skipped: {s}");
    }
    ExitCode::SUCCESS
}

struct Codegen<'a> {
    out: String,
    interner: &'a Interner,
    counter: usize,
    /// Set while compiling a `(defun NAME ...)`. Used by the tail-call
    /// detector to turn self-calls in tail position into `continue`s.
    current_fn: Option<String>,
    current_params: Vec<String>,
}

impl<'a> Codegen<'a> {
    fn new(interner: &'a Interner) -> Self {
        Self {
            out: String::new(),
            interner,
            counter: 0,
            current_fn: None,
            current_params: Vec::new(),
        }
    }

    fn emit_header(&mut self, input: &std::path::Path) {
        self.out.push_str("//! Auto-generated by `klcompile` from ");
        self.out.push_str(&input.display().to_string());
        self.out.push_str(".\n");
        self.out.push_str("//!\n");
        self.out
            .push_str("//! DO NOT EDIT. Re-run klcompile to regenerate.\n\n");
        self.out
            .push_str("#![allow(unused_variables, unused_braces, unused_imports,\n");
        self.out
            .push_str("    clippy::let_and_return, clippy::needless_question_mark,\n");
        self.out
            .push_str("    clippy::redundant_clone, clippy::needless_late_init,\n");
        self.out
            .push_str("    clippy::len_zero, clippy::needless_borrow,\n");
        self.out
            .push_str("    clippy::approx_constant, clippy::redundant_closure_call,\n");
        self.out.push_str("    non_snake_case)]\n\n");
        // Paths are relative to the `shen-cedar` crate; the generated
        // file is expected to live inside `crates/shen-cedar/src/`.
        self.out.push_str("use crate::aot::runtime as rt;\n");
        self.out
            .push_str("use crate::error::{ShenError, ShenResult};\n");
        self.out.push_str("use crate::interp::eval::Interp;\n");
        self.out.push_str("use crate::value::Value;\n");
        self.out.push_str("use std::rc::Rc;\n\n");
    }

    fn emit_install(&mut self, compiled: &[String]) {
        self.out
            .push_str("/// Register every AOT-compiled function on `interp`. Call after kernel\n");
        self.out
            .push_str("/// boot so these names override the tree-walked defuns.\n");
        self.out.push_str("pub fn install(interp: &mut Interp) {\n");
        for (rust_name, kl_name) in compiled.iter().map(|n| (sanitize_ident(n), n.clone())) {
            let _ = rust_name;
            // Each entry is registered with its declared arity by referencing
            // the helper emitted below.
            self.out.push_str(&format!(
                "    install_{}(interp);\n",
                sanitize_ident(&kl_name)
            ));
        }
        self.out.push_str("}\n\n");
    }

    fn finish(self) -> String {
        self.out
    }

    fn fresh(&mut self) -> String {
        let n = self.counter;
        self.counter += 1;
        format!("__t{n}")
    }

    /// Compile a top-level form. Returns the function name on success or
    /// a `Skipped` reason describing why klcompile bailed.
    fn compile_top(&mut self, form: &KlExpr) -> Result<String, String> {
        let items = match form {
            KlExpr::App(items) => items,
            _ => return Err("top-level non-application".into()),
        };
        if items.len() != 4 {
            return Err(format!("non-defun (length {})", items.len()));
        }
        let head = match &items[0] {
            KlExpr::Sym(s) => self.interner.resolve(*s),
            _ => return Err("head is not a symbol".into()),
        };
        if head != "defun" {
            return Err(format!("non-defun head `{head}`"));
        }
        let name = match &items[1] {
            KlExpr::Sym(s) => self.interner.resolve(*s).to_string(),
            _ => return Err("defun name not a symbol".into()),
        };
        let params: Vec<String> = match &items[2] {
            KlExpr::Nil => Vec::new(),
            KlExpr::App(ps) => {
                let mut out = Vec::with_capacity(ps.len());
                for p in ps.iter() {
                    match p {
                        KlExpr::Sym(s) => out.push(self.interner.resolve(*s).to_string()),
                        _ => return Err("defun param not a symbol".into()),
                    }
                }
                out
            }
            _ => return Err("defun params not a list".into()),
        };
        let body = &items[3];

        let mut scope = Scope::new();
        for p in &params {
            scope.bind(p);
        }

        self.current_fn = Some(name.clone());
        self.current_params = params.clone();
        let body_src = match self.compile_tail(body, &mut scope) {
            Ok(s) => s,
            Err(e) => return Err(format!("`{name}`: {e}")),
        };
        self.current_fn = None;
        self.current_params.clear();

        let rs_name = sanitize_ident(&name);
        self.out
            .push_str(&format!("/// AOT-compiled from KL `(defun {name} ...)`\n"));
        self.out.push_str(&format!(
            "pub fn aot_{rs_name}(interp: &mut Interp, args: &[Value]) -> ShenResult<Value> {{\n"
        ));
        self.out
            .push_str(&format!("    if args.len() != {} {{\n", params.len()));
        self.out
            .push_str("        return Err(ShenError::new(format!(\n");
        self.out.push_str(&format!(
            "            \"{name}: expected {} args, got {{}}\", args.len())));\n",
            params.len()
        ));
        self.out.push_str("    }\n");
        // Params are `mut` because tail-self-calls reassign them in
        // place. Suppress the `unused_mut` warning for cases where the
        // generator doesn't actually emit a tail-self-call.
        for (i, p) in params.iter().enumerate() {
            self.out.push_str(&format!(
                "    #[allow(unused_mut)] let mut {} = args[{i}].clone();\n",
                rust_var(p)
            ));
        }
        // The body is a `loop { ... }`. compile_tail emits either
        // `break Ok(value);` for terminal expressions or
        // `{ assign params; continue; }` for self-tail-calls.
        self.out
            .push_str("    #[allow(clippy::never_loop)] loop {\n");
        self.out.push_str(&format!("        {body_src}\n"));
        self.out.push_str("    }\n");
        self.out.push_str("}\n\n");

        // Installer helper.
        self.out
            .push_str(&format!("fn install_{rs_name}(interp: &mut Interp) {{\n"));
        self.out.push_str(&format!(
            "    interp.register_native(\"{name}\", {}, aot_{rs_name});\n",
            params.len()
        ));
        // Also populate the direct-call table for the ultra-fast path.
        self.out.push_str(&format!(
            "    interp.register_aot_direct(\"{name}\", aot_{rs_name});\n"
        ));
        self.out.push_str("}\n\n");

        Ok(name)
    }

    /// Compile a KL expression at tail position. Output is a Rust
    /// *statement block* that either `break`s the enclosing `loop` with
    /// `Ok(value)` or `continue`s after re-binding params (for
    /// self-tail-calls). The trailing-semicolon contract is the caller's
    /// responsibility (we generate one ourselves where needed).
    fn compile_tail(&mut self, expr: &KlExpr, scope: &mut Scope) -> Result<String, String> {
        if let KlExpr::App(items) = expr {
            if !items.is_empty() {
                let head_name = if let KlExpr::Sym(s) = &items[0] {
                    Some(self.interner.resolve(*s).to_string())
                } else {
                    None
                };
                if let Some(head) = head_name.as_deref() {
                    match head {
                        "if" => return self.compile_tail_if(&items[1..], scope),
                        "let" => return self.compile_tail_let(&items[1..], scope),
                        "cond" => return self.compile_tail_cond(&items[1..], scope),
                        "do" => return self.compile_tail_do(&items[1..], scope),
                        "and" => return self.compile_tail_and(&items[1..], scope),
                        "or" => return self.compile_tail_or(&items[1..], scope),
                        "type" => {
                            if items.len() < 2 {
                                return Err("type: needs at least 1 arg".into());
                            }
                            return self.compile_tail(&items[1], scope);
                        }
                        _ => {}
                    }
                    // Self-tail-call?
                    if self.current_fn.as_deref() == Some(head)
                        && !scope.has(head)
                        && items.len() - 1 == self.current_params.len()
                    {
                        return self.compile_self_tail_call(&items[1..], scope);
                    }
                }
            }
        }
        // Default: compute as a value expression and `break Ok(value)`.
        let src = self.compile_expr(expr, scope)?;
        Ok(format!("break Ok({src});"))
    }

    fn compile_self_tail_call(
        &mut self,
        args: &[KlExpr],
        scope: &mut Scope,
    ) -> Result<String, String> {
        let (binds, names) = self.bind_args(args, scope)?;
        let params = self.current_params.clone();
        let mut assigns = String::new();
        for (p, n) in params.iter().zip(names.iter()) {
            assigns.push_str(&format!("{} = {n}; ", rust_var(p)));
        }
        Ok(format!("{{ {binds}{assigns}continue; }}"))
    }

    fn compile_tail_if(&mut self, args: &[KlExpr], scope: &mut Scope) -> Result<String, String> {
        if args.len() != 3 {
            return Err("if: expected 3 args".into());
        }
        let c = self.compile_expr(&args[0], scope)?;
        let tv = self.fresh();
        let t = self.compile_tail(&args[1], scope)?;
        let e = self.compile_tail(&args[2], scope)?;
        Ok(format!(
            "{{ let {tv} = {c}; if match rt::is_truthy(interp, &{tv}) {{ Ok(b) => b, Err(e) => break Err(e), }} {{ {t} }} else {{ {e} }} }}"
        ))
    }

    fn compile_tail_let(&mut self, args: &[KlExpr], scope: &mut Scope) -> Result<String, String> {
        if args.len() != 3 {
            return Err("let: expected 3 args".into());
        }
        let var = match &args[0] {
            KlExpr::Sym(s) => self.interner.resolve(*s).to_string(),
            _ => return Err("let: var must be symbol".into()),
        };
        let value_src = self.compile_expr(&args[1], scope)?;
        scope.bind(&var);
        let body_src = self.compile_tail(&args[2], scope)?;
        scope.unbind(&var);
        Ok(format!(
            "{{ let {} = {value_src}; {body_src} }}",
            rust_var(&var)
        ))
    }

    fn compile_tail_cond(&mut self, args: &[KlExpr], scope: &mut Scope) -> Result<String, String> {
        let mut acc = String::from("break Err(ShenError::new(\"cond: no clause matched\"));");
        for clause in args.iter().rev() {
            let items = match clause {
                KlExpr::App(items) if items.len() == 2 => items,
                _ => return Err("cond: clause must be (test action)".into()),
            };
            let t = self.compile_expr(&items[0], scope)?;
            let v = self.compile_tail(&items[1], scope)?;
            let tv = self.fresh();
            acc = format!(
                "{{ let {tv} = {t}; if match rt::is_truthy(interp, &{tv}) {{ Ok(b) => b, Err(e) => break Err(e), }} {{ {v} }} else {{ {acc} }} }}"
            );
        }
        Ok(acc)
    }

    fn compile_tail_do(&mut self, args: &[KlExpr], scope: &mut Scope) -> Result<String, String> {
        if args.is_empty() {
            return Ok("break Ok(Value::Nil);".into());
        }
        let mut block = String::from("{ ");
        for (i, a) in args.iter().enumerate() {
            if i + 1 == args.len() {
                let tail = self.compile_tail(a, scope)?;
                block.push_str(&tail);
            } else {
                let src = self.compile_expr(a, scope)?;
                block.push_str(&format!("let _ = {src}; "));
            }
        }
        block.push_str(" }");
        Ok(block)
    }

    fn compile_tail_and(&mut self, args: &[KlExpr], scope: &mut Scope) -> Result<String, String> {
        if args.len() != 2 {
            return Err("and: expected 2 args".into());
        }
        let a = self.compile_expr(&args[0], scope)?;
        let av = self.fresh();
        let tail_b = self.compile_tail(&args[1], scope)?;
        Ok(format!(
            "{{ let {av} = {a}; if !match rt::is_truthy(interp, &{av}) {{ Ok(b) => b, Err(e) => break Err(e), }} {{ break Ok(Value::Bool(false)); }} else {{ {tail_b} }} }}"
        ))
    }

    fn compile_tail_or(&mut self, args: &[KlExpr], scope: &mut Scope) -> Result<String, String> {
        if args.len() != 2 {
            return Err("or: expected 2 args".into());
        }
        let a = self.compile_expr(&args[0], scope)?;
        let av = self.fresh();
        let tail_b = self.compile_tail(&args[1], scope)?;
        Ok(format!(
            "{{ let {av} = {a}; if match rt::is_truthy(interp, &{av}) {{ Ok(b) => b, Err(e) => break Err(e), }} {{ break Ok(Value::Bool(true)); }} else {{ {tail_b} }} }}"
        ))
    }

    /// Compile a KL expression. Returns a Rust expression string that
    /// evaluates to `Value`. May use `?` against `ShenResult<Value>`
    /// values — the caller is responsible for being inside a function
    /// returning `ShenResult<Value>`.
    fn compile_expr(&mut self, expr: &KlExpr, scope: &mut Scope) -> Result<String, String> {
        Ok(match expr {
            KlExpr::Nil => "Value::Nil".into(),
            KlExpr::Bool(b) => format!("Value::Bool({b})"),
            KlExpr::Int(n) => format!("Value::Int({n}i64)"),
            KlExpr::Float(x) => format!("Value::Float({x}f64)"),
            KlExpr::Str(s) => format!("Value::Str(Rc::from({:?}))", s.as_ref()),
            KlExpr::Sym(id) => {
                let name = self.interner.resolve(*id);
                if scope.has(name) {
                    format!("{}.clone()", rust_var(name))
                } else {
                    // Free symbol — innocent symbol semantics: evaluate
                    // to the symbol value itself.
                    format!("Value::Sym(interp.intern({:?}))", name)
                }
            }
            KlExpr::App(items) => self.compile_app(items, scope)?,
        })
    }

    fn compile_app(&mut self, items: &[KlExpr], scope: &mut Scope) -> Result<String, String> {
        if items.is_empty() {
            return Ok("Value::Nil".into());
        }
        let head_name = match &items[0] {
            KlExpr::Sym(s) => Some(self.interner.resolve(*s).to_string()),
            _ => None,
        };
        let args = &items[1..];

        if let Some(head) = head_name.as_deref() {
            match head {
                "if" => return self.compile_if(args, scope),
                "let" => return self.compile_let(args, scope),
                "cond" => return self.compile_cond(args, scope),
                "do" => return self.compile_do(args, scope),
                "and" => return self.compile_and(args, scope),
                "or" => return self.compile_or(args, scope),
                "lambda" => return self.compile_lambda(args, scope),
                "freeze" => return self.compile_freeze(args, scope),
                "thaw" => return self.compile_thaw(args, scope),
                "trap-error" => return self.compile_trap_error(args, scope),
                "type" => {
                    if args.is_empty() {
                        return Err("type: needs at least 1 arg".into());
                    }
                    return self.compile_expr(&args[0], scope);
                }
                "quote" => {
                    if args.len() != 1 {
                        return Err("quote: needs 1 arg".into());
                    }
                    return self.compile_quote(&args[0]);
                }
                _ => {}
            }

            // Locals shadow the function namespace: if `head` is a local
            // var, it's a value (closure) and we apply it.
            if scope.has(head) {
                let (binds, names) = self.bind_args(args, scope)?;
                return Ok(format!(
                    "{{ {binds}rt::apply_value(interp, {}.clone(), &[{}])? }}",
                    rust_var(head),
                    names.join(", ")
                ));
            }

            // Inlinable primitive? Emit a direct call to the rt:: helper,
            // bypassing the env-routed apply_named path. release-mode LLVM
            // inlines the helper body so e.g. `(+ X 1)` becomes a direct
            // Value::Int match.
            if let Some((rust_helper, fallible)) = inlinable(head, args.len()) {
                let (binds, names) = self.bind_args(args, scope)?;
                let refs: Vec<String> = names.iter().map(|n| format!("&{n}")).collect();
                let q = if fallible { "?" } else { "" };
                return Ok(format!(
                    "{{ {binds}rt::{rust_helper}({}){q} }}",
                    refs.join(", ")
                ));
            }

            // Plain named call. Uses the direct table (populated for every
            // AOT function at install time) for the fast path when the
            // callee is an AOT-compiled kernel function.
            let (binds, names) = self.bind_args(args, scope)?;
            return Ok(format!(
                "{{ {binds}rt::apply_direct(interp, {:?}, &[{}])? }}",
                head,
                names.join(", ")
            ));
        }

        // Head is itself an expression — must evaluate to a closure.
        let head_src = self.compile_expr(&items[0], scope)?;
        let head_tv = self.fresh();
        let (binds, names) = self.bind_args(args, scope)?;
        Ok(format!(
            "{{ let {head_tv} = {head_src}; {binds}rt::apply_value(interp, {head_tv}, &[{}])? }}",
            names.join(", ")
        ))
    }

    /// Compile each argument and bind it to a fresh local so nested calls
    /// don't overlap mutable borrows of `interp`. Returns the binding
    /// statements and the list of bound names to use as call args.
    fn bind_args(
        &mut self,
        args: &[KlExpr],
        scope: &mut Scope,
    ) -> Result<(String, Vec<String>), String> {
        let mut binds = String::new();
        let mut names = Vec::with_capacity(args.len());
        for a in args {
            let src = self.compile_expr(a, scope)?;
            let tv = self.fresh();
            binds.push_str(&format!("let {tv} = {src}; "));
            names.push(tv);
        }
        Ok((binds, names))
    }

    fn compile_if(&mut self, args: &[KlExpr], scope: &mut Scope) -> Result<String, String> {
        if args.len() != 3 {
            return Err("if: expected 3 args".into());
        }
        let c = self.compile_expr(&args[0], scope)?;
        let t = self.compile_expr(&args[1], scope)?;
        let e = self.compile_expr(&args[2], scope)?;
        let tv = self.fresh();
        Ok(format!(
            "{{ let {tv} = {c}; if rt::is_truthy(interp, &{tv})? {{ {t} }} else {{ {e} }} }}"
        ))
    }

    fn compile_let(&mut self, args: &[KlExpr], scope: &mut Scope) -> Result<String, String> {
        if args.len() != 3 {
            return Err("let: expected 3 args".into());
        }
        let var = match &args[0] {
            KlExpr::Sym(s) => self.interner.resolve(*s).to_string(),
            _ => return Err("let: var must be symbol".into()),
        };
        let value_src = self.compile_expr(&args[1], scope)?;
        scope.bind(&var);
        let body_src = self.compile_expr(&args[2], scope)?;
        scope.unbind(&var);
        Ok(format!(
            "{{ let {} = {value_src}; {body_src} }}",
            rust_var(&var)
        ))
    }

    fn compile_cond(&mut self, args: &[KlExpr], scope: &mut Scope) -> Result<String, String> {
        // Compile (cond (T1 V1) (T2 V2) ... (true VN)) as nested if/else.
        // We don't have a "no-clause-matched" trap in this fast path —
        // the kernel always ends with a `(true ...)` clause.
        let mut acc = String::from("return Err(ShenError::new(\"cond: no clause matched\"))");
        for clause in args.iter().rev() {
            let items = match clause {
                KlExpr::App(items) if items.len() == 2 => items,
                _ => return Err("cond: clause must be (test action)".into()),
            };
            let t = self.compile_expr(&items[0], scope)?;
            let v = self.compile_expr(&items[1], scope)?;
            let tv = self.fresh();
            acc = format!(
                "{{ let {tv} = {t}; if rt::is_truthy(interp, &{tv})? {{ {v} }} else {{ {acc} }} }}"
            );
        }
        Ok(acc)
    }

    fn compile_do(&mut self, args: &[KlExpr], scope: &mut Scope) -> Result<String, String> {
        if args.is_empty() {
            return Ok("Value::Nil".into());
        }
        let mut block = String::from("{ ");
        for (i, a) in args.iter().enumerate() {
            let src = self.compile_expr(a, scope)?;
            if i + 1 == args.len() {
                block.push_str(&src);
            } else {
                block.push_str(&format!("let _ = {src}; "));
            }
        }
        block.push_str(" }");
        Ok(block)
    }

    fn compile_and(&mut self, args: &[KlExpr], scope: &mut Scope) -> Result<String, String> {
        if args.len() != 2 {
            return Err("and: expected 2 args".into());
        }
        let a = self.compile_expr(&args[0], scope)?;
        let b = self.compile_expr(&args[1], scope)?;
        let av = self.fresh();
        let bv = self.fresh();
        Ok(format!(
            "{{ let {av} = {a}; if !rt::is_truthy(interp, &{av})? {{ Value::Bool(false) }} else {{ let {bv} = {b}; Value::Bool(rt::is_truthy(interp, &{bv})?) }} }}"
        ))
    }

    fn compile_or(&mut self, args: &[KlExpr], scope: &mut Scope) -> Result<String, String> {
        if args.len() != 2 {
            return Err("or: expected 2 args".into());
        }
        let a = self.compile_expr(&args[0], scope)?;
        let b = self.compile_expr(&args[1], scope)?;
        let av = self.fresh();
        let bv = self.fresh();
        Ok(format!(
            "{{ let {av} = {a}; if rt::is_truthy(interp, &{av})? {{ Value::Bool(true) }} else {{ let {bv} = {b}; Value::Bool(rt::is_truthy(interp, &{bv})?) }} }}"
        ))
    }

    fn compile_lambda(&mut self, args: &[KlExpr], scope: &mut Scope) -> Result<String, String> {
        if args.len() != 2 {
            return Err("lambda: expected (lambda VAR BODY)".into());
        }
        let var = match &args[0] {
            KlExpr::Sym(s) => self.interner.resolve(*s).to_string(),
            _ => return Err("lambda: param not a symbol".into()),
        };
        // Capture only outer vars the body actually references. Sort for
        // stable codegen output across runs.
        let mut captures = self.captures_used(&args[1], scope);
        captures.sort();

        let mut inner_scope = Scope::new();
        for c in &captures {
            inner_scope.bind(c);
        }
        inner_scope.bind(&var);

        let body_src = self.compile_expr(&args[1], &mut inner_scope)?;

        // Emit a Rust closure. `move` captures all clones by value.
        let mut clone_list = String::new();
        for c in &captures {
            clone_list.push_str(&format!("let {0} = {0}.clone(); ", rust_var(c)));
        }
        Ok(format!(
            "{{ {clone_list}rt::make_aot_closure(\"<lambda>\", 1, move |interp, args| {{ let {} = args[0].clone(); Ok({body_src}) }}, interp) }}",
            rust_var(&var)
        ))
    }

    fn compile_freeze(&mut self, args: &[KlExpr], scope: &mut Scope) -> Result<String, String> {
        if args.len() != 1 {
            return Err("freeze: expected 1 arg".into());
        }
        // 0-arity closure. Capture only outer vars the body references.
        let mut captures = self.captures_used(&args[0], scope);
        captures.sort();
        let mut inner_scope = Scope::new();
        for c in &captures {
            inner_scope.bind(c);
        }
        let body_src = self.compile_expr(&args[0], &mut inner_scope)?;
        let mut clone_list = String::new();
        for c in &captures {
            clone_list.push_str(&format!("let {0} = {0}.clone(); ", rust_var(c)));
        }
        Ok(format!(
            "{{ {clone_list}rt::make_aot_closure(\"<freeze>\", 0, move |interp, _args| Ok({body_src}), interp) }}"
        ))
    }

    /// Pick out the subset of `scope.in_scope` that the closure body
    /// might actually look up. Walks the body collecting every
    /// `KlExpr::Sym(s)` reference and keeps only outer-scope names that
    /// appear in that set. Conservative: ignores inner `let`/`lambda`
    /// shadowing, since shadowing is resolved at runtime by
    /// innermost-wins lookup — over-capturing a slot is never wrong,
    /// just slightly larger. The big win is shrinking type-checker
    /// freezes whose body uses 3–5 vars out of a 20–50 entry scope.
    fn captures_used(&self, body: &KlExpr, scope: &Scope) -> Vec<String> {
        if scope.in_scope.is_empty() {
            return Vec::new();
        }
        let mut used: HashSet<String> = HashSet::new();
        self.collect_used_names(body, &mut used);
        if used.is_empty() {
            return Vec::new();
        }
        scope
            .in_scope
            .iter()
            .filter(|name| used.contains(name.as_str()))
            .cloned()
            .collect()
    }

    fn collect_used_names(&self, expr: &KlExpr, out: &mut HashSet<String>) {
        match expr {
            KlExpr::Sym(s) => {
                let name = self.interner.resolve(*s);
                if !out.contains(name) {
                    out.insert(name.to_string());
                }
            }
            KlExpr::App(items) => {
                for child in items.iter() {
                    self.collect_used_names(child, out);
                }
            }
            _ => {}
        }
    }

    fn compile_thaw(&mut self, args: &[KlExpr], scope: &mut Scope) -> Result<String, String> {
        if args.len() != 1 {
            return Err("thaw: expected 1 arg".into());
        }
        let f = self.compile_expr(&args[0], scope)?;
        Ok(format!("rt::apply_value(interp, {f}, &[])?"))
    }

    fn compile_trap_error(&mut self, args: &[KlExpr], scope: &mut Scope) -> Result<String, String> {
        if args.len() != 2 {
            return Err("trap-error: expected 2 args".into());
        }
        let body = self.compile_expr(&args[0], scope)?;
        let handler = self.compile_expr(&args[1], scope)?;
        // Wrap the body in an IIFE so `?` inside it propagates to the
        // closure, not the enclosing AOT function. Catch the error here
        // and dispatch to the handler.
        Ok(format!(
            "match (|| -> ShenResult<Value> {{ Ok({body}) }})() {{ Ok(v) => v, Err(e) => {{ let __h = {handler}; let __err = Value::Error(e.message.clone()); rt::apply_value(interp, __h, &[__err])? }} }}"
        ))
    }

    fn compile_quote(&mut self, expr: &KlExpr) -> Result<String, String> {
        // Quote produces a literal Value. No lookups, no calls.
        Ok(match expr {
            KlExpr::Nil => "Value::Nil".into(),
            KlExpr::Bool(b) => format!("Value::Bool({b})"),
            KlExpr::Int(n) => format!("Value::Int({n}i64)"),
            KlExpr::Float(x) => format!("Value::Float({x}f64)"),
            KlExpr::Str(s) => format!("Value::Str(Rc::from({:?}))", s.as_ref()),
            KlExpr::Sym(id) => format!(
                "Value::Sym(interp.intern({:?}))",
                self.interner.resolve(*id)
            ),
            KlExpr::App(items) => {
                let elems: Vec<String> = items
                    .iter()
                    .map(|e| self.compile_quote(e))
                    .collect::<Result<Vec<_>, _>>()?;
                format!("Value::list([{}])", elems.join(", "))
            }
        })
    }
}

/// Scope tracker: which KL variable names are currently bound to a
/// Rust local. We use a flat `HashSet` because shadowing is rare in
/// kernel code and we only need to answer "is this name in scope".
struct Scope {
    in_scope: HashSet<String>,
}

impl Scope {
    fn new() -> Self {
        Self {
            in_scope: HashSet::new(),
        }
    }
    fn bind(&mut self, name: &str) {
        self.in_scope.insert(name.to_string());
    }
    fn unbind(&mut self, name: &str) {
        self.in_scope.remove(name);
    }
    fn has(&self, name: &str) -> bool {
        self.in_scope.contains(name)
    }
}

/// Map a KL identifier to a Rust variable name (`v_<sanitized>`).
fn rust_var(name: &str) -> String {
    format!("v_{}", sanitize_ident(name))
}

/// Kernel defuns whose source is so large (deeply nested cons literals)
/// that LLVM optimization takes minutes per release build. They run
/// once at boot, so AOT gives no speedup — leave them tree-walked.
const SLOW_DEFUNS: &[&str] = &[
    "stlib.initialise-sources",
    "stlib.initialise-types",
    "stlib.initialise-environment",
    "stlib.initialise-arities",
];

/// Extract the defun name from a top-level form, or None if it isn't a
/// well-formed `(defun NAME ARGS BODY)`.
fn defun_name(form: &KlExpr, interner: &Interner) -> Option<String> {
    let items = match form {
        KlExpr::App(items) => items,
        _ => return None,
    };
    if items.len() != 4 {
        return None;
    }
    let head = match &items[0] {
        KlExpr::Sym(s) => interner.resolve(*s),
        _ => return None,
    };
    if head != "defun" {
        return None;
    }
    match &items[1] {
        KlExpr::Sym(s) => Some(interner.resolve(*s).to_string()),
        _ => None,
    }
}

/// Inlinable primitive table. Returns the `rt::` helper name and whether
/// it returns `ShenResult<Value>` (needs `?`) vs. `Value` (infallible).
/// Arity must match exactly — partial application stays on the
/// apply_named path so its closure semantics are preserved.
fn inlinable(name: &str, arity: usize) -> Option<(&'static str, bool)> {
    let (helper, expected_arity, fallible) = match name {
        "+" => ("add", 2, true),
        "-" => ("sub", 2, true),
        "*" => ("mul", 2, true),
        "/" => ("div", 2, true),
        "<" => ("lt", 2, true),
        ">" => ("gt", 2, true),
        "<=" => ("lte", 2, true),
        ">=" => ("gte", 2, true),
        "=" => ("eq", 2, false),
        "cons" => ("cons", 2, false),
        "hd" => ("hd", 1, true),
        "tl" => ("tl", 1, true),
        "cons?" => ("is_cons", 1, false),
        "number?" => ("is_number", 1, false),
        "string?" => ("is_string", 1, false),
        "symbol?" => ("is_symbol", 1, false),
        "absvector?" => ("is_absvector", 1, false),
        "vector?" => ("is_absvector", 1, false),
        _ => return None,
    };
    if arity == expected_arity {
        Some((helper, fallible))
    } else {
        None
    }
}

/// Map a KL identifier to a Rust-safe form. Non-alphanumeric characters
/// are hex-escaped as `_xHH_` so distinct KL names (`string?`, `string->`,
/// `string->n`) never collapse onto the same Rust ident.
fn sanitize_ident(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    for c in name.chars() {
        if c.is_ascii_alphanumeric() || c == '_' {
            out.push(c);
        } else {
            out.push_str(&format!("_x{:02x}_", c as u32));
        }
    }
    if out.is_empty() {
        out.push('x');
    }
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}
