//! Auto-generated by `klcompile` from kernel/klambda/extension-programmable-pattern-matching.kl.
//!
//! DO NOT EDIT. Re-run klcompile to regenerate.

#![allow(
    unused_variables,
    unused_braces,
    unused_imports,
    clippy::let_and_return,
    clippy::needless_question_mark,
    clippy::redundant_clone,
    clippy::needless_late_init,
    clippy::len_zero,
    clippy::needless_borrow,
    clippy::approx_constant,
    clippy::redundant_closure_call,
    non_snake_case
)]

use crate::aot::runtime as rt;
use crate::error::{ShenError, ShenResult};
use crate::interp::eval::Interp;
use crate::value::Value;
use std::rc::Rc;

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.apply-pattern-handlers ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_apply_x2d_pattern_x2d_handlers(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 5 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.apply-pattern-handlers: expected 5 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7168 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V7169 = args[1].clone();
    #[allow(unused_mut)]
    let mut v_V7170 = args[2].clone();
    #[allow(unused_mut)]
    let mut v_V7171 = args[3].clone();
    #[allow(unused_mut)]
    let mut v_V7172 = args[4].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let __t24 = Value::bool((v_V7168.clone()).is_nil());
            if match rt::is_truthy(interp, &__t24) {
                Ok(b) => b,
                Err(e) => break Err(e),
            } {
                break Ok({ rt::fail(interp) });
            } else {
                {
                    let __t23 = Value::bool(true);
                    if match rt::is_truthy(interp, &__t23) {
                        Ok(b) => b,
                        Err(e) => break Err(e),
                    } {
                        {
                            let __t10 = |interp: &mut Interp| -> ShenResult<Value> {
                                Ok({
                                    let __t9 = {
                                        let __t2 = v_V7168.clone();
                                        rt::is_cons(&__t2)
                                    };
                                    if rt::is_truthy(interp, &__t9)? {
                                        {
                                            let __t4 = {
                                                let __t3 = v_V7168.clone();
                                                rt::tl(&__t3)?
                                            };
                                            let __t5 = v_V7169.clone();
                                            let __t6 = v_V7170.clone();
                                            let __t7 = v_V7171.clone();
                                            let __t8 = v_V7172.clone();
                                            aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_apply_x2d_pattern_x2d_handlers(interp, &[__t4, __t5, __t6, __t7, __t8])?
                                        }
                                    } else {
                                        {
                                            let __t1 = Value::bool(true);
                                            if rt::is_truthy(interp, &__t1)? {
                                                {
                                                    let __t0 = Value::sym(interp.intern_static("shen.x.programmable-pattern-matching.apply-pattern-handlers"));
                                                    rt::apply_direct(
                                                        interp,
                                                        "shen.f-error",
                                                        &[__t0],
                                                    )?
                                                }
                                            } else {
                                                return Err(ShenError::new(
                                                    "cond: no clause matched",
                                                ));
                                            }
                                        }
                                    }
                                })
                            };
                            {
                                let __t12 = {
                                    let __t11 = v_V7168.clone();
                                    rt::is_cons(&__t11)
                                };
                                if match rt::is_truthy(interp, &__t12) {
                                    Ok(b) => b,
                                    Err(e) => break Err(e),
                                } {
                                    {
                                        let v_Result7173 = {
                                            let __t20 = {
                                                let __t18 = {
                                                    let __t16 = {
                                                        let __t14 = {
                                                            let __t13 = v_V7168.clone();
                                                            rt::hd(&__t13)?
                                                        };
                                                        let __t15 = v_V7169.clone();
                                                        rt::apply_value(interp, __t14, &[__t15])?
                                                    };
                                                    let __t17 = v_V7170.clone();
                                                    rt::apply_value(interp, __t16, &[__t17])?
                                                };
                                                let __t19 = v_V7171.clone();
                                                rt::apply_value(interp, __t18, &[__t19])?
                                            };
                                            let __t21 = v_V7172.clone();
                                            rt::apply_value(interp, __t20, &[__t21])?
                                        };
                                        {
                                            let __t22 = Value::bool(
                                                (v_Result7173.clone()).as_sym()
                                                    == Some(interp.well_known.k_shen_fail),
                                            );
                                            if match rt::is_truthy(interp, &__t22) {
                                                Ok(b) => b,
                                                Err(e) => break Err(e),
                                            } {
                                                break Ok(__t10(interp)?);
                                            } else {
                                                break Ok(v_Result7173.clone());
                                            }
                                        }
                                    }
                                } else {
                                    break Ok(__t10(interp)?);
                                }
                            }
                        }
                    } else {
                        break Err(ShenError::new("cond: no clause matched"));
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_apply_x2d_pattern_x2d_handlers(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.apply-pattern-handlers",
        5,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_apply_x2d_pattern_x2d_handlers,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.apply-pattern-handlers",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_apply_x2d_pattern_x2d_handlers,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.make-stack ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_make_x2d_stack(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 0 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.make-stack: expected 0 args, got {}",
            args.len()
        )));
    }
    #[allow(clippy::never_loop)]
    loop {
        break Ok({
            let __t26 = {
                let __t25 = Value::int(1i64);
                rt::apply_direct(interp, "absvector", &[__t25])?
            };
            let __t27 = Value::int(0i64);
            let __t28 = Value::nil();
            rt::address_set(&__t26, &__t27, &__t28)?
        });
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_make_x2d_stack(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.make-stack",
        0,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_make_x2d_stack,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.make-stack",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_make_x2d_stack,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.push ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_push(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 2 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.push: expected 2 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7175 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V7176 = args[1].clone();
    #[allow(clippy::never_loop)]
    loop {
        break Ok({
            let __t29 = v_V7175.clone();
            let __t30 = Value::int(0i64);
            let __t35 = {
                let __t31 = v_V7176.clone();
                let __t34 = {
                    let __t32 = v_V7175.clone();
                    let __t33 = Value::int(0i64);
                    rt::address_ref(&__t32, &__t33)?
                };
                rt::cons(&__t31, &__t34)
            };
            rt::address_set(&__t29, &__t30, &__t35)?
        });
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_push(interp: &mut Interp) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.push",
        2,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_push,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.push",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_push,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.pop-all ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_pop_x2d_all(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 1 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.pop-all: expected 1 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7177 = args[0].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let v_W7178 = {
                let __t36 = v_V7177.clone();
                let __t37 = Value::int(0i64);
                rt::address_ref(&__t36, &__t37)?
            };
            {
                let v_W7179 = {
                    let __t38 = v_V7177.clone();
                    let __t39 = Value::int(0i64);
                    let __t40 = Value::nil();
                    rt::address_set(&__t38, &__t39, &__t40)?
                };
                break Ok(v_W7178.clone());
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_pop_x2d_all(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.pop-all",
        1,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_pop_x2d_all,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.pop-all",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_pop_x2d_all,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.surface-pattern ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 1 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.surface-pattern: expected 1 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7180 = args[0].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let __t69 = {
                let __t58 = {
                    let __t42 = v_V7180.clone();
                    rt::is_cons(&__t42)
                };
                if !rt::is_truthy(interp, &__t58)? {
                    Value::bool(false)
                } else {
                    let __t59 = {
                        let __t56 = Value::bool(
                            ({
                                let __t43 = v_V7180.clone();
                                rt::hd(&__t43)?
                            })
                            .as_sym()
                                == Some(interp.intern_static("cons")),
                        );
                        if !rt::is_truthy(interp, &__t56)? {
                            Value::bool(false)
                        } else {
                            let __t57 = {
                                let __t54 = {
                                    let __t45 = {
                                        let __t44 = v_V7180.clone();
                                        rt::tl(&__t44)?
                                    };
                                    rt::is_cons(&__t45)
                                };
                                if !rt::is_truthy(interp, &__t54)? {
                                    Value::bool(false)
                                } else {
                                    let __t55 = {
                                        let __t52 = {
                                            let __t48 = {
                                                let __t47 = {
                                                    let __t46 = v_V7180.clone();
                                                    rt::tl(&__t46)?
                                                };
                                                rt::tl(&__t47)?
                                            };
                                            rt::is_cons(&__t48)
                                        };
                                        if !rt::is_truthy(interp, &__t52)? {
                                            Value::bool(false)
                                        } else {
                                            let __t53 = Value::bool(
                                                ({
                                                    let __t51 = {
                                                        let __t50 = {
                                                            let __t49 = v_V7180.clone();
                                                            rt::tl(&__t49)?
                                                        };
                                                        rt::tl(&__t50)?
                                                    };
                                                    rt::tl(&__t51)?
                                                })
                                                .is_nil(),
                                            );
                                            Value::bool(rt::is_truthy(interp, &__t53)?)
                                        }
                                    };
                                    Value::bool(rt::is_truthy(interp, &__t55)?)
                                }
                            };
                            Value::bool(rt::is_truthy(interp, &__t57)?)
                        }
                    };
                    Value::bool(rt::is_truthy(interp, &__t59)?)
                }
            };
            if match rt::is_truthy(interp, &__t69) {
                Ok(b) => b,
                Err(e) => break Err(e),
            } {
                break Ok({
                    let __t63 = {
                        let __t62 = {
                            let __t61 = {
                                let __t60 = v_V7180.clone();
                                rt::tl(&__t60)?
                            };
                            rt::hd(&__t61)?
                        };
                        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern(interp, &[__t62])?
                    };
                    let __t68 = {
                        let __t67 = {
                            let __t66 = {
                                let __t65 = {
                                    let __t64 = v_V7180.clone();
                                    rt::tl(&__t64)?
                                };
                                rt::tl(&__t65)?
                            };
                            rt::hd(&__t66)?
                        };
                        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern_x2d_tail(interp, &[__t67])?
                    };
                    rt::cons(&__t63, &__t68)
                });
            } else {
                {
                    let __t41 = Value::bool(true);
                    if match rt::is_truthy(interp, &__t41) {
                        Ok(b) => b,
                        Err(e) => break Err(e),
                    } {
                        break Ok(v_V7180.clone());
                    } else {
                        break Err(ShenError::new("cond: no clause matched"));
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.surface-pattern",
        1,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.surface-pattern",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.surface-pattern-tail ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern_x2d_tail(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 1 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.surface-pattern-tail: expected 1 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7181 = args[0].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let __t99 = Value::bool((v_V7181.clone()).is_nil());
            if match rt::is_truthy(interp, &__t99) {
                Ok(b) => b,
                Err(e) => break Err(e),
            } {
                break Ok(Value::nil());
            } else {
                {
                    let __t98 = {
                        let __t87 = {
                            let __t71 = v_V7181.clone();
                            rt::is_cons(&__t71)
                        };
                        if !rt::is_truthy(interp, &__t87)? {
                            Value::bool(false)
                        } else {
                            let __t88 = {
                                let __t85 = Value::bool(
                                    ({
                                        let __t72 = v_V7181.clone();
                                        rt::hd(&__t72)?
                                    })
                                    .as_sym()
                                        == Some(interp.intern_static("cons")),
                                );
                                if !rt::is_truthy(interp, &__t85)? {
                                    Value::bool(false)
                                } else {
                                    let __t86 = {
                                        let __t83 = {
                                            let __t74 = {
                                                let __t73 = v_V7181.clone();
                                                rt::tl(&__t73)?
                                            };
                                            rt::is_cons(&__t74)
                                        };
                                        if !rt::is_truthy(interp, &__t83)? {
                                            Value::bool(false)
                                        } else {
                                            let __t84 = {
                                                let __t81 = {
                                                    let __t77 = {
                                                        let __t76 = {
                                                            let __t75 = v_V7181.clone();
                                                            rt::tl(&__t75)?
                                                        };
                                                        rt::tl(&__t76)?
                                                    };
                                                    rt::is_cons(&__t77)
                                                };
                                                if !rt::is_truthy(interp, &__t81)? {
                                                    Value::bool(false)
                                                } else {
                                                    let __t82 = Value::bool(
                                                        ({
                                                            let __t80 = {
                                                                let __t79 = {
                                                                    let __t78 = v_V7181.clone();
                                                                    rt::tl(&__t78)?
                                                                };
                                                                rt::tl(&__t79)?
                                                            };
                                                            rt::tl(&__t80)?
                                                        })
                                                        .is_nil(),
                                                    );
                                                    Value::bool(rt::is_truthy(interp, &__t82)?)
                                                }
                                            };
                                            Value::bool(rt::is_truthy(interp, &__t84)?)
                                        }
                                    };
                                    Value::bool(rt::is_truthy(interp, &__t86)?)
                                }
                            };
                            Value::bool(rt::is_truthy(interp, &__t88)?)
                        }
                    };
                    if match rt::is_truthy(interp, &__t98) {
                        Ok(b) => b,
                        Err(e) => break Err(e),
                    } {
                        break Ok({
                            let __t92 = {
                                let __t91 = {
                                    let __t90 = {
                                        let __t89 = v_V7181.clone();
                                        rt::tl(&__t89)?
                                    };
                                    rt::hd(&__t90)?
                                };
                                aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern(interp, &[__t91])?
                            };
                            let __t97 = {
                                let __t96 = {
                                    let __t95 = {
                                        let __t94 = {
                                            let __t93 = v_V7181.clone();
                                            rt::tl(&__t93)?
                                        };
                                        rt::tl(&__t94)?
                                    };
                                    rt::hd(&__t95)?
                                };
                                aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern_x2d_tail(interp, &[__t96])?
                            };
                            rt::cons(&__t92, &__t97)
                        });
                    } else {
                        {
                            let __t70 = Value::bool(true);
                            if match rt::is_truthy(interp, &__t70) {
                                Ok(b) => b,
                                Err(e) => break Err(e),
                            } {
                                break Ok(v_V7181.clone());
                            } else {
                                break Err(ShenError::new("cond: no clause matched"));
                            }
                        }
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern_x2d_tail(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.surface-pattern-tail",
        1,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern_x2d_tail,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.surface-pattern-tail",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern_x2d_tail,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.compile-pattern ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 3 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.compile-pattern: expected 3 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7182 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V7183 = args[1].clone();
    #[allow(unused_mut)]
    let mut v_V7184 = args[2].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let v_W7185 = {
                let __t100 = v_V7182.clone();
                aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern(
                    interp,
                    &[__t100],
                )?
            };
            {
                let v_W7186 = {
                    aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_make_x2d_stack(
                        interp,
                        &[],
                    )?
                };
                {
                    let v_W7187 = Value::sym(interp.intern_static("Self$$7907$$"));
                    {
                        let v_W7188 = {
                            rt::make_aot_closure(
                                "<lambda>",
                                1,
                                move |interp, args| {
                                    let v_Z7189 = args[0].clone();
                                    Ok(Value::sym(interp.intern_static(
                                        "shen.x.programmable-pattern-matching.ignored",
                                    )))
                                },
                                Vec::new(),
                                interp,
                            )
                        };
                        {
                            let v_W7190 = {
                                let v_W7186 = v_W7186.clone();
                                rt::make_aot_closure(
                                    "<lambda>",
                                    1,
                                    move |interp, args| {
                                        let v_Z7191 = args[0].clone();
                                        Ok({
                                            let v_W7186 = v_W7186.clone();
                                            let v_Z7191 = v_Z7191.clone();
                                            rt::make_aot_closure(
                                                "<lambda>",
                                                1,
                                                move |interp, args| {
                                                    let v_Z7192 = args[0].clone();
                                                    Ok({
                                                        let __t101 = v_W7186.clone();
                                                        let __t102 = v_Z7191.clone();
                                                        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_push(interp, &[__t101, __t102])?
                                                    })
                                                },
                                                vec![v_W7186, v_Z7191],
                                                interp,
                                            )
                                        })
                                    },
                                    vec![v_W7186],
                                    interp,
                                )
                            };
                            {
                                let v_W7193 = {
                                    let __t103 = v_V7183.clone();
                                    let __t104 = v_W7187.clone();
                                    let __t105 = v_W7188.clone();
                                    let __t106 = v_W7190.clone();
                                    let __t107 = v_W7185.clone();
                                    aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_apply_x2d_pattern_x2d_handlers(interp, &[__t103, __t104, __t105, __t106, __t107])?
                                };
                                {
                                    let __t108 = Value::bool(
                                        (v_W7193.clone()).as_sym()
                                            == Some(interp.well_known.k_shen_fail),
                                    );
                                    if match rt::is_truthy(interp, &__t108) {
                                        Ok(b) => b,
                                        Err(e) => break Err(e),
                                    } {
                                        break Ok(rt::apply_value(interp, v_V7184.clone(), &[])?);
                                    } else {
                                        break Ok({
                                            let __t109 = Value::sym(interp.intern_static("@p"));
                                            let __t118 = {
                                                let __t110 = Value::sym(
                                                    interp.intern_static("shen.custom-pattern"),
                                                );
                                                let __t117 = {
                                                    let __t115 = {
                                                        let __t111 = v_W7185.clone();
                                                        let __t114 = {
                                                            let __t113 = {
                                                                let __t112 = v_W7186.clone();
                                                                aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_pop_x2d_all(interp, &[__t112])?
                                                            };
                                                            rt::apply_direct(
                                                                interp,
                                                                "reverse",
                                                                &[__t113],
                                                            )?
                                                        };
                                                        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern_x2d_h(interp, &[__t111, __t114])?
                                                    };
                                                    let __t116 = Value::nil();
                                                    rt::cons(&__t115, &__t116)
                                                };
                                                rt::cons(&__t110, &__t117)
                                            };
                                            rt::cons(&__t109, &__t118)
                                        });
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.compile-pattern",
        3,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.compile-pattern",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.compile-pattern-h ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern_x2d_h(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 2 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.compile-pattern-h: expected 2 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7194 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V7195 = args[1].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let __t132 = {
                let __t121 = v_V7194.clone();
                rt::is_cons(&__t121)
            };
            if match rt::is_truthy(interp, &__t132) {
                Ok(b) => b,
                Err(e) => break Err(e),
            } {
                {
                    let v_W7196 = {
                        let __t126 = {
                            let v_V7195 = v_V7195.clone();
                            rt::make_aot_closure(
                                "<lambda>",
                                1,
                                move |interp, args| {
                                    let v_Z7197 = args[0].clone();
                                    Ok({
                                        let __t125 = {
                                            let __t122 = v_Z7197.clone();
                                            let __t123 = v_V7195.clone();
                                            rt::apply_direct(interp, "element?", &[__t122, __t123])?
                                        };
                                        if rt::is_truthy(interp, &__t125)? {
                                            {
                                                let __t124 = v_Z7197.clone();
                                                rt::apply_direct(
                                                    interp,
                                                    "shen.compile-pattern-fragment",
                                                    &[__t124],
                                                )?
                                            }
                                        } else {
                                            v_Z7197.clone()
                                        }
                                    })
                                },
                                vec![v_V7195],
                                interp,
                            )
                        };
                        let __t128 = {
                            let __t127 = v_V7194.clone();
                            rt::tl(&__t127)?
                        };
                        rt::apply_direct(interp, "map", &[__t126, __t128])?
                    };
                    break Ok({
                        let __t130 = {
                            let __t129 = v_V7194.clone();
                            rt::hd(&__t129)?
                        };
                        let __t131 = v_W7196.clone();
                        rt::cons(&__t130, &__t131)
                    });
                }
            } else {
                {
                    let __t120 = Value::bool(true);
                    if match rt::is_truthy(interp, &__t120) {
                        Ok(b) => b,
                        Err(e) => break Err(e),
                    } {
                        break Ok({
                            let __t119 = Value::sym(interp.intern_static(
                                "shen.x.programmable-pattern-matching.compile-pattern-h",
                            ));
                            rt::apply_direct(interp, "shen.f-error", &[__t119])?
                        });
                    } else {
                        break Err(ShenError::new("cond: no clause matched"));
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern_x2d_h(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.compile-pattern-h",
        2,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern_x2d_h,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.compile-pattern-h",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern_x2d_h,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.reduce ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_reduce(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 2 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.reduce: expected 2 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7198 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V7199 = args[1].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let __t157 = {
                let __t135 = v_V7198.clone();
                rt::apply_direct(interp, "tuple?", &[__t135])?
            };
            if match rt::is_truthy(interp, &__t157) {
                Ok(b) => b,
                Err(e) => break Err(e),
            } {
                {
                    let v_W7200 = {
                        let __t137 = {
                            let __t136 = v_V7198.clone();
                            rt::apply_direct(interp, "fst", &[__t136])?
                        };
                        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern(interp, &[__t137])?
                    };
                    {
                        let v_W7201 = {
                            aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_make_x2d_stack(interp, &[])?
                        };
                        {
                            let v_W7202 = {
                                aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_make_x2d_stack(interp, &[])?
                            };
                            {
                                let v_W7203 = {
                                    let v_W7201 = v_W7201.clone();
                                    rt::make_aot_closure(
                                        "<lambda>",
                                        1,
                                        move |interp, args| {
                                            let v_Z7204 = args[0].clone();
                                            Ok({
                                                let __t138 = v_W7201.clone();
                                                let __t139 = v_Z7204.clone();
                                                aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_push(interp, &[__t138, __t139])?
                                            })
                                        },
                                        vec![v_W7201],
                                        interp,
                                    )
                                };
                                {
                                    let v_W7205 = {
                                        let v_W7202 = v_W7202.clone();
                                        rt::make_aot_closure(
                                            "<lambda>",
                                            1,
                                            move |interp, args| {
                                                let v_Z7206 = args[0].clone();
                                                Ok({
                                                    let v_W7202 = v_W7202.clone();
                                                    let v_Z7206 = v_Z7206.clone();
                                                    rt::make_aot_closure(
                                                        "<lambda>",
                                                        1,
                                                        move |interp, args| {
                                                            let v_Z7207 = args[0].clone();
                                                            Ok({
                                                                let __t140 = v_W7202.clone();
                                                                let __t143 = {
                                                                    let __t141 = v_Z7206.clone();
                                                                    let __t142 = v_Z7207.clone();
                                                                    rt::apply_direct(
                                                                        interp,
                                                                        "@p",
                                                                        &[__t141, __t142],
                                                                    )?
                                                                };
                                                                aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_push(interp, &[__t140, __t143])?
                                                            })
                                                        },
                                                        vec![v_W7202, v_Z7206],
                                                        interp,
                                                    )
                                                })
                                            },
                                            vec![v_W7202],
                                            interp,
                                        )
                                    };
                                    {
                                        let v_W7208 = {
                                            let __t144 = v_V7199.clone();
                                            let __t146 = {
                                                let __t145 = v_V7198.clone();
                                                rt::apply_direct(interp, "snd", &[__t145])?
                                            };
                                            let __t147 = v_W7203.clone();
                                            let __t148 = v_W7205.clone();
                                            let __t149 = v_W7200.clone();
                                            aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_apply_x2d_pattern_x2d_handlers(interp, &[__t144, __t146, __t147, __t148, __t149])?
                                        };
                                        {
                                            let __t150 = Value::bool(
                                                (v_W7208.clone()).as_sym()
                                                    == Some(interp.well_known.k_shen_fail),
                                            );
                                            if match rt::is_truthy(interp, &__t150) {
                                                Ok(b) => b,
                                                Err(e) => break Err(e),
                                            } {
                                                break Ok({ rt::fail(interp) });
                                            } else {
                                                break Ok({
                                                    let __t153 = {
                                                        let __t152 = {
                                                            let __t151 = v_W7201.clone();
                                                            aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_pop_x2d_all(interp, &[__t151])?
                                                        };
                                                        rt::apply_direct(
                                                            interp,
                                                            "reverse",
                                                            &[__t152],
                                                        )?
                                                    };
                                                    let __t156 = {
                                                        let __t155 = {
                                                            let __t154 = v_W7202.clone();
                                                            aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_pop_x2d_all(interp, &[__t154])?
                                                        };
                                                        rt::apply_direct(
                                                            interp,
                                                            "reverse",
                                                            &[__t155],
                                                        )?
                                                    };
                                                    rt::apply_direct(
                                                        interp,
                                                        "@p",
                                                        &[__t153, __t156],
                                                    )?
                                                });
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            } else {
                {
                    let __t134 = Value::bool(true);
                    if match rt::is_truthy(interp, &__t134) {
                        Ok(b) => b,
                        Err(e) => break Err(e),
                    } {
                        break Ok({
                            let __t133 = Value::sym(
                                interp.intern_static("shen.x.programmable-pattern-matching.reduce"),
                            );
                            rt::apply_direct(interp, "shen.f-error", &[__t133])?
                        });
                    } else {
                        break Err(ShenError::new("cond: no clause matched"));
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_reduce(interp: &mut Interp) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.reduce",
        2,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_reduce,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.reduce",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_reduce,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.initialise ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_initialise(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 0 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.initialise: expected 0 args, got {}",
            args.len()
        )));
    }
    #[allow(clippy::never_loop)]
    loop {
        {
            let _ = {
                let __v = {
                    rt::make_aot_closure(
                        "<lambda>",
                        1,
                        move |interp, args| {
                            let v_Z7209 = args[0].clone();
                            Ok({
                                let v_Z7209 = v_Z7209.clone();
                                rt::make_aot_closure(
                                    "<lambda>",
                                    1,
                                    move |interp, args| {
                                        let v_Z7210 = args[0].clone();
                                        Ok({
                                            let __t158 = v_Z7209.clone();
                                            let __t159 = rt::global_value(interp, "shen.x.programmable-pattern-matching.*pattern-handlers*")?;
                                            let __t160 = v_Z7210.clone();
                                            aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern(interp, &[__t158, __t159, __t160])?
                                        })
                                    },
                                    vec![v_Z7209],
                                    interp,
                                )
                            })
                        },
                        Vec::new(),
                        interp,
                    )
                };
                rt::set_global(interp, "shen.*custom-pattern-compiler*", __v)
            };
            {
                let _ = {
                    let __v = {
                        rt::make_aot_closure(
                            "<lambda>",
                            1,
                            move |interp, args| {
                                let v_Z7211 = args[0].clone();
                                Ok({
                                    let __t161 = v_Z7211.clone();
                                    let __t162 = rt::global_value(
                                        interp,
                                        "shen.x.programmable-pattern-matching.*pattern-handlers*",
                                    )?;
                                    aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_reduce(interp, &[__t161, __t162])?
                                })
                            },
                            Vec::new(),
                            interp,
                        )
                    };
                    rt::set_global(interp, "shen.*custom-pattern-reducer*", __v)
                };
                {
                    let _ = {
                        let __v = Value::nil();
                        rt::set_global(
                            interp,
                            "shen.x.programmable-pattern-matching.*pattern-handlers*",
                            __v,
                        )
                    };
                    {
                        let _ = {
                            let __v = Value::nil();
                            rt::set_global(
                                interp,
                                "shen.x.programmable-pattern-matching.*pattern-handlers-reg*",
                                __v,
                            )
                        };
                        break Ok(Value::sym(
                            interp.intern_static("shen.x.programmable-pattern-matching.done"),
                        ));
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_initialise(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.initialise",
        0,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_initialise,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.initialise",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_initialise,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.register-handler ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_register_x2d_handler(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 1 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.register-handler: expected 1 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7212 = args[0].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let __t171 = {
                let __t169 = v_V7212.clone();
                let __t170 = rt::global_value(
                    interp,
                    "shen.x.programmable-pattern-matching.*pattern-handlers-reg*",
                )?;
                rt::apply_direct(interp, "element?", &[__t169, __t170])?
            };
            if match rt::is_truthy(interp, &__t171) {
                Ok(b) => b,
                Err(e) => break Err(e),
            } {
                break Ok(v_V7212.clone());
            } else {
                {
                    let __t168 = Value::bool(true);
                    if match rt::is_truthy(interp, &__t168) {
                        Ok(b) => b,
                        Err(e) => break Err(e),
                    } {
                        {
                            let _ = {
                                let __v = {
                                    let __t163 = v_V7212.clone();
                                    let __t164 = rt::global_value(interp, "shen.x.programmable-pattern-matching.*pattern-handlers-reg*")?;
                                    rt::cons(&__t163, &__t164)
                                };
                                rt::set_global(
                                    interp,
                                    "shen.x.programmable-pattern-matching.*pattern-handlers-reg*",
                                    __v,
                                )
                            };
                            {
                                let _ = {
                                    let __v = {
                                        let __t166 = {
                                            let __t165 = v_V7212.clone();
                                            rt::apply_direct(interp, "fn", &[__t165])?
                                        };
                                        let __t167 = rt::global_value(interp, "shen.x.programmable-pattern-matching.*pattern-handlers*")?;
                                        rt::cons(&__t166, &__t167)
                                    };
                                    rt::set_global(
                                        interp,
                                        "shen.x.programmable-pattern-matching.*pattern-handlers*",
                                        __v,
                                    )
                                };
                                break Ok(v_V7212.clone());
                            }
                        }
                    } else {
                        break Err(ShenError::new("cond: no clause matched"));
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_register_x2d_handler(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.register-handler",
        1,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_register_x2d_handler,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.register-handler",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_register_x2d_handler,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.findpos ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 2 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.findpos: expected 2 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7213 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V7214 = args[1].clone();
    #[allow(clippy::never_loop)]
    loop {
        break Ok({
            let __t172 = v_V7213.clone();
            let __t173 = v_V7214.clone();
            let __t174 = Value::int(1i64);
            aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos_x2d_h(
                interp,
                &[__t172, __t173, __t174],
            )?
        });
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos(interp: &mut Interp) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.findpos",
        2,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.findpos",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.findpos-h ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos_x2d_h(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 3 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.findpos-h: expected 3 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7222 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V7223 = args[1].clone();
    #[allow(unused_mut)]
    let mut v_V7224 = args[2].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let __t196 = Value::bool((v_V7223.clone()).is_nil());
            if match rt::is_truthy(interp, &__t196) {
                Ok(b) => b,
                Err(e) => break Err(e),
            } {
                break Ok({
                    let __t195 = {
                        let __t192 = v_V7222.clone();
                        let __t193 = Value::str(" is not a pattern handler\n");
                        let __t194 = Value::sym(interp.intern_static("shen.a"));
                        rt::apply_direct(interp, "shen.app", &[__t192, __t193, __t194])?
                    };
                    rt::apply_direct(interp, "simple-error", &[__t195])?
                });
            } else {
                {
                    let __t191 = {
                        let __t189 = {
                            let __t185 = v_V7223.clone();
                            rt::is_cons(&__t185)
                        };
                        if !rt::is_truthy(interp, &__t189)? {
                            Value::bool(false)
                        } else {
                            let __t190 = {
                                let __t186 = v_V7222.clone();
                                let __t188 = {
                                    let __t187 = v_V7223.clone();
                                    rt::hd(&__t187)?
                                };
                                rt::eq(&__t186, &__t188)
                            };
                            Value::bool(rt::is_truthy(interp, &__t190)?)
                        }
                    };
                    if match rt::is_truthy(interp, &__t191) {
                        Ok(b) => b,
                        Err(e) => break Err(e),
                    } {
                        break Ok(v_V7224.clone());
                    } else {
                        {
                            let __t184 = {
                                let __t177 = v_V7223.clone();
                                rt::is_cons(&__t177)
                            };
                            if match rt::is_truthy(interp, &__t184) {
                                Ok(b) => b,
                                Err(e) => break Err(e),
                            } {
                                {
                                    let __t178 = v_V7222.clone();
                                    let __t180 = {
                                        let __t179 = v_V7223.clone();
                                        rt::tl(&__t179)?
                                    };
                                    let __t183 = {
                                        let __t181 = v_V7224.clone();
                                        let __t182 = Value::int(1i64);
                                        rt::add(&__t181, &__t182)?
                                    };
                                    v_V7222 = __t178;
                                    v_V7223 = __t180;
                                    v_V7224 = __t183;
                                    continue;
                                }
                            } else {
                                {
                                    let __t176 = Value::bool(true);
                                    if match rt::is_truthy(interp, &__t176) {
                                        Ok(b) => b,
                                        Err(e) => break Err(e),
                                    } {
                                        break Ok({
                                            let __t175 = Value::sym(interp.intern_static(
                                                "shen.x.programmable-pattern-matching.findpos-h",
                                            ));
                                            rt::apply_direct(interp, "shen.f-error", &[__t175])?
                                        });
                                    } else {
                                        break Err(ShenError::new("cond: no clause matched"));
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos_x2d_h(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.findpos-h",
        3,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos_x2d_h,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.findpos-h",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos_x2d_h,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.remove-nth ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_remove_x2d_nth(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 2 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.remove-nth: expected 2 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7229 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V7230 = args[1].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let __t223 = {
                let __t222 = {
                    let __t220 = {
                        let __t217 = v_V7229.clone();
                        rt::apply_direct(interp, "integer?", &[__t217])?
                    };
                    if !rt::is_truthy(interp, &__t220)? {
                        Value::bool(false)
                    } else {
                        let __t221 = {
                            let __t218 = v_V7229.clone();
                            let __t219 = Value::int(0i64);
                            rt::gt(&__t218, &__t219)?
                        };
                        Value::bool(rt::is_truthy(interp, &__t221)?)
                    }
                };
                rt::not(interp, &__t222)?
            };
            if match rt::is_truthy(interp, &__t223) {
                Ok(b) => b,
                Err(e) => break Err(e),
            } {
                break Ok(v_V7230.clone());
            } else {
                {
                    let __t216 = Value::bool((v_V7230.clone()).is_nil());
                    if match rt::is_truthy(interp, &__t216) {
                        Ok(b) => b,
                        Err(e) => break Err(e),
                    } {
                        break Ok(Value::nil());
                    } else {
                        {
                            let __t215 = {
                                let __t212 = {
                                    let __t209 = Value::int(1i64);
                                    let __t210 = v_V7229.clone();
                                    rt::eq(&__t209, &__t210)
                                };
                                if !rt::is_truthy(interp, &__t212)? {
                                    Value::bool(false)
                                } else {
                                    let __t213 = {
                                        let __t211 = v_V7230.clone();
                                        rt::is_cons(&__t211)
                                    };
                                    Value::bool(rt::is_truthy(interp, &__t213)?)
                                }
                            };
                            if match rt::is_truthy(interp, &__t215) {
                                Ok(b) => b,
                                Err(e) => break Err(e),
                            } {
                                break Ok({
                                    let __t214 = v_V7230.clone();
                                    rt::tl(&__t214)?
                                });
                            } else {
                                {
                                    let __t208 = {
                                        let __t199 = v_V7230.clone();
                                        rt::is_cons(&__t199)
                                    };
                                    if match rt::is_truthy(interp, &__t208) {
                                        Ok(b) => b,
                                        Err(e) => break Err(e),
                                    } {
                                        break Ok({
                                            let __t201 = {
                                                let __t200 = v_V7230.clone();
                                                rt::hd(&__t200)?
                                            };
                                            let __t207 = {
                                                let __t204 = {
                                                    let __t202 = v_V7229.clone();
                                                    let __t203 = Value::int(1i64);
                                                    rt::sub(&__t202, &__t203)?
                                                };
                                                let __t206 = {
                                                    let __t205 = v_V7230.clone();
                                                    rt::tl(&__t205)?
                                                };
                                                aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_remove_x2d_nth(interp, &[__t204, __t206])?
                                            };
                                            rt::cons(&__t201, &__t207)
                                        });
                                    } else {
                                        {
                                            let __t198 = Value::bool(true);
                                            if match rt::is_truthy(interp, &__t198) {
                                                Ok(b) => b,
                                                Err(e) => break Err(e),
                                            } {
                                                break Ok({
                                                    let __t197 = Value::sym(interp.intern_static("shen.x.programmable-pattern-matching.remove-nth"));
                                                    rt::apply_direct(
                                                        interp,
                                                        "shen.f-error",
                                                        &[__t197],
                                                    )?
                                                });
                                            } else {
                                                break Err(ShenError::new(
                                                    "cond: no clause matched",
                                                ));
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_remove_x2d_nth(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.remove-nth",
        2,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_remove_x2d_nth,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.remove-nth",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_remove_x2d_nth,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.unregister-handler ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_unregister_x2d_handler(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 1 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.unregister-handler: expected 1 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7231 = args[0].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let v_W7232 = rt::global_value(
                interp,
                "shen.x.programmable-pattern-matching.*pattern-handlers-reg*",
            )?;
            {
                let v_W7233 = {
                    let __t224 = v_V7231.clone();
                    let __t225 = v_W7232.clone();
                    aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos(
                        interp,
                        &[__t224, __t225],
                    )?
                };
                {
                    let v_W7234 = {
                        let __v = {
                            let __t226 = v_V7231.clone();
                            let __t227 = v_W7232.clone();
                            rt::apply_direct(interp, "remove", &[__t226, __t227])?
                        };
                        rt::set_global(
                            interp,
                            "shen.x.programmable-pattern-matching.*pattern-handlers-reg*",
                            __v,
                        )
                    };
                    {
                        let v_W7235 = {
                            let __v = {
                                let __t228 = v_W7233.clone();
                                let __t229 = rt::global_value(
                                    interp,
                                    "shen.x.programmable-pattern-matching.*pattern-handlers*",
                                )?;
                                aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_remove_x2d_nth(interp, &[__t228, __t229])?
                            };
                            rt::set_global(
                                interp,
                                "shen.x.programmable-pattern-matching.*pattern-handlers*",
                                __v,
                            )
                        };
                        break Ok(v_V7231.clone());
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_unregister_x2d_handler(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.unregister-handler",
        1,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_unregister_x2d_handler,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.unregister-handler",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_unregister_x2d_handler,
    );
}

/// Register every AOT-compiled function on `interp`. Call after kernel
/// boot so these names override the tree-walked defuns.
pub fn install(interp: &mut Interp) {
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_apply_x2d_pattern_x2d_handlers(
        interp,
    );
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_make_x2d_stack(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_push(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_pop_x2d_all(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern_x2d_tail(
        interp,
    );
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern_x2d_h(
        interp,
    );
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_reduce(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_initialise(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_register_x2d_handler(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos_x2d_h(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_remove_x2d_nth(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_unregister_x2d_handler(interp);
}
