//! Auto-generated by `klcompile` from kernel/klambda/extension-features.kl.
//!
//! DO NOT EDIT. Re-run klcompile to regenerate.

#![allow(
    unused_variables,
    unused_braces,
    unused_imports,
    clippy::let_and_return,
    clippy::needless_question_mark,
    clippy::redundant_clone,
    clippy::needless_late_init,
    clippy::len_zero,
    clippy::needless_borrow,
    clippy::approx_constant,
    clippy::redundant_closure_call,
    non_snake_case
)]

use crate::aot::runtime as rt;
use crate::error::{ShenError, ShenResult};
use crate::interp::eval::Interp;
use crate::value::Value;
use std::rc::Rc;

/// AOT-compiled from KL `(defun shen.x.features.cond-expand-macro ...)`
pub fn aot_shen_x2e_x_x2e_features_x2e_cond_x2d_expand_x2d_macro(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 1 {
        return Err(ShenError::new(format!(
            "shen.x.features.cond-expand-macro: expected 1 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7078 = args[0].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let __t317 = {
                let __t314 = {
                    let __t309 = v_V7078.clone();
                    rt::is_cons(&__t309)
                };
                if !rt::is_truthy(interp, &__t314)? {
                    Value::bool(false)
                } else {
                    let __t315 = {
                        let __t312 = Value::bool(
                            ({
                                let __t310 = v_V7078.clone();
                                rt::hd(&__t310)?
                            })
                            .as_sym()
                                == Some(interp.intern_static("shen.x.features.cond-expand")),
                        );
                        if !rt::is_truthy(interp, &__t312)? {
                            Value::bool(false)
                        } else {
                            let __t313 = Value::bool(
                                ({
                                    let __t311 = v_V7078.clone();
                                    rt::tl(&__t311)?
                                })
                                .is_nil(),
                            );
                            Value::bool(rt::is_truthy(interp, &__t313)?)
                        }
                    };
                    Value::bool(rt::is_truthy(interp, &__t315)?)
                }
            };
            if match rt::is_truthy(interp, &__t317) {
                Ok(b) => b,
                Err(e) => break Err(e),
            } {
                break Ok({
                    let __t316 = Value::str("Unfulfilled shen.x.features.cond-expand clause.");
                    rt::apply_direct(interp, "simple-error", &[__t316])?
                });
            } else {
                {
                    let __t308 = {
                        let __t303 = {
                            let __t281 = v_V7078.clone();
                            rt::is_cons(&__t281)
                        };
                        if !rt::is_truthy(interp, &__t303)? {
                            Value::bool(false)
                        } else {
                            let __t304 = {
                                let __t301 = Value::bool(
                                    ({
                                        let __t282 = v_V7078.clone();
                                        rt::hd(&__t282)?
                                    })
                                    .as_sym()
                                        == Some(
                                            interp.intern_static("shen.x.features.cond-expand"),
                                        ),
                                );
                                if !rt::is_truthy(interp, &__t301)? {
                                    Value::bool(false)
                                } else {
                                    let __t302 = {
                                        let __t299 = {
                                            let __t284 = {
                                                let __t283 = v_V7078.clone();
                                                rt::tl(&__t283)?
                                            };
                                            rt::is_cons(&__t284)
                                        };
                                        if !rt::is_truthy(interp, &__t299)? {
                                            Value::bool(false)
                                        } else {
                                            let __t300 = {
                                                let __t297 = {
                                                    let __t285 = Value::bool(true);
                                                    let __t288 = {
                                                        let __t287 = {
                                                            let __t286 = v_V7078.clone();
                                                            rt::tl(&__t286)?
                                                        };
                                                        rt::hd(&__t287)?
                                                    };
                                                    rt::eq(&__t285, &__t288)
                                                };
                                                if !rt::is_truthy(interp, &__t297)? {
                                                    Value::bool(false)
                                                } else {
                                                    let __t298 = {
                                                        let __t295 = {
                                                            let __t291 = {
                                                                let __t290 = {
                                                                    let __t289 = v_V7078.clone();
                                                                    rt::tl(&__t289)?
                                                                };
                                                                rt::tl(&__t290)?
                                                            };
                                                            rt::is_cons(&__t291)
                                                        };
                                                        if !rt::is_truthy(interp, &__t295)? {
                                                            Value::bool(false)
                                                        } else {
                                                            let __t296 = Value::bool(
                                                                ({
                                                                    let __t294 = {
                                                                        let __t293 = {
                                                                            let __t292 =
                                                                                v_V7078.clone();
                                                                            rt::tl(&__t292)?
                                                                        };
                                                                        rt::tl(&__t293)?
                                                                    };
                                                                    rt::tl(&__t294)?
                                                                })
                                                                .is_nil(),
                                                            );
                                                            Value::bool(rt::is_truthy(
                                                                interp, &__t296,
                                                            )?)
                                                        }
                                                    };
                                                    Value::bool(rt::is_truthy(interp, &__t298)?)
                                                }
                                            };
                                            Value::bool(rt::is_truthy(interp, &__t300)?)
                                        }
                                    };
                                    Value::bool(rt::is_truthy(interp, &__t302)?)
                                }
                            };
                            Value::bool(rt::is_truthy(interp, &__t304)?)
                        }
                    };
                    if match rt::is_truthy(interp, &__t308) {
                        Ok(b) => b,
                        Err(e) => break Err(e),
                    } {
                        break Ok({
                            let __t307 = {
                                let __t306 = {
                                    let __t305 = v_V7078.clone();
                                    rt::tl(&__t305)?
                                };
                                rt::tl(&__t306)?
                            };
                            rt::hd(&__t307)?
                        });
                    } else {
                        {
                            let __t280 = {
                                let __t275 = {
                                    let __t249 = v_V7078.clone();
                                    rt::is_cons(&__t249)
                                };
                                if !rt::is_truthy(interp, &__t275)? {
                                    Value::bool(false)
                                } else {
                                    let __t276 = {
                                        let __t273 =
                                            Value::bool(
                                                ({
                                                    let __t250 = v_V7078.clone();
                                                    rt::hd(&__t250)?
                                                })
                                                .as_sym()
                                                    == Some(interp.intern_static(
                                                        "shen.x.features.cond-expand",
                                                    )),
                                            );
                                        if !rt::is_truthy(interp, &__t273)? {
                                            Value::bool(false)
                                        } else {
                                            let __t274 = {
                                                let __t271 = {
                                                    let __t252 = {
                                                        let __t251 = v_V7078.clone();
                                                        rt::tl(&__t251)?
                                                    };
                                                    rt::is_cons(&__t252)
                                                };
                                                if !rt::is_truthy(interp, &__t271)? {
                                                    Value::bool(false)
                                                } else {
                                                    let __t272 = {
                                                        let __t269 = {
                                                            let __t255 = {
                                                                let __t254 = {
                                                                    let __t253 = v_V7078.clone();
                                                                    rt::tl(&__t253)?
                                                                };
                                                                rt::hd(&__t254)?
                                                            };
                                                            rt::is_cons(&__t255)
                                                        };
                                                        if !rt::is_truthy(interp, &__t269)? {
                                                            Value::bool(false)
                                                        } else {
                                                            let __t270 = {
                                                                let __t267 = Value::bool(
                                                                    ({
                                                                        let __t258 = {
                                                                            let __t257 = {
                                                                                let __t256 =
                                                                                    v_V7078.clone();
                                                                                rt::tl(&__t256)?
                                                                            };
                                                                            rt::hd(&__t257)?
                                                                        };
                                                                        rt::hd(&__t258)?
                                                                    })
                                                                    .as_sym()
                                                                        == Some(
                                                                            interp.intern_static(
                                                                                "and",
                                                                            ),
                                                                        ),
                                                                );
                                                                if !rt::is_truthy(interp, &__t267)?
                                                                {
                                                                    Value::bool(false)
                                                                } else {
                                                                    let __t268 = {
                                                                        let __t265 = Value::bool(({ let __t261 = { let __t260 = { let __t259 = v_V7078.clone(); rt::tl(&__t259)? }; rt::hd(&__t260)? }; rt::tl(&__t261)? }).is_nil());
                                                                        if !rt::is_truthy(
                                                                            interp, &__t265,
                                                                        )? {
                                                                            Value::bool(false)
                                                                        } else {
                                                                            let __t266 = {
                                                                                let __t264 = {
                                                                                    let __t263 = {
                                                                                        let __t262 = v_V7078.clone();
                                                                                        rt::tl(
                                                                                            &__t262,
                                                                                        )?
                                                                                    };
                                                                                    rt::tl(&__t263)?
                                                                                };
                                                                                rt::is_cons(&__t264)
                                                                            };
                                                                            Value::bool(
                                                                                rt::is_truthy(
                                                                                    interp, &__t266,
                                                                                )?,
                                                                            )
                                                                        }
                                                                    };
                                                                    Value::bool(rt::is_truthy(
                                                                        interp, &__t268,
                                                                    )?)
                                                                }
                                                            };
                                                            Value::bool(rt::is_truthy(
                                                                interp, &__t270,
                                                            )?)
                                                        }
                                                    };
                                                    Value::bool(rt::is_truthy(interp, &__t272)?)
                                                }
                                            };
                                            Value::bool(rt::is_truthy(interp, &__t274)?)
                                        }
                                    };
                                    Value::bool(rt::is_truthy(interp, &__t276)?)
                                }
                            };
                            if match rt::is_truthy(interp, &__t280) {
                                Ok(b) => b,
                                Err(e) => break Err(e),
                            } {
                                break Ok({
                                    let __t279 = {
                                        let __t278 = {
                                            let __t277 = v_V7078.clone();
                                            rt::tl(&__t277)?
                                        };
                                        rt::tl(&__t278)?
                                    };
                                    rt::hd(&__t279)?
                                });
                            } else {
                                {
                                    let __t248 = {
                                        let __t221 = {
                                            let __t194 = v_V7078.clone();
                                            rt::is_cons(&__t194)
                                        };
                                        if !rt::is_truthy(interp, &__t221)? {
                                            Value::bool(false)
                                        } else {
                                            let __t222 = {
                                                let __t219 = Value::bool(
                                                    ({
                                                        let __t195 = v_V7078.clone();
                                                        rt::hd(&__t195)?
                                                    })
                                                    .as_sym()
                                                        == Some(interp.intern_static(
                                                            "shen.x.features.cond-expand",
                                                        )),
                                                );
                                                if !rt::is_truthy(interp, &__t219)? {
                                                    Value::bool(false)
                                                } else {
                                                    let __t220 = {
                                                        let __t217 = {
                                                            let __t197 = {
                                                                let __t196 = v_V7078.clone();
                                                                rt::tl(&__t196)?
                                                            };
                                                            rt::is_cons(&__t197)
                                                        };
                                                        if !rt::is_truthy(interp, &__t217)? {
                                                            Value::bool(false)
                                                        } else {
                                                            let __t218 = {
                                                                let __t215 = {
                                                                    let __t200 = {
                                                                        let __t199 = {
                                                                            let __t198 =
                                                                                v_V7078.clone();
                                                                            rt::tl(&__t198)?
                                                                        };
                                                                        rt::hd(&__t199)?
                                                                    };
                                                                    rt::is_cons(&__t200)
                                                                };
                                                                if !rt::is_truthy(interp, &__t215)?
                                                                {
                                                                    Value::bool(false)
                                                                } else {
                                                                    let __t216 = {
                                                                        let __t213 = Value::bool(({ let __t203 = { let __t202 = { let __t201 = v_V7078.clone(); rt::tl(&__t201)? }; rt::hd(&__t202)? }; rt::hd(&__t203)? }).as_sym() == Some(interp.intern_static("and")));
                                                                        if !rt::is_truthy(
                                                                            interp, &__t213,
                                                                        )? {
                                                                            Value::bool(false)
                                                                        } else {
                                                                            let __t214 = {
                                                                                let __t211 = {
                                                                                    let __t207 = {
                                                                                        let __t206 = {
                                                                                            let __t205 = {
                                                                                                let __t204 = v_V7078.clone();
                                                                                                rt::tl(&__t204)?
                                                                                            };
                                                                                            rt::hd(&__t205)?
                                                                                        };
                                                                                        rt::tl(
                                                                                            &__t206,
                                                                                        )?
                                                                                    };
                                                                                    rt::is_cons(
                                                                                        &__t207,
                                                                                    )
                                                                                };
                                                                                if !rt::is_truthy(
                                                                                    interp, &__t211,
                                                                                )? {
                                                                                    Value::bool(
                                                                                        false,
                                                                                    )
                                                                                } else {
                                                                                    let __t212 = {
                                                                                        let __t210 = {
                                                                                            let __t209 = {
                                                                                                let __t208 = v_V7078.clone();
                                                                                                rt::tl(&__t208)?
                                                                                            };
                                                                                            rt::tl(&__t209)?
                                                                                        };
                                                                                        rt::is_cons(
                                                                                            &__t210,
                                                                                        )
                                                                                    };
                                                                                    Value::bool(rt::is_truthy(interp, &__t212)?)
                                                                                }
                                                                            };
                                                                            Value::bool(
                                                                                rt::is_truthy(
                                                                                    interp, &__t214,
                                                                                )?,
                                                                            )
                                                                        }
                                                                    };
                                                                    Value::bool(rt::is_truthy(
                                                                        interp, &__t216,
                                                                    )?)
                                                                }
                                                            };
                                                            Value::bool(rt::is_truthy(
                                                                interp, &__t218,
                                                            )?)
                                                        }
                                                    };
                                                    Value::bool(rt::is_truthy(interp, &__t220)?)
                                                }
                                            };
                                            Value::bool(rt::is_truthy(interp, &__t222)?)
                                        }
                                    };
                                    if match rt::is_truthy(interp, &__t248) {
                                        Ok(b) => b,
                                        Err(e) => break Err(e),
                                    } {
                                        break Ok({
                                            let __t223 = Value::sym(
                                                interp.intern_static("shen.x.features.cond-expand"),
                                            );
                                            let __t247 = {
                                                let __t228 = {
                                                    let __t227 = {
                                                        let __t226 = {
                                                            let __t225 = {
                                                                let __t224 = v_V7078.clone();
                                                                rt::tl(&__t224)?
                                                            };
                                                            rt::hd(&__t225)?
                                                        };
                                                        rt::tl(&__t226)?
                                                    };
                                                    rt::hd(&__t227)?
                                                };
                                                let __t246 = {
                                                    let __t241 = {
                                                        let __t229 =
                                                            Value::sym(interp.intern_static(
                                                                "shen.x.features.cond-expand",
                                                            ));
                                                        let __t240 = {
                                                            let __t236 = {
                                                                let __t230 = Value::sym(
                                                                    interp.intern_static("and"),
                                                                );
                                                                let __t235 = {
                                                                    let __t234 = {
                                                                        let __t233 = {
                                                                            let __t232 = {
                                                                                let __t231 =
                                                                                    v_V7078.clone();
                                                                                rt::tl(&__t231)?
                                                                            };
                                                                            rt::hd(&__t232)?
                                                                        };
                                                                        rt::tl(&__t233)?
                                                                    };
                                                                    rt::tl(&__t234)?
                                                                };
                                                                rt::cons(&__t230, &__t235)
                                                            };
                                                            let __t239 = {
                                                                let __t238 = {
                                                                    let __t237 = v_V7078.clone();
                                                                    rt::tl(&__t237)?
                                                                };
                                                                rt::tl(&__t238)?
                                                            };
                                                            rt::cons(&__t236, &__t239)
                                                        };
                                                        rt::cons(&__t229, &__t240)
                                                    };
                                                    let __t245 = {
                                                        let __t244 = {
                                                            let __t243 = {
                                                                let __t242 = v_V7078.clone();
                                                                rt::tl(&__t242)?
                                                            };
                                                            rt::tl(&__t243)?
                                                        };
                                                        rt::tl(&__t244)?
                                                    };
                                                    rt::cons(&__t241, &__t245)
                                                };
                                                rt::cons(&__t228, &__t246)
                                            };
                                            rt::cons(&__t223, &__t247)
                                        });
                                    } else {
                                        {
                                            let __t193 = {
                                                let __t186 = {
                                                    let __t160 = v_V7078.clone();
                                                    rt::is_cons(&__t160)
                                                };
                                                if !rt::is_truthy(interp, &__t186)? {
                                                    Value::bool(false)
                                                } else {
                                                    let __t187 = {
                                                        let __t184 = Value::bool(
                                                            ({
                                                                let __t161 = v_V7078.clone();
                                                                rt::hd(&__t161)?
                                                            })
                                                            .as_sym()
                                                                == Some(interp.intern_static(
                                                                    "shen.x.features.cond-expand",
                                                                )),
                                                        );
                                                        if !rt::is_truthy(interp, &__t184)? {
                                                            Value::bool(false)
                                                        } else {
                                                            let __t185 = {
                                                                let __t182 = {
                                                                    let __t163 = {
                                                                        let __t162 =
                                                                            v_V7078.clone();
                                                                        rt::tl(&__t162)?
                                                                    };
                                                                    rt::is_cons(&__t163)
                                                                };
                                                                if !rt::is_truthy(interp, &__t182)?
                                                                {
                                                                    Value::bool(false)
                                                                } else {
                                                                    let __t183 = {
                                                                        let __t180 = {
                                                                            let __t166 = {
                                                                                let __t165 = {
                                                                                    let __t164 =
                                                                                        v_V7078
                                                                                            .clone(
                                                                                            );
                                                                                    rt::tl(&__t164)?
                                                                                };
                                                                                rt::hd(&__t165)?
                                                                            };
                                                                            rt::is_cons(&__t166)
                                                                        };
                                                                        if !rt::is_truthy(
                                                                            interp, &__t180,
                                                                        )? {
                                                                            Value::bool(false)
                                                                        } else {
                                                                            let __t181 = {
                                                                                let __t178 = Value::bool(({ let __t169 = { let __t168 = { let __t167 = v_V7078.clone(); rt::tl(&__t167)? }; rt::hd(&__t168)? }; rt::hd(&__t169)? }).as_sym() == Some(interp.intern_static("or")));
                                                                                if !rt::is_truthy(
                                                                                    interp, &__t178,
                                                                                )? {
                                                                                    Value::bool(
                                                                                        false,
                                                                                    )
                                                                                } else {
                                                                                    let __t179 = {
                                                                                        let __t176 = Value::bool(({ let __t172 = { let __t171 = { let __t170 = v_V7078.clone(); rt::tl(&__t170)? }; rt::hd(&__t171)? }; rt::tl(&__t172)? }).is_nil());
                                                                                        if !rt::is_truthy(interp, &__t176)? { Value::bool(false) } else { let __t177 = { let __t175 = { let __t174 = { let __t173 = v_V7078.clone(); rt::tl(&__t173)? }; rt::tl(&__t174)? }; rt::is_cons(&__t175) }; Value::bool(rt::is_truthy(interp, &__t177)?) }
                                                                                    };
                                                                                    Value::bool(rt::is_truthy(interp, &__t179)?)
                                                                                }
                                                                            };
                                                                            Value::bool(
                                                                                rt::is_truthy(
                                                                                    interp, &__t181,
                                                                                )?,
                                                                            )
                                                                        }
                                                                    };
                                                                    Value::bool(rt::is_truthy(
                                                                        interp, &__t183,
                                                                    )?)
                                                                }
                                                            };
                                                            Value::bool(rt::is_truthy(
                                                                interp, &__t185,
                                                            )?)
                                                        }
                                                    };
                                                    Value::bool(rt::is_truthy(interp, &__t187)?)
                                                }
                                            };
                                            if match rt::is_truthy(interp, &__t193) {
                                                Ok(b) => b,
                                                Err(e) => break Err(e),
                                            } {
                                                break Ok({
                                                    let __t188 = Value::sym(interp.intern_static(
                                                        "shen.x.features.cond-expand",
                                                    ));
                                                    let __t192 = {
                                                        let __t191 = {
                                                            let __t190 = {
                                                                let __t189 = v_V7078.clone();
                                                                rt::tl(&__t189)?
                                                            };
                                                            rt::tl(&__t190)?
                                                        };
                                                        rt::tl(&__t191)?
                                                    };
                                                    rt::cons(&__t188, &__t192)
                                                });
                                            } else {
                                                {
                                                    let __t159 = {
                                                        let __t128 = {
                                                            let __t101 = v_V7078.clone();
                                                            rt::is_cons(&__t101)
                                                        };
                                                        if !rt::is_truthy(interp, &__t128)? {
                                                            Value::bool(false)
                                                        } else {
                                                            let __t129 = {
                                                                let __t126 = Value::bool(({ let __t102 = v_V7078.clone(); rt::hd(&__t102)? }).as_sym() == Some(interp.intern_static("shen.x.features.cond-expand")));
                                                                if !rt::is_truthy(interp, &__t126)?
                                                                {
                                                                    Value::bool(false)
                                                                } else {
                                                                    let __t127 = {
                                                                        let __t124 = {
                                                                            let __t104 = {
                                                                                let __t103 =
                                                                                    v_V7078.clone();
                                                                                rt::tl(&__t103)?
                                                                            };
                                                                            rt::is_cons(&__t104)
                                                                        };
                                                                        if !rt::is_truthy(
                                                                            interp, &__t124,
                                                                        )? {
                                                                            Value::bool(false)
                                                                        } else {
                                                                            let __t125 = {
                                                                                let __t122 = {
                                                                                    let __t107 = {
                                                                                        let __t106 = {
                                                                                            let __t105 = v_V7078.clone();
                                                                                            rt::tl(&__t105)?
                                                                                        };
                                                                                        rt::hd(
                                                                                            &__t106,
                                                                                        )?
                                                                                    };
                                                                                    rt::is_cons(
                                                                                        &__t107,
                                                                                    )
                                                                                };
                                                                                if !rt::is_truthy(
                                                                                    interp, &__t122,
                                                                                )? {
                                                                                    Value::bool(
                                                                                        false,
                                                                                    )
                                                                                } else {
                                                                                    let __t123 = {
                                                                                        let __t120 = Value::bool(({ let __t110 = { let __t109 = { let __t108 = v_V7078.clone(); rt::tl(&__t108)? }; rt::hd(&__t109)? }; rt::hd(&__t110)? }).as_sym() == Some(interp.intern_static("or")));
                                                                                        if !rt::is_truthy(interp, &__t120)? { Value::bool(false) } else { let __t121 = { let __t118 = { let __t114 = { let __t113 = { let __t112 = { let __t111 = v_V7078.clone(); rt::tl(&__t111)? }; rt::hd(&__t112)? }; rt::tl(&__t113)? }; rt::is_cons(&__t114) }; if !rt::is_truthy(interp, &__t118)? { Value::bool(false) } else { let __t119 = { let __t117 = { let __t116 = { let __t115 = v_V7078.clone(); rt::tl(&__t115)? }; rt::tl(&__t116)? }; rt::is_cons(&__t117) }; Value::bool(rt::is_truthy(interp, &__t119)?) } }; Value::bool(rt::is_truthy(interp, &__t121)?) }
                                                                                    };
                                                                                    Value::bool(rt::is_truthy(interp, &__t123)?)
                                                                                }
                                                                            };
                                                                            Value::bool(
                                                                                rt::is_truthy(
                                                                                    interp, &__t125,
                                                                                )?,
                                                                            )
                                                                        }
                                                                    };
                                                                    Value::bool(rt::is_truthy(
                                                                        interp, &__t127,
                                                                    )?)
                                                                }
                                                            };
                                                            Value::bool(rt::is_truthy(
                                                                interp, &__t129,
                                                            )?)
                                                        }
                                                    };
                                                    if match rt::is_truthy(interp, &__t159) {
                                                        Ok(b) => b,
                                                        Err(e) => break Err(e),
                                                    } {
                                                        break Ok({
                                                            let __t130 =
                                                                Value::sym(interp.intern_static(
                                                                    "shen.x.features.cond-expand",
                                                                ));
                                                            let __t158 = {
                                                                let __t135 = {
                                                                    let __t134 = {
                                                                        let __t133 = {
                                                                            let __t132 = {
                                                                                let __t131 =
                                                                                    v_V7078.clone();
                                                                                rt::tl(&__t131)?
                                                                            };
                                                                            rt::hd(&__t132)?
                                                                        };
                                                                        rt::tl(&__t133)?
                                                                    };
                                                                    rt::hd(&__t134)?
                                                                };
                                                                let __t157 = {
                                                                    let __t139 = {
                                                                        let __t138 = {
                                                                            let __t137 = {
                                                                                let __t136 =
                                                                                    v_V7078.clone();
                                                                                rt::tl(&__t136)?
                                                                            };
                                                                            rt::tl(&__t137)?
                                                                        };
                                                                        rt::hd(&__t138)?
                                                                    };
                                                                    let __t156 = {
                                                                        let __t140 =
                                                                            Value::bool(true);
                                                                        let __t155 = {
                                                                            let __t153 = {
                                                                                let __t141 = Value::sym(interp.intern_static("shen.x.features.cond-expand"));
                                                                                let __t152 = {
                                                                                    let __t148 = {
                                                                                        let __t142 = Value::sym(interp.intern_static("or"));
                                                                                        let __t147 = {
                                                                                            let __t146 = {
                                                                                                let __t145 = { let __t144 = { let __t143 = v_V7078.clone(); rt::tl(&__t143)? }; rt::hd(&__t144)? };
                                                                                                rt::tl(&__t145)?
                                                                                            };
                                                                                            rt::tl(&__t146)?
                                                                                        };
                                                                                        rt::cons(
                                                                                            &__t142,
                                                                                            &__t147,
                                                                                        )
                                                                                    };
                                                                                    let __t151 = {
                                                                                        let __t150 = {
                                                                                            let __t149 = v_V7078.clone();
                                                                                            rt::tl(&__t149)?
                                                                                        };
                                                                                        rt::tl(
                                                                                            &__t150,
                                                                                        )?
                                                                                    };
                                                                                    rt::cons(
                                                                                        &__t148,
                                                                                        &__t151,
                                                                                    )
                                                                                };
                                                                                rt::cons(
                                                                                    &__t141,
                                                                                    &__t152,
                                                                                )
                                                                            };
                                                                            let __t154 =
                                                                                Value::nil();
                                                                            rt::cons(
                                                                                &__t153, &__t154,
                                                                            )
                                                                        };
                                                                        rt::cons(&__t140, &__t155)
                                                                    };
                                                                    rt::cons(&__t139, &__t156)
                                                                };
                                                                rt::cons(&__t135, &__t157)
                                                            };
                                                            rt::cons(&__t130, &__t158)
                                                        });
                                                    } else {
                                                        {
                                                            let __t100 = {
                                                                let __t76 = {
                                                                    let __t43 = v_V7078.clone();
                                                                    rt::is_cons(&__t43)
                                                                };
                                                                if !rt::is_truthy(interp, &__t76)? {
                                                                    Value::bool(false)
                                                                } else {
                                                                    let __t77 = {
                                                                        let __t74 = Value::bool(({ let __t44 = v_V7078.clone(); rt::hd(&__t44)? }).as_sym() == Some(interp.intern_static("shen.x.features.cond-expand")));
                                                                        if !rt::is_truthy(
                                                                            interp, &__t74,
                                                                        )? {
                                                                            Value::bool(false)
                                                                        } else {
                                                                            let __t75 = {
                                                                                let __t72 = {
                                                                                    let __t46 = {
                                                                                        let __t45 = v_V7078.clone();
                                                                                        rt::tl(
                                                                                            &__t45,
                                                                                        )?
                                                                                    };
                                                                                    rt::is_cons(
                                                                                        &__t46,
                                                                                    )
                                                                                };
                                                                                if !rt::is_truthy(
                                                                                    interp, &__t72,
                                                                                )? {
                                                                                    Value::bool(
                                                                                        false,
                                                                                    )
                                                                                } else {
                                                                                    let __t73 = {
                                                                                        let __t70 = {
                                                                                            let __t49 = {
                                                                                                let __t48 = { let __t47 = v_V7078.clone(); rt::tl(&__t47)? };
                                                                                                rt::hd(&__t48)?
                                                                                            };
                                                                                            rt::is_cons(&__t49)
                                                                                        };
                                                                                        if !rt::is_truthy(interp, &__t70)? { Value::bool(false) } else { let __t71 = { let __t68 = Value::bool(({ let __t52 = { let __t51 = { let __t50 = v_V7078.clone(); rt::tl(&__t50)? }; rt::hd(&__t51)? }; rt::hd(&__t52)? }).as_sym() == Some(interp.intern_static("not"))); if !rt::is_truthy(interp, &__t68)? { Value::bool(false) } else { let __t69 = { let __t66 = { let __t56 = { let __t55 = { let __t54 = { let __t53 = v_V7078.clone(); rt::tl(&__t53)? }; rt::hd(&__t54)? }; rt::tl(&__t55)? }; rt::is_cons(&__t56) }; if !rt::is_truthy(interp, &__t66)? { Value::bool(false) } else { let __t67 = { let __t64 = Value::bool(({ let __t60 = { let __t59 = { let __t58 = { let __t57 = v_V7078.clone(); rt::tl(&__t57)? }; rt::hd(&__t58)? }; rt::tl(&__t59)? }; rt::tl(&__t60)? }).is_nil()); if !rt::is_truthy(interp, &__t64)? { Value::bool(false) } else { let __t65 = { let __t63 = { let __t62 = { let __t61 = v_V7078.clone(); rt::tl(&__t61)? }; rt::tl(&__t62)? }; rt::is_cons(&__t63) }; Value::bool(rt::is_truthy(interp, &__t65)?) } }; Value::bool(rt::is_truthy(interp, &__t67)?) } }; Value::bool(rt::is_truthy(interp, &__t69)?) } }; Value::bool(rt::is_truthy(interp, &__t71)?) }
                                                                                    };
                                                                                    Value::bool(rt::is_truthy(interp, &__t73)?)
                                                                                }
                                                                            };
                                                                            Value::bool(
                                                                                rt::is_truthy(
                                                                                    interp, &__t75,
                                                                                )?,
                                                                            )
                                                                        }
                                                                    };
                                                                    Value::bool(rt::is_truthy(
                                                                        interp, &__t77,
                                                                    )?)
                                                                }
                                                            };
                                                            if match rt::is_truthy(interp, &__t100)
                                                            {
                                                                Ok(b) => b,
                                                                Err(e) => break Err(e),
                                                            } {
                                                                break Ok({
                                                                    let __t78 = Value::sym(interp.intern_static("shen.x.features.cond-expand"));
                                                                    let __t99 = {
                                                                        let __t83 = {
                                                                            let __t82 = {
                                                                                let __t81 = {
                                                                                    let __t80 = {
                                                                                        let __t79 = v_V7078.clone();
                                                                                        rt::tl(
                                                                                            &__t79,
                                                                                        )?
                                                                                    };
                                                                                    rt::hd(&__t80)?
                                                                                };
                                                                                rt::tl(&__t81)?
                                                                            };
                                                                            rt::hd(&__t82)?
                                                                        };
                                                                        let __t98 = {
                                                                            let __t89 = {
                                                                                let __t84 = Value::sym(interp.intern_static("shen.x.features.cond-expand"));
                                                                                let __t88 = {
                                                                                    let __t87 = {
                                                                                        let __t86 = {
                                                                                            let __t85 = v_V7078.clone();
                                                                                            rt::tl(&__t85)?
                                                                                        };
                                                                                        rt::tl(
                                                                                            &__t86,
                                                                                        )?
                                                                                    };
                                                                                    rt::tl(&__t87)?
                                                                                };
                                                                                rt::cons(
                                                                                    &__t84, &__t88,
                                                                                )
                                                                            };
                                                                            let __t97 = {
                                                                                let __t90 =
                                                                                    Value::bool(
                                                                                        true,
                                                                                    );
                                                                                let __t96 = {
                                                                                    let __t94 = {
                                                                                        let __t93 = {
                                                                                            let __t92 = {
                                                                                                let __t91 = v_V7078.clone();
                                                                                                rt::tl(&__t91)?
                                                                                            };
                                                                                            rt::tl(&__t92)?
                                                                                        };
                                                                                        rt::hd(
                                                                                            &__t93,
                                                                                        )?
                                                                                    };
                                                                                    let __t95 =
                                                                                        Value::nil(
                                                                                        );
                                                                                    rt::cons(
                                                                                        &__t94,
                                                                                        &__t95,
                                                                                    )
                                                                                };
                                                                                rt::cons(
                                                                                    &__t90, &__t96,
                                                                                )
                                                                            };
                                                                            rt::cons(&__t89, &__t97)
                                                                        };
                                                                        rt::cons(&__t83, &__t98)
                                                                    };
                                                                    rt::cons(&__t78, &__t99)
                                                                });
                                                            } else {
                                                                {
                                                                    let __t42 = {
                                                                        let __t37 = {
                                                                            let __t20 =
                                                                                v_V7078.clone();
                                                                            rt::is_cons(&__t20)
                                                                        };
                                                                        if !rt::is_truthy(
                                                                            interp, &__t37,
                                                                        )? {
                                                                            Value::bool(false)
                                                                        } else {
                                                                            let __t38 = {
                                                                                let __t35 = Value::bool(({ let __t21 = v_V7078.clone(); rt::hd(&__t21)? }).as_sym() == Some(interp.intern_static("shen.x.features.cond-expand")));
                                                                                if !rt::is_truthy(
                                                                                    interp, &__t35,
                                                                                )? {
                                                                                    Value::bool(
                                                                                        false,
                                                                                    )
                                                                                } else {
                                                                                    let __t36 = {
                                                                                        let __t33 = {
                                                                                            let __t23 = {
                                                                                                let __t22 = v_V7078.clone();
                                                                                                rt::tl(&__t22)?
                                                                                            };
                                                                                            rt::is_cons(&__t23)
                                                                                        };
                                                                                        if !rt::is_truthy(interp, &__t33)? { Value::bool(false) } else { let __t34 = { let __t31 = { let __t26 = { let __t25 = { let __t24 = v_V7078.clone(); rt::tl(&__t24)? }; rt::tl(&__t25)? }; rt::is_cons(&__t26) }; if !rt::is_truthy(interp, &__t31)? { Value::bool(false) } else { let __t32 = { let __t29 = { let __t28 = { let __t27 = v_V7078.clone(); rt::tl(&__t27)? }; rt::hd(&__t28)? }; let __t30 = rt::global_value(interp, "shen.x.features.*features*")?; rt::apply_direct(interp, "element?", &[__t29, __t30])? }; Value::bool(rt::is_truthy(interp, &__t32)?) } }; Value::bool(rt::is_truthy(interp, &__t34)?) }
                                                                                    };
                                                                                    Value::bool(rt::is_truthy(interp, &__t36)?)
                                                                                }
                                                                            };
                                                                            Value::bool(
                                                                                rt::is_truthy(
                                                                                    interp, &__t38,
                                                                                )?,
                                                                            )
                                                                        }
                                                                    };
                                                                    if match rt::is_truthy(
                                                                        interp, &__t42,
                                                                    ) {
                                                                        Ok(b) => b,
                                                                        Err(e) => break Err(e),
                                                                    } {
                                                                        break Ok({
                                                                            let __t41 = {
                                                                                let __t40 = {
                                                                                    let __t39 =
                                                                                        v_V7078
                                                                                            .clone(
                                                                                            );
                                                                                    rt::tl(&__t39)?
                                                                                };
                                                                                rt::tl(&__t40)?
                                                                            };
                                                                            rt::hd(&__t41)?
                                                                        });
                                                                    } else {
                                                                        {
                                                                            let __t19 = {
                                                                                let __t12 = {
                                                                                    let __t1 =
                                                                                        v_V7078
                                                                                            .clone(
                                                                                            );
                                                                                    rt::is_cons(
                                                                                        &__t1,
                                                                                    )
                                                                                };
                                                                                if !rt::is_truthy(
                                                                                    interp, &__t12,
                                                                                )? {
                                                                                    Value::bool(
                                                                                        false,
                                                                                    )
                                                                                } else {
                                                                                    let __t13 = {
                                                                                        let __t10 = Value::bool(({ let __t2 = v_V7078.clone(); rt::hd(&__t2)? }).as_sym() == Some(interp.intern_static("shen.x.features.cond-expand")));
                                                                                        if !rt::is_truthy(interp, &__t10)? { Value::bool(false) } else { let __t11 = { let __t8 = { let __t4 = { let __t3 = v_V7078.clone(); rt::tl(&__t3)? }; rt::is_cons(&__t4) }; if !rt::is_truthy(interp, &__t8)? { Value::bool(false) } else { let __t9 = { let __t7 = { let __t6 = { let __t5 = v_V7078.clone(); rt::tl(&__t5)? }; rt::tl(&__t6)? }; rt::is_cons(&__t7) }; Value::bool(rt::is_truthy(interp, &__t9)?) } }; Value::bool(rt::is_truthy(interp, &__t11)?) }
                                                                                    };
                                                                                    Value::bool(rt::is_truthy(interp, &__t13)?)
                                                                                }
                                                                            };
                                                                            if match rt::is_truthy(
                                                                                interp, &__t19,
                                                                            ) {
                                                                                Ok(b) => b,
                                                                                Err(e) => {
                                                                                    break Err(e)
                                                                                }
                                                                            } {
                                                                                break Ok({
                                                                                    let __t14 = Value::sym(interp.intern_static("shen.x.features.cond-expand"));
                                                                                    let __t18 = {
                                                                                        let __t17 = {
                                                                                            let __t16 = {
                                                                                                let __t15 = v_V7078.clone();
                                                                                                rt::tl(&__t15)?
                                                                                            };
                                                                                            rt::tl(&__t16)?
                                                                                        };
                                                                                        rt::tl(
                                                                                            &__t17,
                                                                                        )?
                                                                                    };
                                                                                    rt::cons(
                                                                                        &__t14,
                                                                                        &__t18,
                                                                                    )
                                                                                });
                                                                            } else {
                                                                                {
                                                                                    let __t0 =
                                                                                        Value::bool(
                                                                                            true,
                                                                                        );
                                                                                    if match rt::is_truthy(interp, &__t0) { Ok(b) => b, Err(e) => break Err(e), } { break Ok(v_V7078.clone()); } else { break Err(ShenError::new("cond: no clause matched")); }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_features_x2e_cond_x2d_expand_x2d_macro(interp: &mut Interp) {
    interp.register_native(
        "shen.x.features.cond-expand-macro",
        1,
        aot_shen_x2e_x_x2e_features_x2e_cond_x2d_expand_x2d_macro,
    );
    interp.register_aot_direct(
        "shen.x.features.cond-expand-macro",
        aot_shen_x2e_x_x2e_features_x2e_cond_x2d_expand_x2d_macro,
    );
}

/// AOT-compiled from KL `(defun shen.x.features.current ...)`
pub fn aot_shen_x2e_x_x2e_features_x2e_current(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 0 {
        return Err(ShenError::new(format!(
            "shen.x.features.current: expected 0 args, got {}",
            args.len()
        )));
    }
    #[allow(clippy::never_loop)]
    loop {
        break Ok(rt::global_value(interp, "shen.x.features.*features*")?);
    }
}

fn install_shen_x2e_x_x2e_features_x2e_current(interp: &mut Interp) {
    interp.register_native(
        "shen.x.features.current",
        0,
        aot_shen_x2e_x_x2e_features_x2e_current,
    );
    interp.register_aot_direct(
        "shen.x.features.current",
        aot_shen_x2e_x_x2e_features_x2e_current,
    );
}

/// AOT-compiled from KL `(defun shen.x.features.initialise ...)`
pub fn aot_shen_x2e_x_x2e_features_x2e_initialise(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 1 {
        return Err(ShenError::new(format!(
            "shen.x.features.initialise: expected 1 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7079 = args[0].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let v_W7080 = {
                let __x = Value::sym(interp.intern_static("shen.x.features.*features*"));
                let __h = {
                    rt::make_aot_closure(
                        "<freeze>",
                        0,
                        move |interp, _args| {
                            Ok({
                                let _ = {
                                    let __v = Value::nil();
                                    rt::set_global(interp, "shen.x.features.*features*", __v)
                                };
                                {
                                    let _ = {
                                        let __t321 = {
                                            let __t318 = Value::sym(interp.intern_static(
                                                "shen.x.features.cond-expand-macro",
                                            ));
                                            let __t320 = {
                                                rt::make_aot_closure(
                                                    "<lambda>",
                                                    1,
                                                    move |interp, args| {
                                                        let v_Z7082 = args[0].clone();
                                                        Ok({
                                                            let __t319 = v_Z7082.clone();
                                                            aot_shen_x2e_x_x2e_features_x2e_cond_x2d_expand_x2d_macro(interp, &[__t319])?
                                                        })
                                                    },
                                                    Vec::new(),
                                                    interp,
                                                )
                                            };
                                            rt::cons(&__t318, &__t320)
                                        };
                                        rt::apply_direct(
                                            interp,
                                            "shen.set-lambda-form-entry",
                                            &[__t321],
                                        )?
                                    };
                                    {
                                        let __t322 = Value::sym(
                                            interp
                                                .intern_static("shen.x.features.cond-expand-macro"),
                                        );
                                        let __t324 = {
                                            rt::make_aot_closure(
                                                "<lambda>",
                                                1,
                                                move |interp, args| {
                                                    let v_Z7083 = args[0].clone();
                                                    Ok({
                                                        let __t323 = v_Z7083.clone();
                                                        aot_shen_x2e_x_x2e_features_x2e_cond_x2d_expand_x2d_macro(interp, &[__t323])?
                                                    })
                                                },
                                                Vec::new(),
                                                interp,
                                            )
                                        };
                                        rt::apply_direct(
                                            interp,
                                            "shen.record-macro",
                                            &[__t322, __t324],
                                        )?
                                    }
                                }
                            })
                        },
                        Vec::new(),
                        interp,
                    )
                };
                rt::apply_direct(interp, "value/or", &[__x, __h])?
            };
            {
                let v_W7084 = { aot_shen_x2e_x_x2e_features_x2e_current(interp, &[])? };
                {
                    let v_W7085 = {
                        let __v = v_V7079.clone();
                        rt::set_global(interp, "shen.x.features.*features*", __v)
                    };
                    break Ok(v_W7084.clone());
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_features_x2e_initialise(interp: &mut Interp) {
    interp.register_native(
        "shen.x.features.initialise",
        1,
        aot_shen_x2e_x_x2e_features_x2e_initialise,
    );
    interp.register_aot_direct(
        "shen.x.features.initialise",
        aot_shen_x2e_x_x2e_features_x2e_initialise,
    );
}

/// AOT-compiled from KL `(defun shen.x.features.add ...)`
pub fn aot_shen_x2e_x_x2e_features_x2e_add(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 1 {
        return Err(ShenError::new(format!(
            "shen.x.features.add: expected 1 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7086 = args[0].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let v_W7087 = { aot_shen_x2e_x_x2e_features_x2e_current(interp, &[])? };
            {
                let v_W7088 = {
                    let __v = {
                        let __t325 = v_V7086.clone();
                        let __t326 = v_W7087.clone();
                        rt::apply_direct(interp, "adjoin", &[__t325, __t326])?
                    };
                    rt::set_global(interp, "shen.x.features.*features*", __v)
                };
                break Ok(v_W7087.clone());
            }
        }
    }
}

fn install_shen_x2e_x_x2e_features_x2e_add(interp: &mut Interp) {
    interp.register_native(
        "shen.x.features.add",
        1,
        aot_shen_x2e_x_x2e_features_x2e_add,
    );
    interp.register_aot_direct("shen.x.features.add", aot_shen_x2e_x_x2e_features_x2e_add);
}

/// Register every AOT-compiled function on `interp`. Call after kernel
/// boot so these names override the tree-walked defuns.
pub fn install(interp: &mut Interp) {
    install_shen_x2e_x_x2e_features_x2e_cond_x2d_expand_x2d_macro(interp);
    install_shen_x2e_x_x2e_features_x2e_current(interp);
    install_shen_x2e_x_x2e_features_x2e_initialise(interp);
    install_shen_x2e_x_x2e_features_x2e_add(interp);
}
