//! Auto-generated by `klcompile` from kernel/klambda/extension-programmable-pattern-matching.kl.
//!
//! DO NOT EDIT. Re-run klcompile to regenerate.

#![allow(
    unused_variables,
    unused_braces,
    unused_imports,
    clippy::let_and_return,
    clippy::needless_question_mark,
    clippy::redundant_clone,
    clippy::needless_late_init,
    clippy::len_zero,
    clippy::needless_borrow,
    clippy::approx_constant,
    clippy::redundant_closure_call,
    non_snake_case
)]

use crate::aot::runtime as rt;
use crate::error::{ShenError, ShenResult};
use crate::interp::eval::Interp;
use crate::value::Value;
use std::rc::Rc;

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.apply-pattern-handlers ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_apply_x2d_pattern_x2d_handlers(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 5 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.apply-pattern-handlers: expected 5 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7168 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V7169 = args[1].clone();
    #[allow(unused_mut)]
    let mut v_V7170 = args[2].clone();
    #[allow(unused_mut)]
    let mut v_V7171 = args[3].clone();
    #[allow(unused_mut)]
    let mut v_V7172 = args[4].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let __t27 = {
                let __t25 = Value::nil();
                let __t26 = v_V7168.clone();
                rt::eq(&__t25, &__t26)
            };
            if match rt::is_truthy(interp, &__t27) {
                Ok(b) => b,
                Err(e) => break Err(e),
            } {
                break Ok({ rt::fail(interp) });
            } else {
                {
                    let __t24 = Value::bool(true);
                    if match rt::is_truthy(interp, &__t24) {
                        Ok(b) => b,
                        Err(e) => break Err(e),
                    } {
                        {
                            let v_Freeze7174 = {
                                let v_V7168 = v_V7168.clone();
                                let v_V7169 = v_V7169.clone();
                                let v_V7170 = v_V7170.clone();
                                let v_V7171 = v_V7171.clone();
                                let v_V7172 = v_V7172.clone();
                                rt::make_aot_closure(
                                    "<freeze>",
                                    0,
                                    move |interp, _args| {
                                        Ok({
                                            let __t9 = {
                                                let __t2 = v_V7168.clone();
                                                rt::is_cons(&__t2)
                                            };
                                            if rt::is_truthy(interp, &__t9)? {
                                                {
                                                    let __t4 = {
                                                        let __t3 = v_V7168.clone();
                                                        rt::tl(&__t3)?
                                                    };
                                                    let __t5 = v_V7169.clone();
                                                    let __t6 = v_V7170.clone();
                                                    let __t7 = v_V7171.clone();
                                                    let __t8 = v_V7172.clone();
                                                    rt::apply_direct(interp, "shen.x.programmable-pattern-matching.apply-pattern-handlers", &[__t4, __t5, __t6, __t7, __t8])?
                                                }
                                            } else {
                                                {
                                                    let __t1 = Value::bool(true);
                                                    if rt::is_truthy(interp, &__t1)? {
                                                        {
                                                            let __t0 = Value::sym(interp.intern("shen.x.programmable-pattern-matching.apply-pattern-handlers"));
                                                            rt::apply_direct(
                                                                interp,
                                                                "shen.f-error",
                                                                &[__t0],
                                                            )?
                                                        }
                                                    } else {
                                                        return Err(ShenError::new(
                                                            "cond: no clause matched",
                                                        ));
                                                    }
                                                }
                                            }
                                        })
                                    },
                                    vec![v_V7168, v_V7169, v_V7170, v_V7171, v_V7172],
                                    interp,
                                )
                            };
                            {
                                let __t11 = {
                                    let __t10 = v_V7168.clone();
                                    rt::is_cons(&__t10)
                                };
                                if match rt::is_truthy(interp, &__t11) {
                                    Ok(b) => b,
                                    Err(e) => break Err(e),
                                } {
                                    {
                                        let v_Result7173 = {
                                            let __t19 = {
                                                let __t17 = {
                                                    let __t15 = {
                                                        let __t13 = {
                                                            let __t12 = v_V7168.clone();
                                                            rt::hd(&__t12)?
                                                        };
                                                        let __t14 = v_V7169.clone();
                                                        rt::apply_value(interp, __t13, &[__t14])?
                                                    };
                                                    let __t16 = v_V7170.clone();
                                                    rt::apply_value(interp, __t15, &[__t16])?
                                                };
                                                let __t18 = v_V7171.clone();
                                                rt::apply_value(interp, __t17, &[__t18])?
                                            };
                                            let __t20 = v_V7172.clone();
                                            rt::apply_value(interp, __t19, &[__t20])?
                                        };
                                        {
                                            let __t23 = {
                                                let __t21 = v_Result7173.clone();
                                                let __t22 = { rt::fail(interp) };
                                                rt::eq(&__t21, &__t22)
                                            };
                                            if match rt::is_truthy(interp, &__t23) {
                                                Ok(b) => b,
                                                Err(e) => break Err(e),
                                            } {
                                                break Ok(rt::apply_value(
                                                    interp,
                                                    v_Freeze7174.clone(),
                                                    &[],
                                                )?);
                                            } else {
                                                break Ok(v_Result7173.clone());
                                            }
                                        }
                                    }
                                } else {
                                    break Ok(rt::apply_value(interp, v_Freeze7174.clone(), &[])?);
                                }
                            }
                        }
                    } else {
                        break Err(ShenError::new("cond: no clause matched"));
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_apply_x2d_pattern_x2d_handlers(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.apply-pattern-handlers",
        5,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_apply_x2d_pattern_x2d_handlers,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.apply-pattern-handlers",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_apply_x2d_pattern_x2d_handlers,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.make-stack ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_make_x2d_stack(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 0 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.make-stack: expected 0 args, got {}",
            args.len()
        )));
    }
    #[allow(clippy::never_loop)]
    loop {
        break Ok({
            let __t29 = {
                let __t28 = Value::int(1i64);
                rt::apply_direct(interp, "absvector", &[__t28])?
            };
            let __t30 = Value::int(0i64);
            let __t31 = Value::nil();
            rt::address_set(&__t29, &__t30, &__t31)?
        });
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_make_x2d_stack(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.make-stack",
        0,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_make_x2d_stack,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.make-stack",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_make_x2d_stack,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.push ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_push(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 2 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.push: expected 2 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7175 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V7176 = args[1].clone();
    #[allow(clippy::never_loop)]
    loop {
        break Ok({
            let __t32 = v_V7175.clone();
            let __t33 = Value::int(0i64);
            let __t38 = {
                let __t34 = v_V7176.clone();
                let __t37 = {
                    let __t35 = v_V7175.clone();
                    let __t36 = Value::int(0i64);
                    rt::address_ref(&__t35, &__t36)?
                };
                rt::cons(&__t34, &__t37)
            };
            rt::address_set(&__t32, &__t33, &__t38)?
        });
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_push(interp: &mut Interp) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.push",
        2,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_push,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.push",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_push,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.pop-all ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_pop_x2d_all(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 1 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.pop-all: expected 1 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7177 = args[0].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let v_W7178 = {
                let __t39 = v_V7177.clone();
                let __t40 = Value::int(0i64);
                rt::address_ref(&__t39, &__t40)?
            };
            {
                let v_W7179 = {
                    let __t41 = v_V7177.clone();
                    let __t42 = Value::int(0i64);
                    let __t43 = Value::nil();
                    rt::address_set(&__t41, &__t42, &__t43)?
                };
                break Ok(v_W7178.clone());
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_pop_x2d_all(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.pop-all",
        1,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_pop_x2d_all,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.pop-all",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_pop_x2d_all,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.surface-pattern ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 1 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.surface-pattern: expected 1 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7180 = args[0].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let __t76 = {
                let __t65 = {
                    let __t45 = v_V7180.clone();
                    rt::is_cons(&__t45)
                };
                if !rt::is_truthy(interp, &__t65)? {
                    Value::bool(false)
                } else {
                    let __t66 = {
                        let __t63 = {
                            let __t46 = Value::sym(interp.intern("cons"));
                            let __t48 = {
                                let __t47 = v_V7180.clone();
                                rt::hd(&__t47)?
                            };
                            rt::eq(&__t46, &__t48)
                        };
                        if !rt::is_truthy(interp, &__t63)? {
                            Value::bool(false)
                        } else {
                            let __t64 = {
                                let __t61 = {
                                    let __t50 = {
                                        let __t49 = v_V7180.clone();
                                        rt::tl(&__t49)?
                                    };
                                    rt::is_cons(&__t50)
                                };
                                if !rt::is_truthy(interp, &__t61)? {
                                    Value::bool(false)
                                } else {
                                    let __t62 = {
                                        let __t59 = {
                                            let __t53 = {
                                                let __t52 = {
                                                    let __t51 = v_V7180.clone();
                                                    rt::tl(&__t51)?
                                                };
                                                rt::tl(&__t52)?
                                            };
                                            rt::is_cons(&__t53)
                                        };
                                        if !rt::is_truthy(interp, &__t59)? {
                                            Value::bool(false)
                                        } else {
                                            let __t60 = {
                                                let __t54 = Value::nil();
                                                let __t58 = {
                                                    let __t57 = {
                                                        let __t56 = {
                                                            let __t55 = v_V7180.clone();
                                                            rt::tl(&__t55)?
                                                        };
                                                        rt::tl(&__t56)?
                                                    };
                                                    rt::tl(&__t57)?
                                                };
                                                rt::eq(&__t54, &__t58)
                                            };
                                            Value::bool(rt::is_truthy(interp, &__t60)?)
                                        }
                                    };
                                    Value::bool(rt::is_truthy(interp, &__t62)?)
                                }
                            };
                            Value::bool(rt::is_truthy(interp, &__t64)?)
                        }
                    };
                    Value::bool(rt::is_truthy(interp, &__t66)?)
                }
            };
            if match rt::is_truthy(interp, &__t76) {
                Ok(b) => b,
                Err(e) => break Err(e),
            } {
                break Ok({
                    let __t70 = {
                        let __t69 = {
                            let __t68 = {
                                let __t67 = v_V7180.clone();
                                rt::tl(&__t67)?
                            };
                            rt::hd(&__t68)?
                        };
                        rt::apply_direct(
                            interp,
                            "shen.x.programmable-pattern-matching.surface-pattern",
                            &[__t69],
                        )?
                    };
                    let __t75 = {
                        let __t74 = {
                            let __t73 = {
                                let __t72 = {
                                    let __t71 = v_V7180.clone();
                                    rt::tl(&__t71)?
                                };
                                rt::tl(&__t72)?
                            };
                            rt::hd(&__t73)?
                        };
                        rt::apply_direct(
                            interp,
                            "shen.x.programmable-pattern-matching.surface-pattern-tail",
                            &[__t74],
                        )?
                    };
                    rt::cons(&__t70, &__t75)
                });
            } else {
                {
                    let __t44 = Value::bool(true);
                    if match rt::is_truthy(interp, &__t44) {
                        Ok(b) => b,
                        Err(e) => break Err(e),
                    } {
                        break Ok(v_V7180.clone());
                    } else {
                        break Err(ShenError::new("cond: no clause matched"));
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.surface-pattern",
        1,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.surface-pattern",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.surface-pattern-tail ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern_x2d_tail(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 1 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.surface-pattern-tail: expected 1 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7181 = args[0].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let __t112 = {
                let __t110 = Value::nil();
                let __t111 = v_V7181.clone();
                rt::eq(&__t110, &__t111)
            };
            if match rt::is_truthy(interp, &__t112) {
                Ok(b) => b,
                Err(e) => break Err(e),
            } {
                break Ok(Value::nil());
            } else {
                {
                    let __t109 = {
                        let __t98 = {
                            let __t78 = v_V7181.clone();
                            rt::is_cons(&__t78)
                        };
                        if !rt::is_truthy(interp, &__t98)? {
                            Value::bool(false)
                        } else {
                            let __t99 = {
                                let __t96 = {
                                    let __t79 = Value::sym(interp.intern("cons"));
                                    let __t81 = {
                                        let __t80 = v_V7181.clone();
                                        rt::hd(&__t80)?
                                    };
                                    rt::eq(&__t79, &__t81)
                                };
                                if !rt::is_truthy(interp, &__t96)? {
                                    Value::bool(false)
                                } else {
                                    let __t97 = {
                                        let __t94 = {
                                            let __t83 = {
                                                let __t82 = v_V7181.clone();
                                                rt::tl(&__t82)?
                                            };
                                            rt::is_cons(&__t83)
                                        };
                                        if !rt::is_truthy(interp, &__t94)? {
                                            Value::bool(false)
                                        } else {
                                            let __t95 = {
                                                let __t92 = {
                                                    let __t86 = {
                                                        let __t85 = {
                                                            let __t84 = v_V7181.clone();
                                                            rt::tl(&__t84)?
                                                        };
                                                        rt::tl(&__t85)?
                                                    };
                                                    rt::is_cons(&__t86)
                                                };
                                                if !rt::is_truthy(interp, &__t92)? {
                                                    Value::bool(false)
                                                } else {
                                                    let __t93 = {
                                                        let __t87 = Value::nil();
                                                        let __t91 = {
                                                            let __t90 = {
                                                                let __t89 = {
                                                                    let __t88 = v_V7181.clone();
                                                                    rt::tl(&__t88)?
                                                                };
                                                                rt::tl(&__t89)?
                                                            };
                                                            rt::tl(&__t90)?
                                                        };
                                                        rt::eq(&__t87, &__t91)
                                                    };
                                                    Value::bool(rt::is_truthy(interp, &__t93)?)
                                                }
                                            };
                                            Value::bool(rt::is_truthy(interp, &__t95)?)
                                        }
                                    };
                                    Value::bool(rt::is_truthy(interp, &__t97)?)
                                }
                            };
                            Value::bool(rt::is_truthy(interp, &__t99)?)
                        }
                    };
                    if match rt::is_truthy(interp, &__t109) {
                        Ok(b) => b,
                        Err(e) => break Err(e),
                    } {
                        break Ok({
                            let __t103 = {
                                let __t102 = {
                                    let __t101 = {
                                        let __t100 = v_V7181.clone();
                                        rt::tl(&__t100)?
                                    };
                                    rt::hd(&__t101)?
                                };
                                rt::apply_direct(
                                    interp,
                                    "shen.x.programmable-pattern-matching.surface-pattern",
                                    &[__t102],
                                )?
                            };
                            let __t108 = {
                                let __t107 = {
                                    let __t106 = {
                                        let __t105 = {
                                            let __t104 = v_V7181.clone();
                                            rt::tl(&__t104)?
                                        };
                                        rt::tl(&__t105)?
                                    };
                                    rt::hd(&__t106)?
                                };
                                rt::apply_direct(
                                    interp,
                                    "shen.x.programmable-pattern-matching.surface-pattern-tail",
                                    &[__t107],
                                )?
                            };
                            rt::cons(&__t103, &__t108)
                        });
                    } else {
                        {
                            let __t77 = Value::bool(true);
                            if match rt::is_truthy(interp, &__t77) {
                                Ok(b) => b,
                                Err(e) => break Err(e),
                            } {
                                break Ok(v_V7181.clone());
                            } else {
                                break Err(ShenError::new("cond: no clause matched"));
                            }
                        }
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern_x2d_tail(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.surface-pattern-tail",
        1,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern_x2d_tail,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.surface-pattern-tail",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern_x2d_tail,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.compile-pattern ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 3 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.compile-pattern: expected 3 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7182 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V7183 = args[1].clone();
    #[allow(unused_mut)]
    let mut v_V7184 = args[2].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let v_W7185 = {
                let __t113 = v_V7182.clone();
                rt::apply_direct(
                    interp,
                    "shen.x.programmable-pattern-matching.surface-pattern",
                    &[__t113],
                )?
            };
            {
                let v_W7186 = {
                    rt::apply_direct(
                        interp,
                        "shen.x.programmable-pattern-matching.make-stack",
                        &[],
                    )?
                };
                {
                    let v_W7187 = Value::sym(interp.intern("Self$$7907$$"));
                    {
                        let v_W7188 = {
                            rt::make_aot_closure(
                                "<lambda>",
                                1,
                                move |interp, args| {
                                    let v_Z7189 = args[0].clone();
                                    Ok(Value::sym(
                                        interp
                                            .intern("shen.x.programmable-pattern-matching.ignored"),
                                    ))
                                },
                                Vec::new(),
                                interp,
                            )
                        };
                        {
                            let v_W7190 = {
                                let v_W7186 = v_W7186.clone();
                                rt::make_aot_closure(
                                    "<lambda>",
                                    1,
                                    move |interp, args| {
                                        let v_Z7191 = args[0].clone();
                                        Ok({
                                            let v_W7186 = v_W7186.clone();
                                            let v_Z7191 = v_Z7191.clone();
                                            rt::make_aot_closure(
                                                "<lambda>",
                                                1,
                                                move |interp, args| {
                                                    let v_Z7192 = args[0].clone();
                                                    Ok({
                                                        let __t114 = v_W7186.clone();
                                                        let __t115 = v_Z7191.clone();
                                                        rt::apply_direct(interp, "shen.x.programmable-pattern-matching.push", &[__t114, __t115])?
                                                    })
                                                },
                                                vec![v_W7186, v_Z7191],
                                                interp,
                                            )
                                        })
                                    },
                                    vec![v_W7186],
                                    interp,
                                )
                            };
                            {
                                let v_W7193 = {
                                    let __t116 = v_V7183.clone();
                                    let __t117 = v_W7187.clone();
                                    let __t118 = v_W7188.clone();
                                    let __t119 = v_W7190.clone();
                                    let __t120 = v_W7185.clone();
                                    rt::apply_direct(interp, "shen.x.programmable-pattern-matching.apply-pattern-handlers", &[__t116, __t117, __t118, __t119, __t120])?
                                };
                                {
                                    let __t123 = {
                                        let __t121 = v_W7193.clone();
                                        let __t122 = { rt::fail(interp) };
                                        rt::eq(&__t121, &__t122)
                                    };
                                    if match rt::is_truthy(interp, &__t123) {
                                        Ok(b) => b,
                                        Err(e) => break Err(e),
                                    } {
                                        break Ok(rt::apply_value(interp, v_V7184.clone(), &[])?);
                                    } else {
                                        break Ok({
                                            let __t124 = Value::sym(interp.intern("@p"));
                                            let __t133 = {
                                                let __t125 = Value::sym(
                                                    interp.intern("shen.custom-pattern"),
                                                );
                                                let __t132 = {
                                                    let __t130 = {
                                                        let __t126 = v_W7185.clone();
                                                        let __t129 = {
                                                            let __t128 = {
                                                                let __t127 = v_W7186.clone();
                                                                rt::apply_direct(interp, "shen.x.programmable-pattern-matching.pop-all", &[__t127])?
                                                            };
                                                            rt::apply_direct(
                                                                interp,
                                                                "reverse",
                                                                &[__t128],
                                                            )?
                                                        };
                                                        rt::apply_direct(interp, "shen.x.programmable-pattern-matching.compile-pattern-h", &[__t126, __t129])?
                                                    };
                                                    let __t131 = Value::nil();
                                                    rt::cons(&__t130, &__t131)
                                                };
                                                rt::cons(&__t125, &__t132)
                                            };
                                            rt::cons(&__t124, &__t133)
                                        });
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.compile-pattern",
        3,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.compile-pattern",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.compile-pattern-h ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern_x2d_h(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 2 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.compile-pattern-h: expected 2 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7194 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V7195 = args[1].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let __t147 = {
                let __t136 = v_V7194.clone();
                rt::is_cons(&__t136)
            };
            if match rt::is_truthy(interp, &__t147) {
                Ok(b) => b,
                Err(e) => break Err(e),
            } {
                {
                    let v_W7196 = {
                        let __t141 = {
                            let v_V7195 = v_V7195.clone();
                            rt::make_aot_closure(
                                "<lambda>",
                                1,
                                move |interp, args| {
                                    let v_Z7197 = args[0].clone();
                                    Ok({
                                        let __t140 = {
                                            let __t137 = v_Z7197.clone();
                                            let __t138 = v_V7195.clone();
                                            rt::apply_direct(interp, "element?", &[__t137, __t138])?
                                        };
                                        if rt::is_truthy(interp, &__t140)? {
                                            {
                                                let __t139 = v_Z7197.clone();
                                                rt::apply_direct(
                                                    interp,
                                                    "shen.compile-pattern-fragment",
                                                    &[__t139],
                                                )?
                                            }
                                        } else {
                                            v_Z7197.clone()
                                        }
                                    })
                                },
                                vec![v_V7195],
                                interp,
                            )
                        };
                        let __t143 = {
                            let __t142 = v_V7194.clone();
                            rt::tl(&__t142)?
                        };
                        rt::apply_direct(interp, "map", &[__t141, __t143])?
                    };
                    break Ok({
                        let __t145 = {
                            let __t144 = v_V7194.clone();
                            rt::hd(&__t144)?
                        };
                        let __t146 = v_W7196.clone();
                        rt::cons(&__t145, &__t146)
                    });
                }
            } else {
                {
                    let __t135 = Value::bool(true);
                    if match rt::is_truthy(interp, &__t135) {
                        Ok(b) => b,
                        Err(e) => break Err(e),
                    } {
                        break Ok({
                            let __t134 =
                                Value::sym(interp.intern(
                                    "shen.x.programmable-pattern-matching.compile-pattern-h",
                                ));
                            rt::apply_direct(interp, "shen.f-error", &[__t134])?
                        });
                    } else {
                        break Err(ShenError::new("cond: no clause matched"));
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern_x2d_h(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.compile-pattern-h",
        2,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern_x2d_h,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.compile-pattern-h",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern_x2d_h,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.reduce ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_reduce(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 2 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.reduce: expected 2 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7198 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V7199 = args[1].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let __t174 = {
                let __t150 = v_V7198.clone();
                rt::apply_direct(interp, "tuple?", &[__t150])?
            };
            if match rt::is_truthy(interp, &__t174) {
                Ok(b) => b,
                Err(e) => break Err(e),
            } {
                {
                    let v_W7200 = {
                        let __t152 = {
                            let __t151 = v_V7198.clone();
                            rt::apply_direct(interp, "fst", &[__t151])?
                        };
                        rt::apply_direct(
                            interp,
                            "shen.x.programmable-pattern-matching.surface-pattern",
                            &[__t152],
                        )?
                    };
                    {
                        let v_W7201 = {
                            rt::apply_direct(
                                interp,
                                "shen.x.programmable-pattern-matching.make-stack",
                                &[],
                            )?
                        };
                        {
                            let v_W7202 = {
                                rt::apply_direct(
                                    interp,
                                    "shen.x.programmable-pattern-matching.make-stack",
                                    &[],
                                )?
                            };
                            {
                                let v_W7203 = {
                                    let v_W7201 = v_W7201.clone();
                                    rt::make_aot_closure(
                                        "<lambda>",
                                        1,
                                        move |interp, args| {
                                            let v_Z7204 = args[0].clone();
                                            Ok({
                                                let __t153 = v_W7201.clone();
                                                let __t154 = v_Z7204.clone();
                                                rt::apply_direct(
                                                    interp,
                                                    "shen.x.programmable-pattern-matching.push",
                                                    &[__t153, __t154],
                                                )?
                                            })
                                        },
                                        vec![v_W7201],
                                        interp,
                                    )
                                };
                                {
                                    let v_W7205 = {
                                        let v_W7202 = v_W7202.clone();
                                        rt::make_aot_closure(
                                            "<lambda>",
                                            1,
                                            move |interp, args| {
                                                let v_Z7206 = args[0].clone();
                                                Ok({
                                                    let v_W7202 = v_W7202.clone();
                                                    let v_Z7206 = v_Z7206.clone();
                                                    rt::make_aot_closure(
                                                        "<lambda>",
                                                        1,
                                                        move |interp, args| {
                                                            let v_Z7207 = args[0].clone();
                                                            Ok({
                                                                let __t155 = v_W7202.clone();
                                                                let __t158 = {
                                                                    let __t156 = v_Z7206.clone();
                                                                    let __t157 = v_Z7207.clone();
                                                                    rt::apply_direct(
                                                                        interp,
                                                                        "@p",
                                                                        &[__t156, __t157],
                                                                    )?
                                                                };
                                                                rt::apply_direct(interp, "shen.x.programmable-pattern-matching.push", &[__t155, __t158])?
                                                            })
                                                        },
                                                        vec![v_W7202, v_Z7206],
                                                        interp,
                                                    )
                                                })
                                            },
                                            vec![v_W7202],
                                            interp,
                                        )
                                    };
                                    {
                                        let v_W7208 = {
                                            let __t159 = v_V7199.clone();
                                            let __t161 = {
                                                let __t160 = v_V7198.clone();
                                                rt::apply_direct(interp, "snd", &[__t160])?
                                            };
                                            let __t162 = v_W7203.clone();
                                            let __t163 = v_W7205.clone();
                                            let __t164 = v_W7200.clone();
                                            rt::apply_direct(interp, "shen.x.programmable-pattern-matching.apply-pattern-handlers", &[__t159, __t161, __t162, __t163, __t164])?
                                        };
                                        {
                                            let __t167 = {
                                                let __t165 = v_W7208.clone();
                                                let __t166 = { rt::fail(interp) };
                                                rt::eq(&__t165, &__t166)
                                            };
                                            if match rt::is_truthy(interp, &__t167) {
                                                Ok(b) => b,
                                                Err(e) => break Err(e),
                                            } {
                                                break Ok({ rt::fail(interp) });
                                            } else {
                                                break Ok({
                                                    let __t170 = {
                                                        let __t169 = {
                                                            let __t168 = v_W7201.clone();
                                                            rt::apply_direct(interp, "shen.x.programmable-pattern-matching.pop-all", &[__t168])?
                                                        };
                                                        rt::apply_direct(
                                                            interp,
                                                            "reverse",
                                                            &[__t169],
                                                        )?
                                                    };
                                                    let __t173 = {
                                                        let __t172 = {
                                                            let __t171 = v_W7202.clone();
                                                            rt::apply_direct(interp, "shen.x.programmable-pattern-matching.pop-all", &[__t171])?
                                                        };
                                                        rt::apply_direct(
                                                            interp,
                                                            "reverse",
                                                            &[__t172],
                                                        )?
                                                    };
                                                    rt::apply_direct(
                                                        interp,
                                                        "@p",
                                                        &[__t170, __t173],
                                                    )?
                                                });
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            } else {
                {
                    let __t149 = Value::bool(true);
                    if match rt::is_truthy(interp, &__t149) {
                        Ok(b) => b,
                        Err(e) => break Err(e),
                    } {
                        break Ok({
                            let __t148 = Value::sym(
                                interp.intern("shen.x.programmable-pattern-matching.reduce"),
                            );
                            rt::apply_direct(interp, "shen.f-error", &[__t148])?
                        });
                    } else {
                        break Err(ShenError::new("cond: no clause matched"));
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_reduce(interp: &mut Interp) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.reduce",
        2,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_reduce,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.reduce",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_reduce,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.initialise ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_initialise(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 0 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.initialise: expected 0 args, got {}",
            args.len()
        )));
    }
    #[allow(clippy::never_loop)]
    loop {
        {
            let _ = {
                let __v = {
                    rt::make_aot_closure(
                        "<lambda>",
                        1,
                        move |interp, args| {
                            let v_Z7209 = args[0].clone();
                            Ok({
                                let v_Z7209 = v_Z7209.clone();
                                rt::make_aot_closure(
                                    "<lambda>",
                                    1,
                                    move |interp, args| {
                                        let v_Z7210 = args[0].clone();
                                        Ok({
                                            let __t175 = v_Z7209.clone();
                                            let __t176 = rt::global_value(interp, "shen.x.programmable-pattern-matching.*pattern-handlers*")?;
                                            let __t177 = v_Z7210.clone();
                                            rt::apply_direct(interp, "shen.x.programmable-pattern-matching.compile-pattern", &[__t175, __t176, __t177])?
                                        })
                                    },
                                    vec![v_Z7209],
                                    interp,
                                )
                            })
                        },
                        Vec::new(),
                        interp,
                    )
                };
                rt::set_global(interp, "shen.*custom-pattern-compiler*", __v)
            };
            {
                let _ = {
                    let __v = {
                        rt::make_aot_closure(
                            "<lambda>",
                            1,
                            move |interp, args| {
                                let v_Z7211 = args[0].clone();
                                Ok({
                                    let __t178 = v_Z7211.clone();
                                    let __t179 = rt::global_value(
                                        interp,
                                        "shen.x.programmable-pattern-matching.*pattern-handlers*",
                                    )?;
                                    rt::apply_direct(
                                        interp,
                                        "shen.x.programmable-pattern-matching.reduce",
                                        &[__t178, __t179],
                                    )?
                                })
                            },
                            Vec::new(),
                            interp,
                        )
                    };
                    rt::set_global(interp, "shen.*custom-pattern-reducer*", __v)
                };
                {
                    let _ = {
                        let __v = Value::nil();
                        rt::set_global(
                            interp,
                            "shen.x.programmable-pattern-matching.*pattern-handlers*",
                            __v,
                        )
                    };
                    {
                        let _ = {
                            let __v = Value::nil();
                            rt::set_global(
                                interp,
                                "shen.x.programmable-pattern-matching.*pattern-handlers-reg*",
                                __v,
                            )
                        };
                        break Ok(Value::sym(
                            interp.intern("shen.x.programmable-pattern-matching.done"),
                        ));
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_initialise(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.initialise",
        0,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_initialise,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.initialise",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_initialise,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.register-handler ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_register_x2d_handler(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 1 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.register-handler: expected 1 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7212 = args[0].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let __t188 = {
                let __t186 = v_V7212.clone();
                let __t187 = rt::global_value(
                    interp,
                    "shen.x.programmable-pattern-matching.*pattern-handlers-reg*",
                )?;
                rt::apply_direct(interp, "element?", &[__t186, __t187])?
            };
            if match rt::is_truthy(interp, &__t188) {
                Ok(b) => b,
                Err(e) => break Err(e),
            } {
                break Ok(v_V7212.clone());
            } else {
                {
                    let __t185 = Value::bool(true);
                    if match rt::is_truthy(interp, &__t185) {
                        Ok(b) => b,
                        Err(e) => break Err(e),
                    } {
                        {
                            let _ = {
                                let __v = {
                                    let __t180 = v_V7212.clone();
                                    let __t181 = rt::global_value(interp, "shen.x.programmable-pattern-matching.*pattern-handlers-reg*")?;
                                    rt::cons(&__t180, &__t181)
                                };
                                rt::set_global(
                                    interp,
                                    "shen.x.programmable-pattern-matching.*pattern-handlers-reg*",
                                    __v,
                                )
                            };
                            {
                                let _ = {
                                    let __v = {
                                        let __t183 = {
                                            let __t182 = v_V7212.clone();
                                            rt::apply_direct(interp, "fn", &[__t182])?
                                        };
                                        let __t184 = rt::global_value(interp, "shen.x.programmable-pattern-matching.*pattern-handlers*")?;
                                        rt::cons(&__t183, &__t184)
                                    };
                                    rt::set_global(
                                        interp,
                                        "shen.x.programmable-pattern-matching.*pattern-handlers*",
                                        __v,
                                    )
                                };
                                break Ok(v_V7212.clone());
                            }
                        }
                    } else {
                        break Err(ShenError::new("cond: no clause matched"));
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_register_x2d_handler(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.register-handler",
        1,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_register_x2d_handler,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.register-handler",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_register_x2d_handler,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.findpos ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 2 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.findpos: expected 2 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7213 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V7214 = args[1].clone();
    #[allow(clippy::never_loop)]
    loop {
        break Ok({
            let __t189 = v_V7213.clone();
            let __t190 = v_V7214.clone();
            let __t191 = Value::int(1i64);
            rt::apply_direct(
                interp,
                "shen.x.programmable-pattern-matching.findpos-h",
                &[__t189, __t190, __t191],
            )?
        });
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos(interp: &mut Interp) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.findpos",
        2,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.findpos",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.findpos-h ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos_x2d_h(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 3 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.findpos-h: expected 3 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7222 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V7223 = args[1].clone();
    #[allow(unused_mut)]
    let mut v_V7224 = args[2].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let __t215 = {
                let __t209 = Value::nil();
                let __t210 = v_V7223.clone();
                rt::eq(&__t209, &__t210)
            };
            if match rt::is_truthy(interp, &__t215) {
                Ok(b) => b,
                Err(e) => break Err(e),
            } {
                break Ok({
                    let __t214 = {
                        let __t211 = v_V7222.clone();
                        let __t212 = Value::str(" is not a pattern handler\n");
                        let __t213 = Value::sym(interp.intern("shen.a"));
                        rt::apply_direct(interp, "shen.app", &[__t211, __t212, __t213])?
                    };
                    rt::apply_direct(interp, "simple-error", &[__t214])?
                });
            } else {
                {
                    let __t208 = {
                        let __t206 = {
                            let __t202 = v_V7223.clone();
                            rt::is_cons(&__t202)
                        };
                        if !rt::is_truthy(interp, &__t206)? {
                            Value::bool(false)
                        } else {
                            let __t207 = {
                                let __t203 = v_V7222.clone();
                                let __t205 = {
                                    let __t204 = v_V7223.clone();
                                    rt::hd(&__t204)?
                                };
                                rt::eq(&__t203, &__t205)
                            };
                            Value::bool(rt::is_truthy(interp, &__t207)?)
                        }
                    };
                    if match rt::is_truthy(interp, &__t208) {
                        Ok(b) => b,
                        Err(e) => break Err(e),
                    } {
                        break Ok(v_V7224.clone());
                    } else {
                        {
                            let __t201 = {
                                let __t194 = v_V7223.clone();
                                rt::is_cons(&__t194)
                            };
                            if match rt::is_truthy(interp, &__t201) {
                                Ok(b) => b,
                                Err(e) => break Err(e),
                            } {
                                {
                                    let __t195 = v_V7222.clone();
                                    let __t197 = {
                                        let __t196 = v_V7223.clone();
                                        rt::tl(&__t196)?
                                    };
                                    let __t200 = {
                                        let __t198 = v_V7224.clone();
                                        let __t199 = Value::int(1i64);
                                        rt::add(&__t198, &__t199)?
                                    };
                                    v_V7222 = __t195;
                                    v_V7223 = __t197;
                                    v_V7224 = __t200;
                                    continue;
                                }
                            } else {
                                {
                                    let __t193 = Value::bool(true);
                                    if match rt::is_truthy(interp, &__t193) {
                                        Ok(b) => b,
                                        Err(e) => break Err(e),
                                    } {
                                        break Ok({
                                            let __t192 = Value::sym(interp.intern(
                                                "shen.x.programmable-pattern-matching.findpos-h",
                                            ));
                                            rt::apply_direct(interp, "shen.f-error", &[__t192])?
                                        });
                                    } else {
                                        break Err(ShenError::new("cond: no clause matched"));
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos_x2d_h(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.findpos-h",
        3,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos_x2d_h,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.findpos-h",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos_x2d_h,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.remove-nth ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_remove_x2d_nth(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 2 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.remove-nth: expected 2 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7229 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V7230 = args[1].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let __t244 = {
                let __t243 = {
                    let __t241 = {
                        let __t238 = v_V7229.clone();
                        rt::apply_direct(interp, "integer?", &[__t238])?
                    };
                    if !rt::is_truthy(interp, &__t241)? {
                        Value::bool(false)
                    } else {
                        let __t242 = {
                            let __t239 = v_V7229.clone();
                            let __t240 = Value::int(0i64);
                            rt::gt(&__t239, &__t240)?
                        };
                        Value::bool(rt::is_truthy(interp, &__t242)?)
                    }
                };
                rt::not(interp, &__t243)?
            };
            if match rt::is_truthy(interp, &__t244) {
                Ok(b) => b,
                Err(e) => break Err(e),
            } {
                break Ok(v_V7230.clone());
            } else {
                {
                    let __t237 = {
                        let __t235 = Value::nil();
                        let __t236 = v_V7230.clone();
                        rt::eq(&__t235, &__t236)
                    };
                    if match rt::is_truthy(interp, &__t237) {
                        Ok(b) => b,
                        Err(e) => break Err(e),
                    } {
                        break Ok(Value::nil());
                    } else {
                        {
                            let __t234 = {
                                let __t231 = {
                                    let __t228 = Value::int(1i64);
                                    let __t229 = v_V7229.clone();
                                    rt::eq(&__t228, &__t229)
                                };
                                if !rt::is_truthy(interp, &__t231)? {
                                    Value::bool(false)
                                } else {
                                    let __t232 = {
                                        let __t230 = v_V7230.clone();
                                        rt::is_cons(&__t230)
                                    };
                                    Value::bool(rt::is_truthy(interp, &__t232)?)
                                }
                            };
                            if match rt::is_truthy(interp, &__t234) {
                                Ok(b) => b,
                                Err(e) => break Err(e),
                            } {
                                break Ok({
                                    let __t233 = v_V7230.clone();
                                    rt::tl(&__t233)?
                                });
                            } else {
                                {
                                    let __t227 = {
                                        let __t218 = v_V7230.clone();
                                        rt::is_cons(&__t218)
                                    };
                                    if match rt::is_truthy(interp, &__t227) {
                                        Ok(b) => b,
                                        Err(e) => break Err(e),
                                    } {
                                        break Ok({
                                            let __t220 = {
                                                let __t219 = v_V7230.clone();
                                                rt::hd(&__t219)?
                                            };
                                            let __t226 = {
                                                let __t223 = {
                                                    let __t221 = v_V7229.clone();
                                                    let __t222 = Value::int(1i64);
                                                    rt::sub(&__t221, &__t222)?
                                                };
                                                let __t225 = {
                                                    let __t224 = v_V7230.clone();
                                                    rt::tl(&__t224)?
                                                };
                                                rt::apply_direct(interp, "shen.x.programmable-pattern-matching.remove-nth", &[__t223, __t225])?
                                            };
                                            rt::cons(&__t220, &__t226)
                                        });
                                    } else {
                                        {
                                            let __t217 = Value::bool(true);
                                            if match rt::is_truthy(interp, &__t217) {
                                                Ok(b) => b,
                                                Err(e) => break Err(e),
                                            } {
                                                break Ok({
                                                    let __t216 = Value::sym(interp.intern("shen.x.programmable-pattern-matching.remove-nth"));
                                                    rt::apply_direct(
                                                        interp,
                                                        "shen.f-error",
                                                        &[__t216],
                                                    )?
                                                });
                                            } else {
                                                break Err(ShenError::new(
                                                    "cond: no clause matched",
                                                ));
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_remove_x2d_nth(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.remove-nth",
        2,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_remove_x2d_nth,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.remove-nth",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_remove_x2d_nth,
    );
}

/// AOT-compiled from KL `(defun shen.x.programmable-pattern-matching.unregister-handler ...)`
pub fn aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_unregister_x2d_handler(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 1 {
        return Err(ShenError::new(format!(
            "shen.x.programmable-pattern-matching.unregister-handler: expected 1 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V7231 = args[0].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let v_W7232 = rt::global_value(
                interp,
                "shen.x.programmable-pattern-matching.*pattern-handlers-reg*",
            )?;
            {
                let v_W7233 = {
                    let __t245 = v_V7231.clone();
                    let __t246 = v_W7232.clone();
                    rt::apply_direct(
                        interp,
                        "shen.x.programmable-pattern-matching.findpos",
                        &[__t245, __t246],
                    )?
                };
                {
                    let v_W7234 = {
                        let __v = {
                            let __t247 = v_V7231.clone();
                            let __t248 = v_W7232.clone();
                            rt::apply_direct(interp, "remove", &[__t247, __t248])?
                        };
                        rt::set_global(
                            interp,
                            "shen.x.programmable-pattern-matching.*pattern-handlers-reg*",
                            __v,
                        )
                    };
                    {
                        let v_W7235 = {
                            let __v = {
                                let __t249 = v_W7233.clone();
                                let __t250 = rt::global_value(
                                    interp,
                                    "shen.x.programmable-pattern-matching.*pattern-handlers*",
                                )?;
                                rt::apply_direct(
                                    interp,
                                    "shen.x.programmable-pattern-matching.remove-nth",
                                    &[__t249, __t250],
                                )?
                            };
                            rt::set_global(
                                interp,
                                "shen.x.programmable-pattern-matching.*pattern-handlers*",
                                __v,
                            )
                        };
                        break Ok(v_V7231.clone());
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_unregister_x2d_handler(
    interp: &mut Interp,
) {
    interp.register_native(
        "shen.x.programmable-pattern-matching.unregister-handler",
        1,
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_unregister_x2d_handler,
    );
    interp.register_aot_direct(
        "shen.x.programmable-pattern-matching.unregister-handler",
        aot_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_unregister_x2d_handler,
    );
}

/// Register every AOT-compiled function on `interp`. Call after kernel
/// boot so these names override the tree-walked defuns.
pub fn install(interp: &mut Interp) {
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_apply_x2d_pattern_x2d_handlers(
        interp,
    );
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_make_x2d_stack(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_push(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_pop_x2d_all(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_surface_x2d_pattern_x2d_tail(
        interp,
    );
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_compile_x2d_pattern_x2d_h(
        interp,
    );
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_reduce(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_initialise(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_register_x2d_handler(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_findpos_x2d_h(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_remove_x2d_nth(interp);
    install_shen_x2e_x_x2e_programmable_x2d_pattern_x2d_matching_x2e_unregister_x2d_handler(interp);
}
