//! Auto-generated by `klcompile` from kernel/klambda/types.kl.
//!
//! DO NOT EDIT. Re-run klcompile to regenerate.

#![allow(
    unused_variables,
    unused_braces,
    unused_imports,
    clippy::let_and_return,
    clippy::needless_question_mark,
    clippy::redundant_clone,
    clippy::needless_late_init,
    clippy::len_zero,
    clippy::needless_borrow,
    clippy::approx_constant,
    clippy::redundant_closure_call,
    non_snake_case
)]

use crate::aot::runtime as rt;
use crate::error::{ShenError, ShenResult};
use crate::interp::eval::Interp;
use crate::value::Value;
use std::rc::Rc;

/// AOT-compiled from KL `(defun declare ...)`
pub fn aot_declare(interp: &mut Interp, args: &[Value]) -> ShenResult<Value> {
    if args.len() != 2 {
        return Err(ShenError::new(format!(
            "declare: expected 2 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V5507 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V5508 = args[1].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let v_W5509 = {
                let __t0 = v_V5508.clone();
                rt::apply_direct(interp, "shen.rectify-type", &[__t0])?
            };
            {
                let v_W5510 = {
                    let __t24 = {
                        let __t22 = {
                            let __t15 = {
                                let __t13 = {
                                    let v_V5507 = v_V5507.clone();
                                    let v_W5509 = v_W5509.clone();
                                    rt::make_aot_closure(
                                        "<lambda>",
                                        1,
                                        move |interp, args| {
                                            let v_Z5511 = args[0].clone();
                                            Ok({
                                                let v_V5507 = v_V5507.clone();
                                                let v_W5509 = v_W5509.clone();
                                                let v_Z5511 = v_Z5511.clone();
                                                rt::make_aot_closure(
                                                    "<lambda>",
                                                    1,
                                                    move |interp, args| {
                                                        let v_Z5512 = args[0].clone();
                                                        Ok({
                                                            let v_V5507 = v_V5507.clone();
                                                            let v_W5509 = v_W5509.clone();
                                                            let v_Z5511 = v_Z5511.clone();
                                                            let v_Z5512 = v_Z5512.clone();
                                                            rt::make_aot_closure(
                                                                "<lambda>",
                                                                1,
                                                                move |interp, args| {
                                                                    let v_Z5513 = args[0].clone();
                                                                    Ok({
                                                                        let v_V5507 =
                                                                            v_V5507.clone();
                                                                        let v_W5509 =
                                                                            v_W5509.clone();
                                                                        let v_Z5511 =
                                                                            v_Z5511.clone();
                                                                        let v_Z5512 =
                                                                            v_Z5512.clone();
                                                                        let v_Z5513 =
                                                                            v_Z5513.clone();
                                                                        rt::make_aot_closure(
                                                                            "<lambda>",
                                                                            1,
                                                                            move |interp, args| {
                                                                                let v_Z5514 =
                                                                                    args[0].clone();
                                                                                Ok({
                                                                                    let _ = {
                                                                                        rt::apply_direct(interp, "shen.incinfs", &[])?
                                                                                    };
                                                                                    {
                                                                                        let __t4 = {
                                                                                            let __t3 = {
                                                                                                let __t1 = v_V5507.clone();
                                                                                                let __t2 = v_Z5511.clone();
                                                                                                rt::apply_direct(interp, "shen.deref", &[__t1, __t2])?
                                                                                            };
                                                                                            rt::apply_direct(interp, "receive", &[__t3])?
                                                                                        };
                                                                                        let __t8 = {
                                                                                            let __t7 = {
                                                                                                let __t5 = v_W5509.clone();
                                                                                                let __t6 = v_Z5511.clone();
                                                                                                rt::apply_direct(interp, "shen.deref", &[__t5, __t6])?
                                                                                            };
                                                                                            rt::apply_direct(interp, "receive", &[__t7])?
                                                                                        };
                                                                                        let __t9 = v_Z5511.clone();
                                                                                        let __t10 = v_Z5512.clone();
                                                                                        let __t11 = v_Z5513.clone();
                                                                                        let __t12 = v_Z5514.clone();
                                                                                        rt::apply_direct(interp, "shen.variancy", &[__t4, __t8, __t9, __t10, __t11, __t12])?
                                                                                    }
                                                                                })
                                                                            },
                                                                            vec![
                                                                                v_V5507, v_W5509,
                                                                                v_Z5511, v_Z5512,
                                                                                v_Z5513,
                                                                            ],
                                                                            interp,
                                                                        )
                                                                    })
                                                                },
                                                                vec![
                                                                    v_V5507, v_W5509, v_Z5511,
                                                                    v_Z5512,
                                                                ],
                                                                interp,
                                                            )
                                                        })
                                                    },
                                                    vec![v_V5507, v_W5509, v_Z5511],
                                                    interp,
                                                )
                                            })
                                        },
                                        vec![v_V5507, v_W5509],
                                        interp,
                                    )
                                };
                                let __t14 =
                                    { rt::apply_direct(interp, "shen.prolog-vector", &[])? };
                                rt::apply_value(interp, __t13, &[__t14])?
                            };
                            let __t21 = {
                                let __t16 = Value::bool(true);
                                let __t20 = {
                                    let __t17 = Value::int(0i64);
                                    let __t19 = {
                                        let __t18 = Value::int(0i64);
                                        rt::apply_direct(interp, "vector", &[__t18])?
                                    };
                                    rt::apply_direct(interp, "@v", &[__t17, __t19])?
                                };
                                rt::apply_direct(interp, "@v", &[__t16, __t20])?
                            };
                            rt::apply_value(interp, __t15, &[__t21])?
                        };
                        let __t23 = Value::int(0i64);
                        rt::apply_value(interp, __t22, &[__t23])?
                    };
                    let __t25 = {
                        rt::make_aot_closure(
                            "<freeze>",
                            0,
                            move |interp, _args| Ok(Value::bool(true)),
                            Vec::new(),
                            interp,
                        )
                    };
                    rt::apply_value(interp, __t24, &[__t25])?
                };
                {
                    let v_W5515 = {
                        let __t27 = {
                            let __t26 = v_V5508.clone();
                            rt::apply_direct(interp, "shen.prolog-abstraction", &[__t26])?
                        };
                        rt::apply_direct(interp, "eval-kl", &[__t27])?
                    };
                    {
                        let v_W5516 = {
                            let __v = {
                                let __t28 = v_V5507.clone();
                                let __t29 = v_W5515.clone();
                                let __t30 = rt::global_value(interp, "shen.*sigf*")?;
                                rt::apply_direct(interp, "shen.assoc->", &[__t28, __t29, __t30])?
                            };
                            rt::set_global(interp, "shen.*sigf*", __v)
                        };
                        break Ok(v_V5507.clone());
                    }
                }
            }
        }
    }
}

fn install_declare(interp: &mut Interp) {
    interp.register_native("declare", 2, aot_declare);
    interp.register_aot_direct("declare", aot_declare);
}

/// AOT-compiled from KL `(defun shen.variancy ...)`
pub fn aot_shen_x2e_variancy(interp: &mut Interp, args: &[Value]) -> ShenResult<Value> {
    if args.len() != 6 {
        return Err(ShenError::new(format!(
            "shen.variancy: expected 6 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V5517 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V5518 = args[1].clone();
    #[allow(unused_mut)]
    let mut v_V5519 = args[2].clone();
    #[allow(unused_mut)]
    let mut v_V5520 = args[3].clone();
    #[allow(unused_mut)]
    let mut v_V5521 = args[4].clone();
    #[allow(unused_mut)]
    let mut v_V5522 = args[5].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let v_W5523 = {
                let __t31 = v_V5521.clone();
                let __t32 = Value::int(1i64);
                rt::add(&__t31, &__t32)?
            };
            {
                let v_W5524 = {
                    let __t131 = {
                        let __t33 = v_V5520.clone();
                        rt::apply_direct(interp, "shen.unlocked?", &[__t33])?
                    };
                    if rt::is_truthy(interp, &__t131)? {
                        {
                            let v_W5525 = {
                                let __t34 = v_V5518.clone();
                                let __t35 = v_V5519.clone();
                                rt::apply_direct(interp, "shen.lazyderef", &[__t34, __t35])?
                            };
                            {
                                let v_W5526 = {
                                    let v_V5517 = v_V5517.clone();
                                    let v_V5519 = v_V5519.clone();
                                    let v_V5520 = v_V5520.clone();
                                    let v_V5522 = v_V5522.clone();
                                    let v_W5523 = v_W5523.clone();
                                    rt::make_aot_closure(
                                        "<lambda>",
                                        1,
                                        move |interp, args| {
                                            let v_Z5527 = args[0].clone();
                                            Ok({
                                                let v_W5528 = {
                                                    let __t36 = v_V5519.clone();
                                                    rt::apply_direct(
                                                        interp,
                                                        "shen.newpv",
                                                        &[__t36],
                                                    )?
                                                };
                                                {
                                                    let __t37 = v_V5519.clone();
                                                    let __t70 = {
                                                        let _ = {
                                                            rt::apply_direct(
                                                                interp,
                                                                "shen.incinfs",
                                                                &[],
                                                            )?
                                                        };
                                                        {
                                                            let __t43 = {
                                                                let __t41 = {
                                                                    let __t40 = {
                                                                        let __t38 = v_V5517.clone();
                                                                        let __t39 = v_V5519.clone();
                                                                        rt::apply_direct(
                                                                            interp,
                                                                            "shen.deref",
                                                                            &[__t38, __t39],
                                                                        )?
                                                                    };
                                                                    rt::apply_direct(
                                                                        interp,
                                                                        "arity",
                                                                        &[__t40],
                                                                    )?
                                                                };
                                                                let __t42 = Value::int(0i64);
                                                                rt::eq(&__t41, &__t42)
                                                            };
                                                            let __t44 = v_V5519.clone();
                                                            let __t45 = v_V5520.clone();
                                                            let __t46 = v_W5523.clone();
                                                            let __t69 = {
                                                                let v_V5517 = v_V5517.clone();
                                                                let v_V5519 = v_V5519.clone();
                                                                let v_V5520 = v_V5520.clone();
                                                                let v_V5522 = v_V5522.clone();
                                                                let v_W5523 = v_W5523.clone();
                                                                let v_W5528 = v_W5528.clone();
                                                                let v_Z5527 = v_Z5527.clone();
                                                                rt::make_aot_closure(
                                                                    "<freeze>",
                                                                    0,
                                                                    move |interp, _args| {
                                                                        Ok({
                                                                            let __t47 =
                                                                                v_V5519.clone();
                                                                            let __t48 =
                                                                                v_V5520.clone();
                                                                            let __t49 =
                                                                                v_W5523.clone();
                                                                            let __t68 = {
                                                                                let v_V5517 =
                                                                                    v_V5517.clone();
                                                                                let v_V5519 =
                                                                                    v_V5519.clone();
                                                                                let v_V5520 =
                                                                                    v_V5520.clone();
                                                                                let v_V5522 =
                                                                                    v_V5522.clone();
                                                                                let v_W5523 =
                                                                                    v_W5523.clone();
                                                                                let v_W5528 =
                                                                                    v_W5528.clone();
                                                                                let v_Z5527 =
                                                                                    v_Z5527.clone();
                                                                                rt::make_aot_closure("<freeze>", 0, move |interp, _args| Ok({ let __t54 = { let __t50 = Value::sym(interp.intern("fn")); let __t53 = { let __t51 = v_V5517.clone(); let __t52 = Value::nil(); rt::cons(&__t51, &__t52) }; rt::cons(&__t50, &__t53) }; let __t55 = v_W5528.clone(); let __t56 = Value::nil(); let __t57 = v_V5519.clone(); let __t58 = v_V5520.clone(); let __t59 = v_W5523.clone(); let __t67 = { let v_V5517 = v_V5517.clone(); let v_V5519 = v_V5519.clone(); let v_V5520 = v_V5520.clone(); let v_V5522 = v_V5522.clone(); let v_W5523 = v_W5523.clone(); let v_W5528 = v_W5528.clone(); let v_Z5527 = v_Z5527.clone(); rt::make_aot_closure("<freeze>", 0, move |interp, _args| Ok({ let __t60 = v_V5517.clone(); let __t61 = v_Z5527.clone(); let __t62 = v_W5528.clone(); let __t63 = v_V5519.clone(); let __t64 = v_V5520.clone(); let __t65 = v_W5523.clone(); let __t66 = v_V5522.clone(); rt::apply_direct(interp, "shen.variants?", &[__t60, __t61, __t62, __t63, __t64, __t65, __t66])? }), vec![v_V5517, v_V5519, v_V5520, v_V5522, v_W5523, v_W5528, v_Z5527], interp) }; rt::apply_direct(interp, "shen.system-S-h", &[__t54, __t55, __t56, __t57, __t58, __t59, __t67])? }), vec![v_V5517, v_V5519, v_V5520, v_V5522, v_W5523, v_W5528, v_Z5527], interp)
                                                                            };
                                                                            rt::apply_direct(
                                                                                interp,
                                                                                "shen.cut",
                                                                                &[
                                                                                    __t47, __t48,
                                                                                    __t49, __t68,
                                                                                ],
                                                                            )?
                                                                        })
                                                                    },
                                                                    vec![
                                                                        v_V5517, v_V5519, v_V5520,
                                                                        v_V5522, v_W5523, v_W5528,
                                                                        v_Z5527,
                                                                    ],
                                                                    interp,
                                                                )
                                                            };
                                                            rt::apply_direct(
                                                                interp,
                                                                "when",
                                                                &[
                                                                    __t43, __t44, __t45, __t46,
                                                                    __t69,
                                                                ],
                                                            )?
                                                        }
                                                    };
                                                    rt::apply_direct(
                                                        interp,
                                                        "shen.gc",
                                                        &[__t37, __t70],
                                                    )?
                                                }
                                            })
                                        },
                                        vec![v_V5517, v_V5519, v_V5520, v_V5522, v_W5523],
                                        interp,
                                    )
                                };
                                {
                                    let __t130 = {
                                        let __t71 = v_W5525.clone();
                                        rt::is_cons(&__t71)
                                    };
                                    if rt::is_truthy(interp, &__t130)? {
                                        {
                                            let v_W5529 = {
                                                let __t73 = {
                                                    let __t72 = v_W5525.clone();
                                                    rt::hd(&__t72)?
                                                };
                                                let __t74 = v_V5519.clone();
                                                rt::apply_direct(
                                                    interp,
                                                    "shen.lazyderef",
                                                    &[__t73, __t74],
                                                )?
                                            };
                                            {
                                                let v_W5530 = {
                                                    let v_V5519 = v_V5519.clone();
                                                    let v_W5525 = v_W5525.clone();
                                                    let v_W5526 = v_W5526.clone();
                                                    rt::make_aot_closure(
                                                        "<freeze>",
                                                        0,
                                                        move |interp, _args| {
                                                            Ok({
                                                                let v_W5531 = {
                                                                    let __t76 = {
                                                                        let __t75 = v_W5525.clone();
                                                                        rt::tl(&__t75)?
                                                                    };
                                                                    let __t77 = v_V5519.clone();
                                                                    rt::apply_direct(
                                                                        interp,
                                                                        "shen.lazyderef",
                                                                        &[__t76, __t77],
                                                                    )?
                                                                };
                                                                {
                                                                    let v_W5532 = {
                                                                        let v_W5526 =
                                                                            v_W5526.clone();
                                                                        rt::make_aot_closure(
                                                                            "<lambda>",
                                                                            1,
                                                                            move |interp, args| {
                                                                                let v_Z5533 =
                                                                                    args[0].clone();
                                                                                Ok({
                                                                                    let __t78 =
                                                                                        v_Z5533
                                                                                            .clone(
                                                                                            );
                                                                                    rt::apply_value(
                                                                                        interp,
                                                                                        v_W5526
                                                                                            .clone(
                                                                                            ),
                                                                                        &[__t78],
                                                                                    )?
                                                                                })
                                                                            },
                                                                            vec![v_W5526],
                                                                            interp,
                                                                        )
                                                                    };
                                                                    {
                                                                        let __t106 = {
                                                                            let __t79 =
                                                                                v_W5531.clone();
                                                                            rt::is_cons(&__t79)
                                                                        };
                                                                        if rt::is_truthy(
                                                                            interp, &__t106,
                                                                        )? {
                                                                            {
                                                                                let v_W5534 = {
                                                                                    let __t80 =
                                                                                        v_W5531
                                                                                            .clone(
                                                                                            );
                                                                                    rt::hd(&__t80)?
                                                                                };
                                                                                {
                                                                                    let v_W5535 = {
                                                                                        let __t82 = {
                                                                                            let __t81 = v_W5531.clone();
                                                                                            rt::tl(&__t81)?
                                                                                        };
                                                                                        let __t83 = v_V5519.clone();
                                                                                        rt::apply_direct(interp, "shen.lazyderef", &[__t82, __t83])?
                                                                                    };
                                                                                    {
                                                                                        let v_W5536 = {
                                                                                            let v_W5532 = v_W5532.clone();
                                                                                            let v_W5534 = v_W5534.clone();
                                                                                            rt::make_aot_closure("<freeze>", 0, move |interp, _args| Ok({ let __t84 = v_W5534.clone(); rt::apply_value(interp, v_W5532.clone(), &[__t84])? }), vec![v_W5532, v_W5534], interp)
                                                                                        };
                                                                                        {
                                                                                            let __t93 = {
                                                                                                let __t85 = v_W5535.clone();
                                                                                                let __t86 = Value::nil();
                                                                                                rt::eq(&__t85, &__t86)
                                                                                            };
                                                                                            if rt::is_truthy(interp, &__t93)? { rt::apply_value(interp, v_W5536.clone(), &[])? } else { { let __t92 = { let __t87 = v_W5535.clone(); rt::apply_direct(interp, "shen.pvar?", &[__t87])? }; if rt::is_truthy(interp, &__t92)? { { let __t88 = v_W5535.clone(); let __t89 = Value::nil(); let __t90 = v_V5519.clone(); let __t91 = v_W5536.clone(); rt::apply_direct(interp, "shen.bind!", &[__t88, __t89, __t90, __t91])? } } else { Value::bool(false) } } }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        } else {
                                                                            {
                                                                                let __t105 = {
                                                                                    let __t94 =
                                                                                        v_W5531
                                                                                            .clone(
                                                                                            );
                                                                                    rt::apply_direct(interp, "shen.pvar?", &[__t94])?
                                                                                };
                                                                                if rt::is_truthy(
                                                                                    interp, &__t105,
                                                                                )? {
                                                                                    {
                                                                                        let v_W5537 = {
                                                                                            let __t95 = v_V5519.clone();
                                                                                            rt::apply_direct(interp, "shen.newpv", &[__t95])?
                                                                                        };
                                                                                        {
                                                                                            let __t96 = v_V5519.clone();
                                                                                            let __t104 = {
                                                                                                let __t97 = v_W5531.clone();
                                                                                                let __t100 = { let __t98 = v_W5537.clone(); let __t99 = Value::nil(); rt::cons(&__t98, &__t99) };
                                                                                                let __t101 = v_V5519.clone();
                                                                                                let __t103 = { let v_W5532 = v_W5532.clone(); let v_W5537 = v_W5537.clone(); rt::make_aot_closure("<freeze>", 0, move |interp, _args| Ok({ let __t102 = v_W5537.clone(); rt::apply_value(interp, v_W5532.clone(), &[__t102])? }), vec![v_W5532, v_W5537], interp) };
                                                                                                rt::apply_direct(interp, "shen.bind!", &[__t97, __t100, __t101, __t103])?
                                                                                            };
                                                                                            rt::apply_direct(interp, "shen.gc", &[__t96, __t104])?
                                                                                        }
                                                                                    }
                                                                                } else {
                                                                                    Value::bool(
                                                                                        false,
                                                                                    )
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            })
                                                        },
                                                        vec![v_V5519, v_W5525, v_W5526],
                                                        interp,
                                                    )
                                                };
                                                {
                                                    let __t115 = {
                                                        let __t107 = v_W5529.clone();
                                                        let __t108 =
                                                            Value::sym(interp.intern("-->"));
                                                        rt::eq(&__t107, &__t108)
                                                    };
                                                    if rt::is_truthy(interp, &__t115)? {
                                                        rt::apply_value(
                                                            interp,
                                                            v_W5530.clone(),
                                                            &[],
                                                        )?
                                                    } else {
                                                        {
                                                            let __t114 = {
                                                                let __t109 = v_W5529.clone();
                                                                rt::apply_direct(
                                                                    interp,
                                                                    "shen.pvar?",
                                                                    &[__t109],
                                                                )?
                                                            };
                                                            if rt::is_truthy(interp, &__t114)? {
                                                                {
                                                                    let __t110 = v_W5529.clone();
                                                                    let __t111 = Value::sym(
                                                                        interp.intern("-->"),
                                                                    );
                                                                    let __t112 = v_V5519.clone();
                                                                    let __t113 = v_W5530.clone();
                                                                    rt::apply_direct(
                                                                        interp,
                                                                        "shen.bind!",
                                                                        &[
                                                                            __t110, __t111, __t112,
                                                                            __t113,
                                                                        ],
                                                                    )?
                                                                }
                                                            } else {
                                                                Value::bool(false)
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    } else {
                                        {
                                            let __t129 = {
                                                let __t116 = v_W5525.clone();
                                                rt::apply_direct(interp, "shen.pvar?", &[__t116])?
                                            };
                                            if rt::is_truthy(interp, &__t129)? {
                                                {
                                                    let v_W5538 = {
                                                        let __t117 = v_V5519.clone();
                                                        rt::apply_direct(
                                                            interp,
                                                            "shen.newpv",
                                                            &[__t117],
                                                        )?
                                                    };
                                                    {
                                                        let __t118 = v_V5519.clone();
                                                        let __t128 = {
                                                            let __t119 = v_W5525.clone();
                                                            let __t124 = {
                                                                let __t120 = Value::sym(
                                                                    interp.intern("-->"),
                                                                );
                                                                let __t123 = {
                                                                    let __t121 = v_W5538.clone();
                                                                    let __t122 = Value::nil();
                                                                    rt::cons(&__t121, &__t122)
                                                                };
                                                                rt::cons(&__t120, &__t123)
                                                            };
                                                            let __t125 = v_V5519.clone();
                                                            let __t127 = {
                                                                let v_W5526 = v_W5526.clone();
                                                                let v_W5538 = v_W5538.clone();
                                                                rt::make_aot_closure(
                                                                    "<freeze>",
                                                                    0,
                                                                    move |interp, _args| {
                                                                        Ok({
                                                                            let __t126 =
                                                                                v_W5538.clone();
                                                                            rt::apply_value(
                                                                                interp,
                                                                                v_W5526.clone(),
                                                                                &[__t126],
                                                                            )?
                                                                        })
                                                                    },
                                                                    vec![v_W5526, v_W5538],
                                                                    interp,
                                                                )
                                                            };
                                                            rt::apply_direct(
                                                                interp,
                                                                "shen.bind!",
                                                                &[__t119, __t124, __t125, __t127],
                                                            )?
                                                        };
                                                        rt::apply_direct(
                                                            interp,
                                                            "shen.gc",
                                                            &[__t118, __t128],
                                                        )?
                                                    }
                                                }
                                            } else {
                                                Value::bool(false)
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    } else {
                        Value::bool(false)
                    }
                };
                {
                    let __t134 = {
                        let __t132 = v_W5524.clone();
                        let __t133 = Value::bool(false);
                        rt::eq(&__t132, &__t133)
                    };
                    if match rt::is_truthy(interp, &__t134) {
                        Ok(b) => b,
                        Err(e) => break Err(e),
                    } {
                        {
                            let v_W5539 = {
                                let __t157 = {
                                    let __t135 = v_V5520.clone();
                                    rt::apply_direct(interp, "shen.unlocked?", &[__t135])?
                                };
                                if rt::is_truthy(interp, &__t157)? {
                                    {
                                        let v_W5540 = {
                                            let __t136 = v_V5519.clone();
                                            rt::apply_direct(interp, "shen.newpv", &[__t136])?
                                        };
                                        {
                                            let __t137 = v_V5519.clone();
                                            let __t156 = {
                                                let _ = {
                                                    rt::apply_direct(interp, "shen.incinfs", &[])?
                                                };
                                                {
                                                    let __t142 = {
                                                        let __t138 =
                                                            Value::sym(interp.intern("fn"));
                                                        let __t141 = {
                                                            let __t139 = v_V5517.clone();
                                                            let __t140 = Value::nil();
                                                            rt::cons(&__t139, &__t140)
                                                        };
                                                        rt::cons(&__t138, &__t141)
                                                    };
                                                    let __t143 = v_W5540.clone();
                                                    let __t144 = Value::nil();
                                                    let __t145 = v_V5519.clone();
                                                    let __t146 = v_V5520.clone();
                                                    let __t147 = v_W5523.clone();
                                                    let __t155 = {
                                                        let v_V5517 = v_V5517.clone();
                                                        let v_V5518 = v_V5518.clone();
                                                        let v_V5519 = v_V5519.clone();
                                                        let v_V5520 = v_V5520.clone();
                                                        let v_V5522 = v_V5522.clone();
                                                        let v_W5523 = v_W5523.clone();
                                                        let v_W5540 = v_W5540.clone();
                                                        rt::make_aot_closure(
                                                            "<freeze>",
                                                            0,
                                                            move |interp, _args| {
                                                                Ok({
                                                                    let __t148 = v_V5517.clone();
                                                                    let __t149 = v_W5540.clone();
                                                                    let __t150 = v_V5518.clone();
                                                                    let __t151 = v_V5519.clone();
                                                                    let __t152 = v_V5520.clone();
                                                                    let __t153 = v_W5523.clone();
                                                                    let __t154 = v_V5522.clone();
                                                                    rt::apply_direct(
                                                                        interp,
                                                                        "shen.variants?",
                                                                        &[
                                                                            __t148, __t149, __t150,
                                                                            __t151, __t152, __t153,
                                                                            __t154,
                                                                        ],
                                                                    )?
                                                                })
                                                            },
                                                            vec![
                                                                v_V5517, v_V5518, v_V5519, v_V5520,
                                                                v_V5522, v_W5523, v_W5540,
                                                            ],
                                                            interp,
                                                        )
                                                    };
                                                    rt::apply_direct(
                                                        interp,
                                                        "shen.system-S-h",
                                                        &[
                                                            __t142, __t143, __t144, __t145, __t146,
                                                            __t147, __t155,
                                                        ],
                                                    )?
                                                }
                                            };
                                            rt::apply_direct(interp, "shen.gc", &[__t137, __t156])?
                                        }
                                    }
                                } else {
                                    Value::bool(false)
                                }
                            };
                            {
                                let __t160 = {
                                    let __t158 = v_W5539.clone();
                                    let __t159 = Value::bool(false);
                                    rt::eq(&__t158, &__t159)
                                };
                                if match rt::is_truthy(interp, &__t160) {
                                    Ok(b) => b,
                                    Err(e) => break Err(e),
                                } {
                                    break Ok({
                                        let __t161 = v_V5520.clone();
                                        let __t162 = v_W5523.clone();
                                        rt::apply_direct(interp, "shen.unlock", &[__t161, __t162])?
                                    });
                                } else {
                                    break Ok(v_W5539.clone());
                                }
                            }
                        }
                    } else {
                        break Ok(v_W5524.clone());
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_variancy(interp: &mut Interp) {
    interp.register_native("shen.variancy", 6, aot_shen_x2e_variancy);
    interp.register_aot_direct("shen.variancy", aot_shen_x2e_variancy);
}

/// AOT-compiled from KL `(defun shen.variants? ...)`
pub fn aot_shen_x2e_variants_x3f_(interp: &mut Interp, args: &[Value]) -> ShenResult<Value> {
    if args.len() != 7 {
        return Err(ShenError::new(format!(
            "shen.variants?: expected 7 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V5541 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V5542 = args[1].clone();
    #[allow(unused_mut)]
    let mut v_V5543 = args[2].clone();
    #[allow(unused_mut)]
    let mut v_V5544 = args[3].clone();
    #[allow(unused_mut)]
    let mut v_V5545 = args[4].clone();
    #[allow(unused_mut)]
    let mut v_V5546 = args[5].clone();
    #[allow(unused_mut)]
    let mut v_V5547 = args[6].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let v_W5548 = {
                let __t170 = {
                    let __t163 = v_V5545.clone();
                    rt::apply_direct(interp, "shen.unlocked?", &[__t163])?
                };
                if rt::is_truthy(interp, &__t170)? {
                    {
                        let _ = { rt::apply_direct(interp, "shen.incinfs", &[])? };
                        {
                            let __t164 = v_V5542.clone();
                            let __t165 = v_V5543.clone();
                            let __t166 = v_V5544.clone();
                            let __t167 = v_V5545.clone();
                            let __t168 = v_V5546.clone();
                            let __t169 = v_V5547.clone();
                            rt::apply_direct(
                                interp,
                                "is!",
                                &[__t164, __t165, __t166, __t167, __t168, __t169],
                            )?
                        }
                    }
                } else {
                    Value::bool(false)
                }
            };
            {
                let __t173 = {
                    let __t171 = v_W5548.clone();
                    let __t172 = Value::bool(false);
                    rt::eq(&__t171, &__t172)
                };
                if match rt::is_truthy(interp, &__t173) {
                    Ok(b) => b,
                    Err(e) => break Err(e),
                } {
                    {
                        let __t175 = {
                            let __t174 = v_V5545.clone();
                            rt::apply_direct(interp, "shen.unlocked?", &[__t174])?
                        };
                        if match rt::is_truthy(interp, &__t175) {
                            Ok(b) => b,
                            Err(e) => break Err(e),
                        } {
                            {
                                let v_W5549 = {
                                    let __t176 = v_V5544.clone();
                                    rt::apply_direct(interp, "shen.newpv", &[__t176])?
                                };
                                break Ok({
                                    let __t177 = v_V5544.clone();
                                    let __t193 = {
                                        let _ = { rt::apply_direct(interp, "shen.incinfs", &[])? };
                                        {
                                            let __t178 = v_W5549.clone();
                                            let __t188 = {
                                                let __t186 = {
                                                    let __t179 = Value::str(
                                                        "warning: changing the type of ",
                                                    );
                                                    let __t185 = {
                                                        let __t182 = {
                                                            let __t180 = v_V5541.clone();
                                                            let __t181 = v_V5544.clone();
                                                            rt::apply_direct(
                                                                interp,
                                                                "shen.deref",
                                                                &[__t180, __t181],
                                                            )?
                                                        };
                                                        let __t183 =
                                                            Value::str(" may create errors\n");
                                                        let __t184 =
                                                            Value::sym(interp.intern("shen.a"));
                                                        rt::apply_direct(
                                                            interp,
                                                            "shen.app",
                                                            &[__t182, __t183, __t184],
                                                        )?
                                                    };
                                                    rt::cn(&__t179, &__t185)?
                                                };
                                                let __t187 =
                                                    { rt::apply_direct(interp, "stoutput", &[])? };
                                                rt::apply_direct(interp, "pr", &[__t186, __t187])?
                                            };
                                            let __t189 = v_V5544.clone();
                                            let __t190 = v_V5545.clone();
                                            let __t191 = v_V5546.clone();
                                            let __t192 = v_V5547.clone();
                                            rt::apply_direct(
                                                interp,
                                                "is",
                                                &[__t178, __t188, __t189, __t190, __t191, __t192],
                                            )?
                                        }
                                    };
                                    rt::apply_direct(interp, "shen.gc", &[__t177, __t193])?
                                });
                            }
                        } else {
                            break Ok(Value::bool(false));
                        }
                    }
                } else {
                    break Ok(v_W5548.clone());
                }
            }
        }
    }
}

fn install_shen_x2e_variants_x3f_(interp: &mut Interp) {
    interp.register_native("shen.variants?", 7, aot_shen_x2e_variants_x3f_);
    interp.register_aot_direct("shen.variants?", aot_shen_x2e_variants_x3f_);
}

/// AOT-compiled from KL `(defun shen.prolog-abstraction ...)`
pub fn aot_shen_x2e_prolog_x2d_abstraction(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 1 {
        return Err(ShenError::new(format!(
            "shen.prolog-abstraction: expected 1 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V5550 = args[0].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let v_W5551 = {
                let __t194 = Value::sym(interp.intern("B"));
                rt::apply_direct(interp, "gensym", &[__t194])?
            };
            {
                let v_W5552 = {
                    let __t195 = Value::sym(interp.intern("L"));
                    rt::apply_direct(interp, "gensym", &[__t195])?
                };
                {
                    let v_W5553 = {
                        let __t196 = Value::sym(interp.intern("Key"));
                        rt::apply_direct(interp, "gensym", &[__t196])?
                    };
                    {
                        let v_W5554 = {
                            let __t197 = Value::sym(interp.intern("C"));
                            rt::apply_direct(interp, "gensym", &[__t197])?
                        };
                        {
                            let v_W5555 = {
                                let __t198 = Value::sym(interp.intern("V"));
                                rt::apply_direct(interp, "gensym", &[__t198])?
                            };
                            {
                                let v_W5556 = {
                                    let __t199 = v_V5550.clone();
                                    rt::apply_direct(interp, "shen.extract-vars", &[__t199])?
                                };
                                break Ok({
                                    let __t200 = Value::sym(interp.intern("lambda"));
                                    let __t247 = {
                                        let __t201 = v_W5555.clone();
                                        let __t246 = {
                                            let __t244 = {
                                                let __t202 = Value::sym(interp.intern("lambda"));
                                                let __t243 = {
                                                    let __t203 = v_W5551.clone();
                                                    let __t242 = {
                                                        let __t240 = {
                                                            let __t204 =
                                                                Value::sym(interp.intern("lambda"));
                                                            let __t239 = {
                                                                let __t205 = v_W5552.clone();
                                                                let __t238 = {
                                                                    let __t236 = {
                                                                        let __t206 = Value::sym(
                                                                            interp.intern("lambda"),
                                                                        );
                                                                        let __t235 = {
                                                                            let __t207 =
                                                                                v_W5553.clone();
                                                                            let __t234 = {
                                                                                let __t232 = {
                                                                                    let __t208 = Value::sym(interp.intern("lambda"));
                                                                                    let __t231 = {
                                                                                        let __t209 = v_W5554.clone();
                                                                                        let __t230 = {
                                                                                            let __t228 = {
                                                                                                let __t210 = v_W5556.clone();
                                                                                                let __t226 = { let __t211 = Value::sym(interp.intern("is!")); let __t225 = { let __t212 = v_W5555.clone(); let __t224 = { let __t214 = { let __t213 = v_V5550.clone(); rt::apply_direct(interp, "shen.rcons_form", &[__t213])? }; let __t223 = { let __t215 = v_W5551.clone(); let __t222 = { let __t216 = v_W5552.clone(); let __t221 = { let __t217 = v_W5553.clone(); let __t220 = { let __t218 = v_W5554.clone(); let __t219 = Value::nil(); rt::cons(&__t218, &__t219) }; rt::cons(&__t217, &__t220) }; rt::cons(&__t216, &__t221) }; rt::cons(&__t215, &__t222) }; rt::cons(&__t214, &__t223) }; rt::cons(&__t212, &__t224) }; rt::cons(&__t211, &__t225) };
                                                                                                let __t227 = v_W5551.clone();
                                                                                                rt::apply_direct(interp, "shen.stpart", &[__t210, __t226, __t227])?
                                                                                            };
                                                                                            let __t229 = Value::nil();
                                                                                            rt::cons(&__t228, &__t229)
                                                                                        };
                                                                                        rt::cons(
                                                                                            &__t209,
                                                                                            &__t230,
                                                                                        )
                                                                                    };
                                                                                    rt::cons(
                                                                                        &__t208,
                                                                                        &__t231,
                                                                                    )
                                                                                };
                                                                                let __t233 =
                                                                                    Value::nil();
                                                                                rt::cons(
                                                                                    &__t232,
                                                                                    &__t233,
                                                                                )
                                                                            };
                                                                            rt::cons(
                                                                                &__t207, &__t234,
                                                                            )
                                                                        };
                                                                        rt::cons(&__t206, &__t235)
                                                                    };
                                                                    let __t237 = Value::nil();
                                                                    rt::cons(&__t236, &__t237)
                                                                };
                                                                rt::cons(&__t205, &__t238)
                                                            };
                                                            rt::cons(&__t204, &__t239)
                                                        };
                                                        let __t241 = Value::nil();
                                                        rt::cons(&__t240, &__t241)
                                                    };
                                                    rt::cons(&__t203, &__t242)
                                                };
                                                rt::cons(&__t202, &__t243)
                                            };
                                            let __t245 = Value::nil();
                                            rt::cons(&__t244, &__t245)
                                        };
                                        rt::cons(&__t201, &__t246)
                                    };
                                    rt::cons(&__t200, &__t247)
                                });
                            }
                        }
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_prolog_x2d_abstraction(interp: &mut Interp) {
    interp.register_native(
        "shen.prolog-abstraction",
        1,
        aot_shen_x2e_prolog_x2d_abstraction,
    );
    interp.register_aot_direct(
        "shen.prolog-abstraction",
        aot_shen_x2e_prolog_x2d_abstraction,
    );
}

/// AOT-compiled from KL `(defun shen.demod ...)`
pub fn aot_shen_x2e_demod(interp: &mut Interp, args: &[Value]) -> ShenResult<Value> {
    if args.len() != 1 {
        return Err(ShenError::new(format!(
            "shen.demod: expected 1 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V5557 = args[0].clone();
    #[allow(clippy::never_loop)]
    loop {
        break Ok(v_V5557.clone());
    }
}

fn install_shen_x2e_demod(interp: &mut Interp) {
    interp.register_native("shen.demod", 1, aot_shen_x2e_demod);
    interp.register_aot_direct("shen.demod", aot_shen_x2e_demod);
}

/// Register every AOT-compiled function on `interp`. Call after kernel
/// boot so these names override the tree-walked defuns.
pub fn install(interp: &mut Interp) {
    install_declare(interp);
    install_shen_x2e_variancy(interp);
    install_shen_x2e_variants_x3f_(interp);
    install_shen_x2e_prolog_x2d_abstraction(interp);
    install_shen_x2e_demod(interp);
}
