//! Authz-shaped served benchmark: the >=1.5x kill-gate measurement for
//! the AOT-native loaded-Shen overlay (Lever B productionization).
//!
//! Workload = the shen-cedar served shape: load the committed authz spec
//! (`examples/shen-cedar-authz/spec/verify.shen` + `spec/authz.shen`, the
//! REAL verifier the example runs) plus a scaled deterministic data corpus
//! (`benches/authz_bench_data.shen`: 64-role DAG in depth-8 chains, 12
//! forbids x 48 permits, 30 grants), then serve many evaluations:
//!
//!   * verify-shape: `(classify-all (bench-forbids) (bench-permits)
//!     (bench-edges))` — 576 hierarchy-aware classify calls per query,
//!     each transitively resolving `in` over the role DAG (`reaches`).
//!   * generate-shape: `(expand-all)` — transitive grant closure over the
//!     scaled role DAG.
//!
//! The sweep runs in-language (one eval per query, recursion inside Shen)
//! — how a real served verifier batches — so the timed region measures
//! Shen execution, not marshalling. Cedar parse/validation is load-time
//! work in the served model and stays outside this bench entirely (the
//! example wiring stage cross-checks the generated-Cedar artifact).
//!
//! Method (normal_form_aot.rs verbatim): boot, load the spec files for
//! real on the session engine (tree-walk by default, VM with
//! `SHEN_RUST_VM=1`), record reference results, time min-of-N batches,
//! `gen::install()` the klcompile AOT overlay over the loaded defuns,
//! assert shen_eq identity on every query, re-time. Loaded-vs-AOT is
//! paired in-process; tree-vs-VM is cross-process (engine is
//! process-global) — drive interleaved pairs from a shell.
//!
//! After timing, a redefinition leg redefines `base-grants` over the
//! installed overlay and asserts `(expand-all)` reflects it through the
//! AOT dispatch path — the bench doubles as a live two-table coherence
//! check (see tests/aot_redefine_coherence.rs for the focused suite).
//!
//! The AOT module is generated by the canonical recipe — fresh boot,
//! `(bootstrap <file>)` per spec file, concatenate the .kl (bench data
//! last: KL last-wins redefines authz.shen's three data defuns at bench
//! scale), `klcompile --external`, rustfmt — and checked in under
//! `benches/gen/authz_served_gen.rs` (25 compiled / 0 skipped).
//!
//!   cargo bench --bench authz_served                  # tree-walk vs AOT
//!   SHEN_RUST_VM=1 cargo bench --bench authz_served   # VM vs AOT
//!
//! KILL-GATE: the AOT arm must be >= 1.5x over the VM-loaded arm
//! (min-of-10 ms/batch, paired in-process, same-session interleaved
//! runs) with identity green before any default-on consideration.

// Generated code: keep the lint posture of klcompile output.
#![allow(
    unused_variables,
    unused_braces,
    unused_imports,
    clippy::let_and_return,
    clippy::needless_question_mark,
    clippy::redundant_clone,
    clippy::clone_on_copy,
    clippy::needless_late_init,
    clippy::len_zero,
    clippy::needless_borrow,
    clippy::approx_constant,
    clippy::redundant_closure_call,
    non_snake_case
)]

use std::path::PathBuf;
use std::time::{Duration, Instant};

use shen_rust::interp::boot::boot_with_kernel;
use shen_rust::interp::eval::Interp;
use shen_rust::kl::parser::parse_one;
use shen_rust::value::{shen_eq, Value};

mod gen {
    include!("gen/authz_served_gen.rs");
}

const ITERS: usize = 10;
const REPS: usize = 5;

const QUERIES: [&str; 2] = [
    // verify-shape: full forbid x permit sweep, hierarchy-aware.
    "(classify-all (bench-forbids) (bench-permits) (bench-edges))",
    // generate-shape: transitive grant closure over the scaled DAG.
    "(expand-all)",
];

fn main() {
    let handle = std::thread::Builder::new()
        .name("authz-served".to_string())
        .stack_size(1024 * 1024 * 1024)
        .spawn(run)
        .expect("spawn bench thread");
    std::process::exit(handle.join().unwrap_or(2));
}

fn workspace_root() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.pop();
    p.pop();
    p
}

fn eval_src(interp: &mut Interp, src: &str) -> Value {
    let expr = parse_one(src, &mut interp.symbols).unwrap_or_else(|e| panic!("parse {src:?}: {e}"));
    interp
        .eval(&expr)
        .unwrap_or_else(|e| panic!("eval {src:?}: {e}"))
}

/// One timed batch: REPS rounds of both queries.
fn batch(interp: &mut Interp) -> Duration {
    let start = Instant::now();
    for _ in 0..REPS {
        for q in &QUERIES {
            std::hint::black_box(eval_src(interp, q));
        }
    }
    start.elapsed()
}

fn min_of(interp: &mut Interp, iters: usize) -> Duration {
    (0..iters).map(|_| batch(interp)).min().expect("iters > 0")
}

fn run() -> i32 {
    let engine = if std::env::var_os("SHEN_RUST_VM").is_some() {
        "vm"
    } else {
        "tree"
    };

    let mut interp = Interp::new();
    let root = workspace_root();
    let kernel = root.join("kernel").join("klambda");
    eprint!("authz-served bench booting kernel [{engine}]… ");
    if let Err(e) = boot_with_kernel(&mut interp, &kernel) {
        eprintln!("FAILED\n  {e}");
        return 2;
    }
    eprintln!("ready.");
    interp.register_native("y-or-n?", 1, |_, _| Ok(Value::bool(true)));

    // Normal load of the committed spec + scaled data, in last-wins order
    // (bench data redefines authz.shen's three data defuns at scale —
    // the same order the gen module was compiled with). Collect the live
    // source bytes in load order for the manifest check below.
    let spec = root.join("examples").join("shen-cedar-authz").join("spec");
    let mut live_src = String::new();
    for path in [
        spec.join("verify.shen"),
        spec.join("authz.shen"),
        root.join("crates")
            .join("shen-rust")
            .join("benches")
            .join("authz_bench_data.shen"),
    ] {
        live_src.push_str(&std::fs::read_to_string(&path).expect("read spec source"));
        eval_src(&mut interp, &format!("(load \"{}\")", path.display()));
    }

    // Reference results on the loaded engine.
    let expected: Vec<Value> = QUERIES.iter().map(|q| eval_src(&mut interp, q)).collect();
    assert!(expected[0].is_cons(), "classify-all sanity: verdict matrix");
    assert!(expected[1].is_cons(), "expand-all sanity: grant list");

    // Warm + time the LOADED engine.
    let _ = batch(&mut interp);
    let loaded = min_of(&mut interp, ITERS);

    // Install the klcompile AOT versions over the loaded defuns through
    // the PRODUCTION path: manifest check (format + source FNV + kernel
    // digest) and per-name exists+arity verification, exactly what a
    // served host calls.
    let installed = interp.install_overlay_if_match(&gen::overlay(), &live_src, &kernel);
    assert!(
        installed,
        "overlay manifest must match the live sources/kernel (regenerate: \
         scripts/codegen-shen-aot.sh)"
    );

    // Same results, byte-for-byte?
    for (q, exp) in QUERIES.iter().zip(&expected) {
        let got = eval_src(&mut interp, q);
        assert!(shen_eq(&got, exp), "AOT diverged on {q}");
    }

    let _ = batch(&mut interp);
    let aot = min_of(&mut interp, ITERS);

    // Redefinition-coherence leg (after timing — it perturbs the data):
    // redefine a data defun over the installed overlay; the AOT
    // `expand-all`'s internal apply_direct edge must late-bind to it.
    let pre = eval_src(&mut interp, "(mem [r0 Eval bench-redef] (expand-all))");
    assert_eq!(pre.as_bool(), Some(false), "redef marker absent before");
    eval_src(
        &mut interp,
        "(defun base-grants () [[r0 Eval bench-redef]])",
    );
    let post = eval_src(&mut interp, "(mem [r0 Eval bench-redef] (expand-all))");
    assert_eq!(
        post.as_bool(),
        Some(true),
        "redefinition must win through the AOT overlay (two-table coherence)"
    );

    println!(
        "engine={engine}  loaded(min) {:>9.3} ms/batch   aot(min) {:>9.3} ms/batch   AOT speedup {:.2}x",
        loaded.as_secs_f64() * 1e3,
        aot.as_secs_f64() * 1e3,
        loaded.as_secs_f64() / aot.as_secs_f64()
    );
    0
}
