//! Auto-generated by `klcompile` from kernel/klambda/dict.kl.
//!
//! DO NOT EDIT. Re-run klcompile to regenerate.

#![allow(
    unused_variables,
    unused_braces,
    unused_imports,
    clippy::let_and_return,
    clippy::needless_question_mark,
    clippy::redundant_clone,
    clippy::needless_late_init,
    clippy::len_zero,
    clippy::needless_borrow,
    clippy::approx_constant,
    clippy::redundant_closure_call,
    non_snake_case
)]

use crate::aot::runtime as rt;
use crate::error::{ShenError, ShenResult};
use crate::interp::eval::Interp;
use crate::value::Value;
use std::rc::Rc;

/// AOT-compiled from KL `(defun shen.dict ...)`
pub fn aot_shen_x2e_dict(interp: &mut Interp, args: &[Value]) -> ShenResult<Value> {
    if args.len() != 1 {
        return Err(ShenError::new(format!(
            "shen.dict: expected 1 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V4138 = args[0].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let __t27 = {
                let __t19 = v_V4138.clone();
                let __t20 = Value::int(1i64);
                rt::lt(&__t19, &__t20)?
            };
            if match rt::is_truthy(interp, &__t27) {
                Ok(b) => b,
                Err(e) => break Err(e),
            } {
                break Ok({
                    let __t26 = {
                        let __t21 = Value::str("invalid initial dict size: ");
                        let __t25 = {
                            let __t22 = v_V4138.clone();
                            let __t23 = Value::str("");
                            let __t24 = Value::sym(interp.intern("shen.s"));
                            rt::apply_direct(interp, "shen.app", &[__t22, __t23, __t24])?
                        };
                        rt::apply_direct(interp, "cn", &[__t21, __t25])?
                    };
                    rt::apply_direct(interp, "simple-error", &[__t26])?
                });
            } else {
                {
                    let __t18 = Value::bool(true);
                    if match rt::is_truthy(interp, &__t18) {
                        Ok(b) => b,
                        Err(e) => break Err(e),
                    } {
                        {
                            let v_W4139 = {
                                let __t2 = {
                                    let __t0 = Value::int(3i64);
                                    let __t1 = v_V4138.clone();
                                    rt::add(&__t0, &__t1)?
                                };
                                rt::apply_direct(interp, "absvector", &[__t2])?
                            };
                            {
                                let v_W4140 = {
                                    let __t3 = v_W4139.clone();
                                    let __t4 = Value::int(0i64);
                                    let __t5 = Value::sym(interp.intern("shen.dictionary"));
                                    rt::apply_direct(interp, "address->", &[__t3, __t4, __t5])?
                                };
                                {
                                    let v_W4141 = {
                                        let __t6 = v_W4139.clone();
                                        let __t7 = Value::int(1i64);
                                        let __t8 = v_V4138.clone();
                                        rt::apply_direct(interp, "address->", &[__t6, __t7, __t8])?
                                    };
                                    {
                                        let v_W4142 = {
                                            let __t9 = v_W4139.clone();
                                            let __t10 = Value::int(2i64);
                                            let __t11 = Value::int(0i64);
                                            rt::apply_direct(
                                                interp,
                                                "address->",
                                                &[__t9, __t10, __t11],
                                            )?
                                        };
                                        {
                                            let v_W4143 = {
                                                let __t12 = v_W4139.clone();
                                                let __t13 = Value::int(3i64);
                                                let __t16 = {
                                                    let __t14 = Value::int(2i64);
                                                    let __t15 = v_V4138.clone();
                                                    rt::add(&__t14, &__t15)?
                                                };
                                                let __t17 = Value::nil();
                                                rt::apply_direct(
                                                    interp,
                                                    "shen.fillvector",
                                                    &[__t12, __t13, __t16, __t17],
                                                )?
                                            };
                                            break Ok(v_W4139.clone());
                                        }
                                    }
                                }
                            }
                        }
                    } else {
                        break Err(ShenError::new("cond: no clause matched"));
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_dict(interp: &mut Interp) {
    interp.register_native("shen.dict", 1, aot_shen_x2e_dict);
    interp.register_aot_direct("shen.dict", aot_shen_x2e_dict);
}

/// AOT-compiled from KL `(defun shen.dict? ...)`
pub fn aot_shen_x2e_dict_x3f_(interp: &mut Interp, args: &[Value]) -> ShenResult<Value> {
    if args.len() != 1 {
        return Err(ShenError::new(format!(
            "shen.dict?: expected 1 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V4144 = args[0].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let __t29 = {
                let __t28 = v_V4144.clone();
                rt::is_absvector(&__t28)
            };
            if !match rt::is_truthy(interp, &__t29) {
                Ok(b) => b,
                Err(e) => break Err(e),
            } {
                break Ok(Value::bool(false));
            } else {
                break Ok({
                    let __t32 = match (|| -> ShenResult<Value> {
                        Ok({
                            let __t30 = v_V4144.clone();
                            let __t31 = Value::int(0i64);
                            rt::apply_direct(interp, "<-address", &[__t30, __t31])?
                        })
                    })() {
                        Ok(v) => v,
                        Err(e) => {
                            let __h = {
                                rt::make_aot_closure(
                                    "<lambda>",
                                    1,
                                    move |interp, args| {
                                        let v_Z4145 = args[0].clone();
                                        Ok(Value::sym(interp.intern("shen.not-dictionary")))
                                    },
                                    Vec::new(),
                                    interp,
                                )
                            };
                            let __err = Value::err(e.message.clone());
                            rt::apply_value(interp, __h, &[__err])?
                        }
                    };
                    let __t33 = Value::sym(interp.intern("shen.dictionary"));
                    rt::eq(&__t32, &__t33)
                });
            }
        }
    }
}

fn install_shen_x2e_dict_x3f_(interp: &mut Interp) {
    interp.register_native("shen.dict?", 1, aot_shen_x2e_dict_x3f_);
    interp.register_aot_direct("shen.dict?", aot_shen_x2e_dict_x3f_);
}

/// AOT-compiled from KL `(defun shen.dict-capacity ...)`
pub fn aot_shen_x2e_dict_x2d_capacity(interp: &mut Interp, args: &[Value]) -> ShenResult<Value> {
    if args.len() != 1 {
        return Err(ShenError::new(format!(
            "shen.dict-capacity: expected 1 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V4146 = args[0].clone();
    #[allow(clippy::never_loop)]
    loop {
        break Ok({
            let __t34 = v_V4146.clone();
            let __t35 = Value::int(1i64);
            rt::apply_direct(interp, "<-address", &[__t34, __t35])?
        });
    }
}

fn install_shen_x2e_dict_x2d_capacity(interp: &mut Interp) {
    interp.register_native("shen.dict-capacity", 1, aot_shen_x2e_dict_x2d_capacity);
    interp.register_aot_direct("shen.dict-capacity", aot_shen_x2e_dict_x2d_capacity);
}

/// AOT-compiled from KL `(defun shen.dict-count ...)`
pub fn aot_shen_x2e_dict_x2d_count(interp: &mut Interp, args: &[Value]) -> ShenResult<Value> {
    if args.len() != 1 {
        return Err(ShenError::new(format!(
            "shen.dict-count: expected 1 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V4147 = args[0].clone();
    #[allow(clippy::never_loop)]
    loop {
        break Ok({
            let __t36 = v_V4147.clone();
            let __t37 = Value::int(2i64);
            rt::apply_direct(interp, "<-address", &[__t36, __t37])?
        });
    }
}

fn install_shen_x2e_dict_x2d_count(interp: &mut Interp) {
    interp.register_native("shen.dict-count", 1, aot_shen_x2e_dict_x2d_count);
    interp.register_aot_direct("shen.dict-count", aot_shen_x2e_dict_x2d_count);
}

/// AOT-compiled from KL `(defun shen.dict-count-> ...)`
pub fn aot_shen_x2e_dict_x2d_count_x2d__x3e_(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 2 {
        return Err(ShenError::new(format!(
            "shen.dict-count->: expected 2 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V4148 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V4149 = args[1].clone();
    #[allow(clippy::never_loop)]
    loop {
        break Ok({
            let __t38 = v_V4148.clone();
            let __t39 = Value::int(2i64);
            let __t40 = v_V4149.clone();
            rt::apply_direct(interp, "address->", &[__t38, __t39, __t40])?
        });
    }
}

fn install_shen_x2e_dict_x2d_count_x2d__x3e_(interp: &mut Interp) {
    interp.register_native(
        "shen.dict-count->",
        2,
        aot_shen_x2e_dict_x2d_count_x2d__x3e_,
    );
    interp.register_aot_direct("shen.dict-count->", aot_shen_x2e_dict_x2d_count_x2d__x3e_);
}

/// AOT-compiled from KL `(defun shen.<-dict-bucket ...)`
pub fn aot_shen_x2e__x3c__x2d_dict_x2d_bucket(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 2 {
        return Err(ShenError::new(format!(
            "shen.<-dict-bucket: expected 2 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V4150 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V4151 = args[1].clone();
    #[allow(clippy::never_loop)]
    loop {
        break Ok({
            let __t41 = v_V4150.clone();
            let __t44 = {
                let __t42 = Value::int(3i64);
                let __t43 = v_V4151.clone();
                rt::add(&__t42, &__t43)?
            };
            rt::apply_direct(interp, "<-address", &[__t41, __t44])?
        });
    }
}

fn install_shen_x2e__x3c__x2d_dict_x2d_bucket(interp: &mut Interp) {
    interp.register_native(
        "shen.<-dict-bucket",
        2,
        aot_shen_x2e__x3c__x2d_dict_x2d_bucket,
    );
    interp.register_aot_direct("shen.<-dict-bucket", aot_shen_x2e__x3c__x2d_dict_x2d_bucket);
}

/// AOT-compiled from KL `(defun shen.dict-bucket-> ...)`
pub fn aot_shen_x2e_dict_x2d_bucket_x2d__x3e_(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 3 {
        return Err(ShenError::new(format!(
            "shen.dict-bucket->: expected 3 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V4152 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V4153 = args[1].clone();
    #[allow(unused_mut)]
    let mut v_V4154 = args[2].clone();
    #[allow(clippy::never_loop)]
    loop {
        break Ok({
            let __t45 = v_V4152.clone();
            let __t48 = {
                let __t46 = Value::int(3i64);
                let __t47 = v_V4153.clone();
                rt::add(&__t46, &__t47)?
            };
            let __t49 = v_V4154.clone();
            rt::apply_direct(interp, "address->", &[__t45, __t48, __t49])?
        });
    }
}

fn install_shen_x2e_dict_x2d_bucket_x2d__x3e_(interp: &mut Interp) {
    interp.register_native(
        "shen.dict-bucket->",
        3,
        aot_shen_x2e_dict_x2d_bucket_x2d__x3e_,
    );
    interp.register_aot_direct("shen.dict-bucket->", aot_shen_x2e_dict_x2d_bucket_x2d__x3e_);
}

/// AOT-compiled from KL `(defun shen.dict-update-count ...)`
pub fn aot_shen_x2e_dict_x2d_update_x2d_count(
    interp: &mut Interp,
    args: &[Value],
) -> ShenResult<Value> {
    if args.len() != 3 {
        return Err(ShenError::new(format!(
            "shen.dict-update-count: expected 3 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V4155 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V4156 = args[1].clone();
    #[allow(unused_mut)]
    let mut v_V4157 = args[2].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let v_W4158 = {
                let __t51 = {
                    let __t50 = v_V4157.clone();
                    rt::apply_direct(interp, "length", &[__t50])?
                };
                let __t53 = {
                    let __t52 = v_V4156.clone();
                    rt::apply_direct(interp, "length", &[__t52])?
                };
                rt::sub(&__t51, &__t53)?
            };
            break Ok({
                let __t54 = v_V4155.clone();
                let __t58 = {
                    let __t55 = v_W4158.clone();
                    let __t57 = {
                        let __t56 = v_V4155.clone();
                        rt::apply_direct(interp, "shen.dict-count", &[__t56])?
                    };
                    rt::add(&__t55, &__t57)?
                };
                rt::apply_direct(interp, "shen.dict-count->", &[__t54, __t58])?
            });
        }
    }
}

fn install_shen_x2e_dict_x2d_update_x2d_count(interp: &mut Interp) {
    interp.register_native(
        "shen.dict-update-count",
        3,
        aot_shen_x2e_dict_x2d_update_x2d_count,
    );
    interp.register_aot_direct(
        "shen.dict-update-count",
        aot_shen_x2e_dict_x2d_update_x2d_count,
    );
}

/// AOT-compiled from KL `(defun shen.dict-> ...)`
pub fn aot_shen_x2e_dict_x2d__x3e_(interp: &mut Interp, args: &[Value]) -> ShenResult<Value> {
    if args.len() != 3 {
        return Err(ShenError::new(format!(
            "shen.dict->: expected 3 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V4159 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V4160 = args[1].clone();
    #[allow(unused_mut)]
    let mut v_V4161 = args[2].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let v_W4162 = {
                let __t59 = v_V4160.clone();
                let __t61 = {
                    let __t60 = v_V4159.clone();
                    rt::apply_direct(interp, "shen.dict-capacity", &[__t60])?
                };
                rt::apply_direct(interp, "hash", &[__t59, __t61])?
            };
            {
                let v_W4163 = {
                    let __t62 = v_V4159.clone();
                    let __t63 = v_W4162.clone();
                    rt::apply_direct(interp, "shen.<-dict-bucket", &[__t62, __t63])?
                };
                {
                    let v_W4164 = {
                        let __t64 = v_V4160.clone();
                        let __t65 = v_V4161.clone();
                        let __t66 = v_W4163.clone();
                        rt::apply_direct(interp, "shen.assoc-set", &[__t64, __t65, __t66])?
                    };
                    {
                        let v_W4165 = {
                            let __t67 = v_V4159.clone();
                            let __t68 = v_W4162.clone();
                            let __t69 = v_W4164.clone();
                            rt::apply_direct(interp, "shen.dict-bucket->", &[__t67, __t68, __t69])?
                        };
                        {
                            let v_W4166 = {
                                let __t70 = v_V4159.clone();
                                let __t71 = v_W4163.clone();
                                let __t72 = v_W4164.clone();
                                rt::apply_direct(
                                    interp,
                                    "shen.dict-update-count",
                                    &[__t70, __t71, __t72],
                                )?
                            };
                            break Ok(v_V4161.clone());
                        }
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_dict_x2d__x3e_(interp: &mut Interp) {
    interp.register_native("shen.dict->", 3, aot_shen_x2e_dict_x2d__x3e_);
    interp.register_aot_direct("shen.dict->", aot_shen_x2e_dict_x2d__x3e_);
}

/// AOT-compiled from KL `(defun shen.<-dict ...)`
pub fn aot_shen_x2e__x3c__x2d_dict(interp: &mut Interp, args: &[Value]) -> ShenResult<Value> {
    if args.len() != 2 {
        return Err(ShenError::new(format!(
            "shen.<-dict: expected 2 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V4167 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V4168 = args[1].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let v_W4169 = {
                let __t73 = v_V4168.clone();
                let __t75 = {
                    let __t74 = v_V4167.clone();
                    rt::apply_direct(interp, "shen.dict-capacity", &[__t74])?
                };
                rt::apply_direct(interp, "hash", &[__t73, __t75])?
            };
            {
                let v_W4170 = {
                    let __t76 = v_V4167.clone();
                    let __t77 = v_W4169.clone();
                    rt::apply_direct(interp, "shen.<-dict-bucket", &[__t76, __t77])?
                };
                {
                    let v_W4171 = {
                        let __t78 = v_V4168.clone();
                        let __t79 = v_W4170.clone();
                        rt::apply_direct(interp, "assoc", &[__t78, __t79])?
                    };
                    {
                        let __t81 = {
                            let __t80 = v_W4171.clone();
                            rt::apply_direct(interp, "empty?", &[__t80])?
                        };
                        if match rt::is_truthy(interp, &__t81) {
                            Ok(b) => b,
                            Err(e) => break Err(e),
                        } {
                            break Ok({
                                let __t87 = {
                                    let __t82 = Value::str("value ");
                                    let __t86 = {
                                        let __t83 = v_V4168.clone();
                                        let __t84 = Value::str(" not found in dict\n");
                                        let __t85 = Value::sym(interp.intern("shen.a"));
                                        rt::apply_direct(
                                            interp,
                                            "shen.app",
                                            &[__t83, __t84, __t85],
                                        )?
                                    };
                                    rt::apply_direct(interp, "cn", &[__t82, __t86])?
                                };
                                rt::apply_direct(interp, "simple-error", &[__t87])?
                            });
                        } else {
                            break Ok({
                                let __t88 = v_W4171.clone();
                                rt::tl(&__t88)?
                            });
                        }
                    }
                }
            }
        }
    }
}

fn install_shen_x2e__x3c__x2d_dict(interp: &mut Interp) {
    interp.register_native("shen.<-dict", 2, aot_shen_x2e__x3c__x2d_dict);
    interp.register_aot_direct("shen.<-dict", aot_shen_x2e__x3c__x2d_dict);
}

/// AOT-compiled from KL `(defun shen.dict-rm ...)`
pub fn aot_shen_x2e_dict_x2d_rm(interp: &mut Interp, args: &[Value]) -> ShenResult<Value> {
    if args.len() != 2 {
        return Err(ShenError::new(format!(
            "shen.dict-rm: expected 2 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V4172 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V4173 = args[1].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let v_W4174 = {
                let __t89 = v_V4173.clone();
                let __t91 = {
                    let __t90 = v_V4172.clone();
                    rt::apply_direct(interp, "shen.dict-capacity", &[__t90])?
                };
                rt::apply_direct(interp, "hash", &[__t89, __t91])?
            };
            {
                let v_W4175 = {
                    let __t92 = v_V4172.clone();
                    let __t93 = v_W4174.clone();
                    rt::apply_direct(interp, "shen.<-dict-bucket", &[__t92, __t93])?
                };
                {
                    let v_W4176 = {
                        let __t94 = v_V4173.clone();
                        let __t95 = v_W4175.clone();
                        rt::apply_direct(interp, "shen.assoc-rm", &[__t94, __t95])?
                    };
                    {
                        let v_W4177 = {
                            let __t96 = v_V4172.clone();
                            let __t97 = v_W4174.clone();
                            let __t98 = v_W4176.clone();
                            rt::apply_direct(interp, "shen.dict-bucket->", &[__t96, __t97, __t98])?
                        };
                        {
                            let v_W4178 = {
                                let __t99 = v_V4172.clone();
                                let __t100 = v_W4175.clone();
                                let __t101 = v_W4176.clone();
                                rt::apply_direct(
                                    interp,
                                    "shen.dict-update-count",
                                    &[__t99, __t100, __t101],
                                )?
                            };
                            break Ok(v_V4173.clone());
                        }
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_dict_x2d_rm(interp: &mut Interp) {
    interp.register_native("shen.dict-rm", 2, aot_shen_x2e_dict_x2d_rm);
    interp.register_aot_direct("shen.dict-rm", aot_shen_x2e_dict_x2d_rm);
}

/// AOT-compiled from KL `(defun shen.dict-fold ...)`
pub fn aot_shen_x2e_dict_x2d_fold(interp: &mut Interp, args: &[Value]) -> ShenResult<Value> {
    if args.len() != 3 {
        return Err(ShenError::new(format!(
            "shen.dict-fold: expected 3 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V4179 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V4180 = args[1].clone();
    #[allow(unused_mut)]
    let mut v_V4181 = args[2].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let v_W4182 = {
                let __t102 = v_V4180.clone();
                rt::apply_direct(interp, "shen.dict-capacity", &[__t102])?
            };
            break Ok({
                let __t103 = v_V4179.clone();
                let __t104 = v_V4180.clone();
                let __t105 = v_V4181.clone();
                let __t106 = Value::int(0i64);
                let __t107 = v_W4182.clone();
                rt::apply_direct(
                    interp,
                    "shen.dict-fold-h",
                    &[__t103, __t104, __t105, __t106, __t107],
                )?
            });
        }
    }
}

fn install_shen_x2e_dict_x2d_fold(interp: &mut Interp) {
    interp.register_native("shen.dict-fold", 3, aot_shen_x2e_dict_x2d_fold);
    interp.register_aot_direct("shen.dict-fold", aot_shen_x2e_dict_x2d_fold);
}

/// AOT-compiled from KL `(defun shen.dict-fold-h ...)`
pub fn aot_shen_x2e_dict_x2d_fold_x2d_h(interp: &mut Interp, args: &[Value]) -> ShenResult<Value> {
    if args.len() != 5 {
        return Err(ShenError::new(format!(
            "shen.dict-fold-h: expected 5 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V4184 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V4185 = args[1].clone();
    #[allow(unused_mut)]
    let mut v_V4186 = args[2].clone();
    #[allow(unused_mut)]
    let mut v_V4187 = args[3].clone();
    #[allow(unused_mut)]
    let mut v_V4188 = args[4].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let __t123 = {
                let __t121 = v_V4187.clone();
                let __t122 = v_V4188.clone();
                rt::eq(&__t121, &__t122)
            };
            if match rt::is_truthy(interp, &__t123) {
                Ok(b) => b,
                Err(e) => break Err(e),
            } {
                break Ok(v_V4186.clone());
            } else {
                {
                    let __t120 = Value::bool(true);
                    if match rt::is_truthy(interp, &__t120) {
                        Ok(b) => b,
                        Err(e) => break Err(e),
                    } {
                        {
                            let v_W4189 = {
                                let __t108 = v_V4185.clone();
                                let __t109 = v_V4187.clone();
                                rt::apply_direct(interp, "shen.<-dict-bucket", &[__t108, __t109])?
                            };
                            {
                                let v_W4190 = {
                                    let __t110 = v_V4184.clone();
                                    let __t111 = v_W4189.clone();
                                    let __t112 = v_V4186.clone();
                                    rt::apply_direct(
                                        interp,
                                        "shen.bucket-fold",
                                        &[__t110, __t111, __t112],
                                    )?
                                };
                                {
                                    let __t113 = v_V4184.clone();
                                    let __t114 = v_V4185.clone();
                                    let __t115 = v_W4190.clone();
                                    let __t118 = {
                                        let __t116 = Value::int(1i64);
                                        let __t117 = v_V4187.clone();
                                        rt::add(&__t116, &__t117)?
                                    };
                                    let __t119 = v_V4188.clone();
                                    v_V4184 = __t113;
                                    v_V4185 = __t114;
                                    v_V4186 = __t115;
                                    v_V4187 = __t118;
                                    v_V4188 = __t119;
                                    continue;
                                }
                            }
                        }
                    } else {
                        break Err(ShenError::new("cond: no clause matched"));
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_dict_x2d_fold_x2d_h(interp: &mut Interp) {
    interp.register_native("shen.dict-fold-h", 5, aot_shen_x2e_dict_x2d_fold_x2d_h);
    interp.register_aot_direct("shen.dict-fold-h", aot_shen_x2e_dict_x2d_fold_x2d_h);
}

/// AOT-compiled from KL `(defun shen.bucket-fold ...)`
pub fn aot_shen_x2e_bucket_x2d_fold(interp: &mut Interp, args: &[Value]) -> ShenResult<Value> {
    if args.len() != 3 {
        return Err(ShenError::new(format!(
            "shen.bucket-fold: expected 3 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V4191 = args[0].clone();
    #[allow(unused_mut)]
    let mut v_V4192 = args[1].clone();
    #[allow(unused_mut)]
    let mut v_V4193 = args[2].clone();
    #[allow(clippy::never_loop)]
    loop {
        {
            let __t147 = {
                let __t145 = Value::nil();
                let __t146 = v_V4192.clone();
                rt::eq(&__t145, &__t146)
            };
            if match rt::is_truthy(interp, &__t147) {
                Ok(b) => b,
                Err(e) => break Err(e),
            } {
                break Ok(v_V4193.clone());
            } else {
                {
                    let __t144 = {
                        let __t129 = {
                            let __t126 = v_V4192.clone();
                            rt::is_cons(&__t126)
                        };
                        if !rt::is_truthy(interp, &__t129)? {
                            Value::bool(false)
                        } else {
                            let __t130 = {
                                let __t128 = {
                                    let __t127 = v_V4192.clone();
                                    rt::hd(&__t127)?
                                };
                                rt::is_cons(&__t128)
                            };
                            Value::bool(rt::is_truthy(interp, &__t130)?)
                        }
                    };
                    if match rt::is_truthy(interp, &__t144) {
                        Ok(b) => b,
                        Err(e) => break Err(e),
                    } {
                        break Ok({
                            let __t138 = {
                                let __t134 = {
                                    let __t133 = {
                                        let __t132 = {
                                            let __t131 = v_V4192.clone();
                                            rt::hd(&__t131)?
                                        };
                                        rt::hd(&__t132)?
                                    };
                                    rt::apply_value(interp, v_V4191.clone(), &[__t133])?
                                };
                                let __t137 = {
                                    let __t136 = {
                                        let __t135 = v_V4192.clone();
                                        rt::hd(&__t135)?
                                    };
                                    rt::tl(&__t136)?
                                };
                                rt::apply_value(interp, __t134, &[__t137])?
                            };
                            let __t143 = {
                                let __t139 = v_V4191.clone();
                                let __t141 = {
                                    let __t140 = v_V4192.clone();
                                    rt::tl(&__t140)?
                                };
                                let __t142 = v_V4193.clone();
                                rt::apply_direct(
                                    interp,
                                    "shen.bucket-fold",
                                    &[__t139, __t141, __t142],
                                )?
                            };
                            rt::apply_value(interp, __t138, &[__t143])?
                        });
                    } else {
                        {
                            let __t125 = Value::bool(true);
                            if match rt::is_truthy(interp, &__t125) {
                                Ok(b) => b,
                                Err(e) => break Err(e),
                            } {
                                break Ok({
                                    let __t124 = Value::sym(interp.intern("shen.bucket-fold"));
                                    rt::apply_direct(interp, "shen.f-error", &[__t124])?
                                });
                            } else {
                                break Err(ShenError::new("cond: no clause matched"));
                            }
                        }
                    }
                }
            }
        }
    }
}

fn install_shen_x2e_bucket_x2d_fold(interp: &mut Interp) {
    interp.register_native("shen.bucket-fold", 3, aot_shen_x2e_bucket_x2d_fold);
    interp.register_aot_direct("shen.bucket-fold", aot_shen_x2e_bucket_x2d_fold);
}

/// AOT-compiled from KL `(defun shen.dict-keys ...)`
pub fn aot_shen_x2e_dict_x2d_keys(interp: &mut Interp, args: &[Value]) -> ShenResult<Value> {
    if args.len() != 1 {
        return Err(ShenError::new(format!(
            "shen.dict-keys: expected 1 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V4194 = args[0].clone();
    #[allow(clippy::never_loop)]
    loop {
        break Ok({
            let __t150 = {
                rt::make_aot_closure(
                    "<lambda>",
                    1,
                    move |interp, args| {
                        let v_Z4195 = args[0].clone();
                        Ok({
                            let v_Z4195 = v_Z4195.clone();
                            rt::make_aot_closure(
                                "<lambda>",
                                1,
                                move |interp, args| {
                                    let v_Z4196 = args[0].clone();
                                    Ok({
                                        let v_Z4195 = v_Z4195.clone();
                                        rt::make_aot_closure(
                                            "<lambda>",
                                            1,
                                            move |interp, args| {
                                                let v_Z4197 = args[0].clone();
                                                Ok({
                                                    let __t148 = v_Z4195.clone();
                                                    let __t149 = v_Z4197.clone();
                                                    rt::cons(&__t148, &__t149)
                                                })
                                            },
                                            vec![v_Z4195],
                                            interp,
                                        )
                                    })
                                },
                                vec![v_Z4195],
                                interp,
                            )
                        })
                    },
                    Vec::new(),
                    interp,
                )
            };
            let __t151 = v_V4194.clone();
            let __t152 = Value::nil();
            rt::apply_direct(interp, "shen.dict-fold", &[__t150, __t151, __t152])?
        });
    }
}

fn install_shen_x2e_dict_x2d_keys(interp: &mut Interp) {
    interp.register_native("shen.dict-keys", 1, aot_shen_x2e_dict_x2d_keys);
    interp.register_aot_direct("shen.dict-keys", aot_shen_x2e_dict_x2d_keys);
}

/// AOT-compiled from KL `(defun shen.dict-values ...)`
pub fn aot_shen_x2e_dict_x2d_values(interp: &mut Interp, args: &[Value]) -> ShenResult<Value> {
    if args.len() != 1 {
        return Err(ShenError::new(format!(
            "shen.dict-values: expected 1 args, got {}",
            args.len()
        )));
    }
    #[allow(unused_mut)]
    let mut v_V4198 = args[0].clone();
    #[allow(clippy::never_loop)]
    loop {
        break Ok({
            let __t155 = {
                rt::make_aot_closure(
                    "<lambda>",
                    1,
                    move |interp, args| {
                        let v_Z4199 = args[0].clone();
                        Ok({
                            rt::make_aot_closure(
                                "<lambda>",
                                1,
                                move |interp, args| {
                                    let v_Z4200 = args[0].clone();
                                    Ok({
                                        let v_Z4200 = v_Z4200.clone();
                                        rt::make_aot_closure(
                                            "<lambda>",
                                            1,
                                            move |interp, args| {
                                                let v_Z4201 = args[0].clone();
                                                Ok({
                                                    let __t153 = v_Z4200.clone();
                                                    let __t154 = v_Z4201.clone();
                                                    rt::cons(&__t153, &__t154)
                                                })
                                            },
                                            vec![v_Z4200],
                                            interp,
                                        )
                                    })
                                },
                                Vec::new(),
                                interp,
                            )
                        })
                    },
                    Vec::new(),
                    interp,
                )
            };
            let __t156 = v_V4198.clone();
            let __t157 = Value::nil();
            rt::apply_direct(interp, "shen.dict-fold", &[__t155, __t156, __t157])?
        });
    }
}

fn install_shen_x2e_dict_x2d_values(interp: &mut Interp) {
    interp.register_native("shen.dict-values", 1, aot_shen_x2e_dict_x2d_values);
    interp.register_aot_direct("shen.dict-values", aot_shen_x2e_dict_x2d_values);
}

/// Register every AOT-compiled function on `interp`. Call after kernel
/// boot so these names override the tree-walked defuns.
pub fn install(interp: &mut Interp) {
    install_shen_x2e_dict(interp);
    install_shen_x2e_dict_x3f_(interp);
    install_shen_x2e_dict_x2d_capacity(interp);
    install_shen_x2e_dict_x2d_count(interp);
    install_shen_x2e_dict_x2d_count_x2d__x3e_(interp);
    install_shen_x2e__x3c__x2d_dict_x2d_bucket(interp);
    install_shen_x2e_dict_x2d_bucket_x2d__x3e_(interp);
    install_shen_x2e_dict_x2d_update_x2d_count(interp);
    install_shen_x2e_dict_x2d__x3e_(interp);
    install_shen_x2e__x3c__x2d_dict(interp);
    install_shen_x2e_dict_x2d_rm(interp);
    install_shen_x2e_dict_x2d_fold(interp);
    install_shen_x2e_dict_x2d_fold_x2d_h(interp);
    install_shen_x2e_bucket_x2d_fold(interp);
    install_shen_x2e_dict_x2d_keys(interp);
    install_shen_x2e_dict_x2d_values(interp);
}
